// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AckSignals
    {
        [DataMember(Name = "signal_ids")]
        public System.Collections.Generic.List<ulong> SignalIds;

        public AckSignals(System.Collections.Generic.List<ulong> SignalIds)
        {
            this.SignalIds = SignalIds;
        }

        public AckSignals()
        {
            this.SignalIds = new();
        }
    }
}
