// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Artifact
    {
        [DataMember(Name = "artifact_id")]
        public string ArtifactId;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "attempt_id")]
        public string AttemptId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "storage_key")]
        public string StorageKey;
        [DataMember(Name = "filename")]
        public string Filename;
        [DataMember(Name = "content_type")]
        public string ContentType;
        [DataMember(Name = "declared_bytes")]
        public ulong? DeclaredBytes;
        [DataMember(Name = "verified_bytes")]
        public ulong? VerifiedBytes;
        [DataMember(Name = "sha_256")]
        public string? Sha256;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "status_reason")]
        public string? StatusReason;
        [DataMember(Name = "job_id")]
        public string? JobId;
        [DataMember(Name = "job_run")]
        public uint? JobRun;
        [DataMember(Name = "created_by")]
        public SpacetimeDB.Identity CreatedBy;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "available_at")]
        public SpacetimeDB.Timestamp? AvailableAt;

        public Artifact(
            string ArtifactId,
            string SessionId,
            string AttemptId,
            string Kind,
            string StorageKey,
            string Filename,
            string ContentType,
            ulong? DeclaredBytes,
            ulong? VerifiedBytes,
            string? Sha256,
            string Status,
            string? StatusReason,
            string? JobId,
            uint? JobRun,
            SpacetimeDB.Identity CreatedBy,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp? AvailableAt
        )
        {
            this.ArtifactId = ArtifactId;
            this.SessionId = SessionId;
            this.AttemptId = AttemptId;
            this.Kind = Kind;
            this.StorageKey = StorageKey;
            this.Filename = Filename;
            this.ContentType = ContentType;
            this.DeclaredBytes = DeclaredBytes;
            this.VerifiedBytes = VerifiedBytes;
            this.Sha256 = Sha256;
            this.Status = Status;
            this.StatusReason = StatusReason;
            this.JobId = JobId;
            this.JobRun = JobRun;
            this.CreatedBy = CreatedBy;
            this.CreatedAt = CreatedAt;
            this.AvailableAt = AvailableAt;
        }

        public Artifact()
        {
            this.ArtifactId = "";
            this.SessionId = "";
            this.AttemptId = "";
            this.Kind = "";
            this.StorageKey = "";
            this.Filename = "";
            this.ContentType = "";
            this.Status = "";
        }
    }
}
