// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Attempt
    {
        [DataMember(Name = "attempt_id")]
        public string AttemptId;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "ordinal")]
        public uint Ordinal;
        [DataMember(Name = "exercise_id")]
        public string ExerciseId;
        [DataMember(Name = "exercise_version")]
        public string ExerciseVersion;
        [DataMember(Name = "started_at")]
        public SpacetimeDB.Timestamp StartedAt;
        [DataMember(Name = "ended_at")]
        public SpacetimeDB.Timestamp? EndedAt;
        [DataMember(Name = "practice_status")]
        public string PracticeStatus;
        [DataMember(Name = "result_summary")]
        public string? ResultSummary;
        [DataMember(Name = "steps_completed")]
        public uint StepsCompleted;
        [DataMember(Name = "steps_total")]
        public uint StepsTotal;
        [DataMember(Name = "mistakes")]
        public uint Mistakes;
        [DataMember(Name = "hints_used")]
        public uint HintsUsed;

        public Attempt(
            string AttemptId,
            string SessionId,
            uint Ordinal,
            string ExerciseId,
            string ExerciseVersion,
            SpacetimeDB.Timestamp StartedAt,
            SpacetimeDB.Timestamp? EndedAt,
            string PracticeStatus,
            string? ResultSummary,
            uint StepsCompleted,
            uint StepsTotal,
            uint Mistakes,
            uint HintsUsed
        )
        {
            this.AttemptId = AttemptId;
            this.SessionId = SessionId;
            this.Ordinal = Ordinal;
            this.ExerciseId = ExerciseId;
            this.ExerciseVersion = ExerciseVersion;
            this.StartedAt = StartedAt;
            this.EndedAt = EndedAt;
            this.PracticeStatus = PracticeStatus;
            this.ResultSummary = ResultSummary;
            this.StepsCompleted = StepsCompleted;
            this.StepsTotal = StepsTotal;
            this.Mistakes = Mistakes;
            this.HintsUsed = HintsUsed;
        }

        public Attempt()
        {
            this.AttemptId = "";
            this.SessionId = "";
            this.ExerciseId = "";
            this.ExerciseVersion = "";
            this.PracticeStatus = "";
        }
    }
}
