// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClaimMotionJob
    {
        [DataMember(Name = "job_id")]
        public string JobId;
        [DataMember(Name = "expected_run")]
        public uint ExpectedRun;
        [DataMember(Name = "worker_id")]
        public string WorkerId;
        [DataMember(Name = "lease_ms")]
        public uint LeaseMs;

        public ClaimMotionJob(
            string JobId,
            uint ExpectedRun,
            string WorkerId,
            uint LeaseMs
        )
        {
            this.JobId = JobId;
            this.ExpectedRun = ExpectedRun;
            this.WorkerId = WorkerId;
            this.LeaseMs = LeaseMs;
        }

        public ClaimMotionJob()
        {
            this.JobId = "";
            this.WorkerId = "";
        }
    }
}
