// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CoachMessage
    {
        [DataMember(Name = "message_id")]
        public ulong MessageId;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "attempt_id")]
        public string AttemptId;
        [DataMember(Name = "speaker")]
        public string Speaker;
        [DataMember(Name = "text")]
        public string Text;
        [DataMember(Name = "at")]
        public SpacetimeDB.Timestamp At;

        public CoachMessage(
            ulong MessageId,
            string SessionId,
            string AttemptId,
            string Speaker,
            string Text,
            SpacetimeDB.Timestamp At
        )
        {
            this.MessageId = MessageId;
            this.SessionId = SessionId;
            this.AttemptId = AttemptId;
            this.Speaker = Speaker;
            this.Text = Text;
            this.At = At;
        }

        public CoachMessage()
        {
            this.SessionId = "";
            this.AttemptId = "";
            this.Speaker = "";
            this.Text = "";
        }
    }
}
