// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ConfirmArtifact
    {
        [DataMember(Name = "artifact_id")]
        public string ArtifactId;
        [DataMember(Name = "ok")]
        public bool Ok;
        [DataMember(Name = "verified_bytes")]
        public ulong? VerifiedBytes;
        [DataMember(Name = "reason")]
        public string? Reason;

        public ConfirmArtifact(
            string ArtifactId,
            bool Ok,
            ulong? VerifiedBytes,
            string? Reason
        )
        {
            this.ArtifactId = ArtifactId;
            this.Ok = Ok;
            this.VerifiedBytes = VerifiedBytes;
            this.Reason = Reason;
        }

        public ConfirmArtifact()
        {
            this.ArtifactId = "";
        }
    }
}
