// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CreateSession
    {
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "label")]
        public string Label;
        [DataMember(Name = "exercise_id")]
        public string ExerciseId;
        [DataMember(Name = "exercise_version")]
        public string ExerciseVersion;
        [DataMember(Name = "display_name")]
        public string DisplayName;

        public CreateSession(
            string SessionId,
            string Label,
            string ExerciseId,
            string ExerciseVersion,
            string DisplayName
        )
        {
            this.SessionId = SessionId;
            this.Label = Label;
            this.ExerciseId = ExerciseId;
            this.ExerciseVersion = ExerciseVersion;
            this.DisplayName = DisplayName;
        }

        public CreateSession()
        {
            this.SessionId = "";
            this.Label = "";
            this.ExerciseId = "";
            this.ExerciseVersion = "";
            this.DisplayName = "";
        }
    }
}
