// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DenyGrant
    {
        [DataMember(Name = "grant_id")]
        public string GrantId;
        [DataMember(Name = "reason")]
        public string Reason;

        public DenyGrant(
            string GrantId,
            string Reason
        )
        {
            this.GrantId = GrantId;
            this.Reason = Reason;
        }

        public DenyGrant()
        {
            this.GrantId = "";
            this.Reason = "";
        }
    }
}
