// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EncounterEvent
    {
        [DataMember(Name = "event_id")]
        public ulong EventId;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "encounter_id")]
        public string EncounterId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "item_id")]
        public string ItemId;
        [DataMember(Name = "speaker")]
        public string? Speaker;
        [DataMember(Name = "text")]
        public string Text;
        [DataMember(Name = "at")]
        public SpacetimeDB.Timestamp At;

        public EncounterEvent(
            ulong EventId,
            string SessionId,
            string EncounterId,
            string Kind,
            string ItemId,
            string? Speaker,
            string Text,
            SpacetimeDB.Timestamp At
        )
        {
            this.EventId = EventId;
            this.SessionId = SessionId;
            this.EncounterId = EncounterId;
            this.Kind = Kind;
            this.ItemId = ItemId;
            this.Speaker = Speaker;
            this.Text = Text;
            this.At = At;
        }

        public EncounterEvent()
        {
            this.SessionId = "";
            this.EncounterId = "";
            this.Kind = "";
            this.ItemId = "";
            this.Text = "";
        }
    }
}
