// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ExerciseEvent
    {
        [DataMember(Name = "event_id")]
        public ulong EventId;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "attempt_id")]
        public string AttemptId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "step_id")]
        public string? StepId;
        [DataMember(Name = "structure_id")]
        public string? StructureId;
        [DataMember(Name = "message")]
        public string Message;
        [DataMember(Name = "device_time_ms")]
        public double? DeviceTimeMs;
        [DataMember(Name = "at")]
        public SpacetimeDB.Timestamp At;

        public ExerciseEvent(
            ulong EventId,
            string SessionId,
            string AttemptId,
            string Kind,
            string? StepId,
            string? StructureId,
            string Message,
            double? DeviceTimeMs,
            SpacetimeDB.Timestamp At
        )
        {
            this.EventId = EventId;
            this.SessionId = SessionId;
            this.AttemptId = AttemptId;
            this.Kind = Kind;
            this.StepId = StepId;
            this.StructureId = StructureId;
            this.Message = Message;
            this.DeviceTimeMs = DeviceTimeMs;
            this.At = At;
        }

        public ExerciseEvent()
        {
            this.SessionId = "";
            this.AttemptId = "";
            this.Kind = "";
            this.Message = "";
        }
    }
}
