// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ExerciseState
    {
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "attempt_id")]
        public string AttemptId;
        [DataMember(Name = "exercise_id")]
        public string ExerciseId;
        [DataMember(Name = "exercise_version")]
        public string ExerciseVersion;
        [DataMember(Name = "mode")]
        public string Mode;
        [DataMember(Name = "step_id")]
        public string? StepId;
        [DataMember(Name = "step_index")]
        public uint StepIndex;
        [DataMember(Name = "step_count")]
        public uint StepCount;
        [DataMember(Name = "selected_structure_id")]
        public string? SelectedStructureId;
        [DataMember(Name = "highlighted_structure_id")]
        public string? HighlightedStructureId;
        [DataMember(Name = "preview_rotating")]
        public bool PreviewRotating;
        [DataMember(Name = "paused")]
        public bool Paused;
        [DataMember(Name = "registration")]
        public string Registration;
        [DataMember(Name = "registration_reason")]
        public string? RegistrationReason;
        [DataMember(Name = "recording")]
        public string Recording;
        [DataMember(Name = "state_version")]
        public ulong StateVersion;
        [DataMember(Name = "step_version")]
        public ulong StepVersion;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;
        [DataMember(Name = "updated_by")]
        public SpacetimeDB.Identity UpdatedBy;

        public ExerciseState(
            string SessionId,
            string AttemptId,
            string ExerciseId,
            string ExerciseVersion,
            string Mode,
            string? StepId,
            uint StepIndex,
            uint StepCount,
            string? SelectedStructureId,
            string? HighlightedStructureId,
            bool PreviewRotating,
            bool Paused,
            string Registration,
            string? RegistrationReason,
            string Recording,
            ulong StateVersion,
            ulong StepVersion,
            SpacetimeDB.Timestamp UpdatedAt,
            SpacetimeDB.Identity UpdatedBy
        )
        {
            this.SessionId = SessionId;
            this.AttemptId = AttemptId;
            this.ExerciseId = ExerciseId;
            this.ExerciseVersion = ExerciseVersion;
            this.Mode = Mode;
            this.StepId = StepId;
            this.StepIndex = StepIndex;
            this.StepCount = StepCount;
            this.SelectedStructureId = SelectedStructureId;
            this.HighlightedStructureId = HighlightedStructureId;
            this.PreviewRotating = PreviewRotating;
            this.Paused = Paused;
            this.Registration = Registration;
            this.RegistrationReason = RegistrationReason;
            this.Recording = Recording;
            this.StateVersion = StateVersion;
            this.StepVersion = StepVersion;
            this.UpdatedAt = UpdatedAt;
            this.UpdatedBy = UpdatedBy;
        }

        public ExerciseState()
        {
            this.SessionId = "";
            this.AttemptId = "";
            this.ExerciseId = "";
            this.ExerciseVersion = "";
            this.Mode = "";
            this.Registration = "";
            this.Recording = "";
        }
    }
}
