// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class FailMotionJob
    {
        [DataMember(Name = "job_id")]
        public string JobId;
        [DataMember(Name = "run")]
        public uint Run;
        [DataMember(Name = "error")]
        public string Error;
        [DataMember(Name = "retryable")]
        public bool Retryable;

        public FailMotionJob(
            string JobId,
            uint Run,
            string Error,
            bool Retryable
        )
        {
            this.JobId = JobId;
            this.Run = Run;
            this.Error = Error;
            this.Retryable = Retryable;
        }

        public FailMotionJob()
        {
            this.JobId = "";
            this.Error = "";
        }
    }
}
