// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HeartbeatMotionJob
    {
        [DataMember(Name = "job_id")]
        public string JobId;
        [DataMember(Name = "run")]
        public uint Run;
        [DataMember(Name = "progress")]
        public double? Progress;
        [DataMember(Name = "stage")]
        public string? Stage;
        [DataMember(Name = "lease_ms")]
        public uint LeaseMs;

        public HeartbeatMotionJob(
            string JobId,
            uint Run,
            double? Progress,
            string? Stage,
            uint LeaseMs
        )
        {
            this.JobId = JobId;
            this.Run = Run;
            this.Progress = Progress;
            this.Stage = Stage;
            this.LeaseMs = LeaseMs;
        }

        public HeartbeatMotionJob()
        {
            this.JobId = "";
        }
    }
}
