// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class IssueGrant
    {
        [DataMember(Name = "grant_id")]
        public string GrantId;
        [DataMember(Name = "url")]
        public string Url;
        [DataMember(Name = "method")]
        public string Method;
        [DataMember(Name = "ttl_ms")]
        public uint TtlMs;

        public IssueGrant(
            string GrantId,
            string Url,
            string Method,
            uint TtlMs
        )
        {
            this.GrantId = GrantId;
            this.Url = Url;
            this.Method = Method;
            this.TtlMs = TtlMs;
        }

        public IssueGrant()
        {
            this.GrantId = "";
            this.Url = "";
            this.Method = "";
        }
    }
}
