// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class JoinSession
    {
        [DataMember(Name = "code")]
        public string Code;
        [DataMember(Name = "display_name")]
        public string DisplayName;

        public JoinSession(
            string Code,
            string DisplayName
        )
        {
            this.Code = Code;
            this.DisplayName = DisplayName;
        }

        public JoinSession()
        {
            this.Code = "";
            this.DisplayName = "";
        }
    }
}
