// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Membership
    {
        [DataMember(Name = "membership_id")]
        public ulong MembershipId;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "role")]
        public string Role;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "joined_at")]
        public SpacetimeDB.Timestamp JoinedAt;

        public Membership(
            ulong MembershipId,
            string SessionId,
            SpacetimeDB.Identity Identity,
            string Role,
            string DisplayName,
            SpacetimeDB.Timestamp JoinedAt
        )
        {
            this.MembershipId = MembershipId;
            this.SessionId = SessionId;
            this.Identity = Identity;
            this.Role = Role;
            this.DisplayName = DisplayName;
            this.JoinedAt = JoinedAt;
        }

        public Membership()
        {
            this.SessionId = "";
            this.Role = "";
            this.DisplayName = "";
        }
    }
}
