// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MotionJob
    {
        [DataMember(Name = "job_id")]
        public string JobId;
        [DataMember(Name = "dedupe_key")]
        public string DedupeKey;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "attempt_id")]
        public string AttemptId;
        [DataMember(Name = "input_artifact_id")]
        public string InputArtifactId;
        [DataMember(Name = "extra_artifact_ids")]
        public System.Collections.Generic.List<string> ExtraArtifactIds;
        [DataMember(Name = "config_version")]
        public string ConfigVersion;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "run")]
        public uint Run;
        [DataMember(Name = "max_runs")]
        public uint MaxRuns;
        [DataMember(Name = "worker_id")]
        public string? WorkerId;
        [DataMember(Name = "lease_expires_at")]
        public SpacetimeDB.Timestamp? LeaseExpiresAt;
        [DataMember(Name = "progress")]
        public double? Progress;
        [DataMember(Name = "stage")]
        public string? Stage;
        [DataMember(Name = "output_artifact_ids")]
        public System.Collections.Generic.List<string> OutputArtifactIds;
        [DataMember(Name = "quality")]
        public QualitySummary? Quality;
        [DataMember(Name = "error")]
        public string? Error;
        [DataMember(Name = "requested_by")]
        public SpacetimeDB.Identity RequestedBy;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public MotionJob(
            string JobId,
            string DedupeKey,
            string SessionId,
            string AttemptId,
            string InputArtifactId,
            System.Collections.Generic.List<string> ExtraArtifactIds,
            string ConfigVersion,
            string Status,
            uint Run,
            uint MaxRuns,
            string? WorkerId,
            SpacetimeDB.Timestamp? LeaseExpiresAt,
            double? Progress,
            string? Stage,
            System.Collections.Generic.List<string> OutputArtifactIds,
            QualitySummary? Quality,
            string? Error,
            SpacetimeDB.Identity RequestedBy,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.JobId = JobId;
            this.DedupeKey = DedupeKey;
            this.SessionId = SessionId;
            this.AttemptId = AttemptId;
            this.InputArtifactId = InputArtifactId;
            this.ExtraArtifactIds = ExtraArtifactIds;
            this.ConfigVersion = ConfigVersion;
            this.Status = Status;
            this.Run = Run;
            this.MaxRuns = MaxRuns;
            this.WorkerId = WorkerId;
            this.LeaseExpiresAt = LeaseExpiresAt;
            this.Progress = Progress;
            this.Stage = Stage;
            this.OutputArtifactIds = OutputArtifactIds;
            this.Quality = Quality;
            this.Error = Error;
            this.RequestedBy = RequestedBy;
            this.CreatedAt = CreatedAt;
            this.UpdatedAt = UpdatedAt;
        }

        public MotionJob()
        {
            this.JobId = "";
            this.DedupeKey = "";
            this.SessionId = "";
            this.AttemptId = "";
            this.InputArtifactId = "";
            this.ExtraArtifactIds = new();
            this.ConfigVersion = "";
            this.Status = "";
            this.OutputArtifactIds = new();
        }
    }
}
