// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PatientCondition
    {
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "coach_session_id")]
        public string CoachSessionId;
        [DataMember(Name = "baseline_hr")]
        public double BaselineHr;
        [DataMember(Name = "baseline_rr")]
        public double BaselineRr;
        [DataMember(Name = "baseline_sys")]
        public double BaselineSys;
        [DataMember(Name = "baseline_dia")]
        public double BaselineDia;
        [DataMember(Name = "baseline_spo_2")]
        public double BaselineSpo2;
        [DataMember(Name = "baseline_source")]
        public string BaselineSource;
        [DataMember(Name = "weight_kg")]
        public double WeightKg;
        [DataMember(Name = "ml_per_kg")]
        public double MlPerKg;
        [DataMember(Name = "ebv_ml")]
        public double EbvMl;
        [DataMember(Name = "scale")]
        public double Scale;
        [DataMember(Name = "hr")]
        public int Hr;
        [DataMember(Name = "rr")]
        public int Rr;
        [DataMember(Name = "sys")]
        public int Sys;
        [DataMember(Name = "dia")]
        public int Dia;
        [DataMember(Name = "spo_2")]
        public int Spo2;
        [DataMember(Name = "blood_loss_pct")]
        public double BloodLossPct;
        [DataMember(Name = "hemorrhage_class")]
        public uint HemorrhageClass;
        [DataMember(Name = "label")]
        public string Label;
        [DataMember(Name = "body_lost_ml")]
        public double BodyLostMl;
        [DataMember(Name = "region_lost_ml")]
        public double RegionLostMl;
        [DataMember(Name = "blood_lost_ml")]
        public double BloodLostMl;
        [DataMember(Name = "body_bleed_ml_per_min")]
        public double BodyBleedMlPerMin;
        [DataMember(Name = "active_bleeds_json")]
        public string ActiveBleedsJson;
        [DataMember(Name = "region_injuries_json")]
        public string RegionInjuriesJson;
        [DataMember(Name = "outcome_result")]
        public string OutcomeResult;
        [DataMember(Name = "outcome_cause")]
        public string OutcomeCause;
        [DataMember(Name = "outcome_at")]
        public SpacetimeDB.Timestamp? OutcomeAt;
        [DataMember(Name = "version")]
        public ulong Version;
        [DataMember(Name = "started_at")]
        public SpacetimeDB.Timestamp StartedAt;
        [DataMember(Name = "advanced_at")]
        public SpacetimeDB.Timestamp AdvancedAt;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;

        public PatientCondition(
            string SessionId,
            string CoachSessionId,
            double BaselineHr,
            double BaselineRr,
            double BaselineSys,
            double BaselineDia,
            double BaselineSpo2,
            string BaselineSource,
            double WeightKg,
            double MlPerKg,
            double EbvMl,
            double Scale,
            int Hr,
            int Rr,
            int Sys,
            int Dia,
            int Spo2,
            double BloodLossPct,
            uint HemorrhageClass,
            string Label,
            double BodyLostMl,
            double RegionLostMl,
            double BloodLostMl,
            double BodyBleedMlPerMin,
            string ActiveBleedsJson,
            string RegionInjuriesJson,
            string OutcomeResult,
            string OutcomeCause,
            SpacetimeDB.Timestamp? OutcomeAt,
            ulong Version,
            SpacetimeDB.Timestamp StartedAt,
            SpacetimeDB.Timestamp AdvancedAt,
            SpacetimeDB.Timestamp UpdatedAt
        )
        {
            this.SessionId = SessionId;
            this.CoachSessionId = CoachSessionId;
            this.BaselineHr = BaselineHr;
            this.BaselineRr = BaselineRr;
            this.BaselineSys = BaselineSys;
            this.BaselineDia = BaselineDia;
            this.BaselineSpo2 = BaselineSpo2;
            this.BaselineSource = BaselineSource;
            this.WeightKg = WeightKg;
            this.MlPerKg = MlPerKg;
            this.EbvMl = EbvMl;
            this.Scale = Scale;
            this.Hr = Hr;
            this.Rr = Rr;
            this.Sys = Sys;
            this.Dia = Dia;
            this.Spo2 = Spo2;
            this.BloodLossPct = BloodLossPct;
            this.HemorrhageClass = HemorrhageClass;
            this.Label = Label;
            this.BodyLostMl = BodyLostMl;
            this.RegionLostMl = RegionLostMl;
            this.BloodLostMl = BloodLostMl;
            this.BodyBleedMlPerMin = BodyBleedMlPerMin;
            this.ActiveBleedsJson = ActiveBleedsJson;
            this.RegionInjuriesJson = RegionInjuriesJson;
            this.OutcomeResult = OutcomeResult;
            this.OutcomeCause = OutcomeCause;
            this.OutcomeAt = OutcomeAt;
            this.Version = Version;
            this.StartedAt = StartedAt;
            this.AdvancedAt = AdvancedAt;
            this.UpdatedAt = UpdatedAt;
        }

        public PatientCondition()
        {
            this.SessionId = "";
            this.CoachSessionId = "";
            this.BaselineSource = "";
            this.Label = "";
            this.ActiveBleedsJson = "";
            this.RegionInjuriesJson = "";
            this.OutcomeResult = "";
            this.OutcomeCause = "";
        }
    }
}
