// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class QualitySummary
    {
        [DataMember(Name = "frames_total")]
        public uint FramesTotal;
        [DataMember(Name = "frames_valid")]
        public uint FramesValid;
        [DataMember(Name = "invalid_intervals")]
        public uint InvalidIntervals;
        [DataMember(Name = "robot_model")]
        public string RobotModel;
        [DataMember(Name = "replay_kind")]
        public string ReplayKind;
        [DataMember(Name = "notes")]
        public string Notes;

        public QualitySummary(
            uint FramesTotal,
            uint FramesValid,
            uint InvalidIntervals,
            string RobotModel,
            string ReplayKind,
            string Notes
        )
        {
            this.FramesTotal = FramesTotal;
            this.FramesValid = FramesValid;
            this.InvalidIntervals = InvalidIntervals;
            this.RobotModel = RobotModel;
            this.ReplayKind = ReplayKind;
            this.Notes = Notes;
        }

        public QualitySummary()
        {
            this.RobotModel = "";
            this.ReplayKind = "";
            this.Notes = "";
        }
    }
}
