// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RemoveMember
    {
        [DataMember(Name = "membership_id")]
        public ulong MembershipId;

        public RemoveMember(ulong MembershipId)
        {
            this.MembershipId = MembershipId;
        }

        public RemoveMember()
        {
        }
    }
}
