// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ReplayState
    {
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "artifact_id")]
        public string? ArtifactId;
        [DataMember(Name = "playing")]
        public bool Playing;
        [DataMember(Name = "position_ms")]
        public double PositionMs;
        [DataMember(Name = "rate")]
        public double Rate;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;
        [DataMember(Name = "updated_by")]
        public SpacetimeDB.Identity UpdatedBy;

        public ReplayState(
            string SessionId,
            string? ArtifactId,
            bool Playing,
            double PositionMs,
            double Rate,
            SpacetimeDB.Timestamp UpdatedAt,
            SpacetimeDB.Identity UpdatedBy
        )
        {
            this.SessionId = SessionId;
            this.ArtifactId = ArtifactId;
            this.Playing = Playing;
            this.PositionMs = PositionMs;
            this.Rate = Rate;
            this.UpdatedAt = UpdatedAt;
            this.UpdatedBy = UpdatedBy;
        }

        public ReplayState()
        {
            this.SessionId = "";
        }
    }
}
