// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ReportInjury
    {
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "region")]
        public string Region;
        [DataMember(Name = "controlled")]
        public bool Controlled;

        public ReportInjury(
            string SessionId,
            string Region,
            bool Controlled
        )
        {
            this.SessionId = SessionId;
            this.Region = Region;
            this.Controlled = Controlled;
        }

        public ReportInjury()
        {
            this.SessionId = "";
            this.Region = "";
        }
    }
}
