// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RequestServiceGrant
    {
        [DataMember(Name = "grant_id")]
        public string GrantId;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "kind")]
        public string Kind;

        public RequestServiceGrant(
            string GrantId,
            string SessionId,
            string Kind
        )
        {
            this.GrantId = GrantId;
            this.SessionId = SessionId;
            this.Kind = Kind;
        }

        public RequestServiceGrant()
        {
            this.GrantId = "";
            this.SessionId = "";
            this.Kind = "";
        }
    }
}
