// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RequestMotionJob
    {
        [DataMember(Name = "job_id")]
        public string JobId;
        [DataMember(Name = "input_artifact_id")]
        public string InputArtifactId;
        [DataMember(Name = "extra_artifact_ids")]
        public System.Collections.Generic.List<string> ExtraArtifactIds;
        [DataMember(Name = "config_version")]
        public string ConfigVersion;

        public RequestMotionJob(
            string JobId,
            string InputArtifactId,
            System.Collections.Generic.List<string> ExtraArtifactIds,
            string ConfigVersion
        )
        {
            this.JobId = JobId;
            this.InputArtifactId = InputArtifactId;
            this.ExtraArtifactIds = ExtraArtifactIds;
            this.ConfigVersion = ConfigVersion;
        }

        public RequestMotionJob()
        {
            this.JobId = "";
            this.InputArtifactId = "";
            this.ExtraArtifactIds = new();
            this.ConfigVersion = "";
        }
    }
}
