// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RequestDownload
    {
        [DataMember(Name = "grant_id")]
        public string GrantId;
        [DataMember(Name = "artifact_id")]
        public string ArtifactId;

        public RequestDownload(
            string GrantId,
            string ArtifactId
        )
        {
            this.GrantId = GrantId;
            this.ArtifactId = ArtifactId;
        }

        public RequestDownload()
        {
            this.GrantId = "";
            this.ArtifactId = "";
        }
    }
}
