// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RobotResult
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "attempt_id")]
        public string AttemptId;
        [DataMember(Name = "step_id")]
        public string StepId;
        [DataMember(Name = "success")]
        public bool Success;
        [DataMember(Name = "path_error_mm")]
        public double? PathErrorMm;
        [DataMember(Name = "policy_success_rate")]
        public double? PolicySuccessRate;
        [DataMember(Name = "demos_human")]
        public uint DemosHuman;
        [DataMember(Name = "demos_synthetic")]
        public uint DemosSynthetic;
        [DataMember(Name = "video_url")]
        public string? VideoUrl;
        [DataMember(Name = "at")]
        public SpacetimeDB.Timestamp At;

        public RobotResult(
            ulong Id,
            string SessionId,
            string AttemptId,
            string StepId,
            bool Success,
            double? PathErrorMm,
            double? PolicySuccessRate,
            uint DemosHuman,
            uint DemosSynthetic,
            string? VideoUrl,
            SpacetimeDB.Timestamp At
        )
        {
            this.Id = Id;
            this.SessionId = SessionId;
            this.AttemptId = AttemptId;
            this.StepId = StepId;
            this.Success = Success;
            this.PathErrorMm = PathErrorMm;
            this.PolicySuccessRate = PolicySuccessRate;
            this.DemosHuman = DemosHuman;
            this.DemosSynthetic = DemosSynthetic;
            this.VideoUrl = VideoUrl;
            this.At = At;
        }

        public RobotResult()
        {
            this.SessionId = "";
            this.AttemptId = "";
            this.StepId = "";
        }
    }
}
