// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RotateInvite
    {
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "role")]
        public string Role;

        public RotateInvite(
            string SessionId,
            string Role
        )
        {
            this.SessionId = SessionId;
            this.Role = Role;
        }

        public RotateInvite()
        {
            this.SessionId = "";
            this.Role = "";
        }
    }
}
