// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ServiceGrant
    {
        [DataMember(Name = "grant_id")]
        public string GrantId;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "requested_by")]
        public SpacetimeDB.Identity RequestedBy;
        [DataMember(Name = "requested_at")]
        public SpacetimeDB.Timestamp RequestedAt;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "payload")]
        public string? Payload;
        [DataMember(Name = "reason")]
        public string? Reason;
        [DataMember(Name = "expires_at")]
        public SpacetimeDB.Timestamp? ExpiresAt;

        public ServiceGrant(
            string GrantId,
            string SessionId,
            string Kind,
            SpacetimeDB.Identity RequestedBy,
            SpacetimeDB.Timestamp RequestedAt,
            string Status,
            string? Payload,
            string? Reason,
            SpacetimeDB.Timestamp? ExpiresAt
        )
        {
            this.GrantId = GrantId;
            this.SessionId = SessionId;
            this.Kind = Kind;
            this.RequestedBy = RequestedBy;
            this.RequestedAt = RequestedAt;
            this.Status = Status;
            this.Payload = Payload;
            this.Reason = Reason;
            this.ExpiresAt = ExpiresAt;
        }

        public ServiceGrant()
        {
            this.GrantId = "";
            this.SessionId = "";
            this.Kind = "";
            this.Status = "";
        }
    }
}
