// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ServiceFlag
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "label")]
        public string Label;

        public ServiceFlag(
            SpacetimeDB.Identity Identity,
            string Label
        )
        {
            this.Identity = Identity;
            this.Label = Label;
        }

        public ServiceFlag()
        {
            this.Label = "";
        }
    }
}
