// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Session
    {
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "label")]
        public string Label;
        [DataMember(Name = "created_by")]
        public SpacetimeDB.Identity CreatedBy;
        [DataMember(Name = "created_at")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "exercise_id")]
        public string ExerciseId;
        [DataMember(Name = "exercise_version")]
        public string ExerciseVersion;
        [DataMember(Name = "current_attempt_id")]
        public string CurrentAttemptId;
        [DataMember(Name = "attempt_count")]
        public uint AttemptCount;
        [DataMember(Name = "ended_at")]
        public SpacetimeDB.Timestamp? EndedAt;

        public Session(
            string SessionId,
            string Label,
            SpacetimeDB.Identity CreatedBy,
            SpacetimeDB.Timestamp CreatedAt,
            string Status,
            string ExerciseId,
            string ExerciseVersion,
            string CurrentAttemptId,
            uint AttemptCount,
            SpacetimeDB.Timestamp? EndedAt
        )
        {
            this.SessionId = SessionId;
            this.Label = Label;
            this.CreatedBy = CreatedBy;
            this.CreatedAt = CreatedAt;
            this.Status = Status;
            this.ExerciseId = ExerciseId;
            this.ExerciseVersion = ExerciseVersion;
            this.CurrentAttemptId = CurrentAttemptId;
            this.AttemptCount = AttemptCount;
            this.EndedAt = EndedAt;
        }

        public Session()
        {
            this.SessionId = "";
            this.Label = "";
            this.Status = "";
            this.ExerciseId = "";
            this.ExerciseVersion = "";
            this.CurrentAttemptId = "";
        }
    }
}
