// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SetAttemptResult
    {
        [DataMember(Name = "attempt_id")]
        public string AttemptId;
        [DataMember(Name = "practice_status")]
        public string PracticeStatus;
        [DataMember(Name = "steps_completed")]
        public uint StepsCompleted;
        [DataMember(Name = "steps_total")]
        public uint StepsTotal;
        [DataMember(Name = "mistakes")]
        public uint Mistakes;
        [DataMember(Name = "hints_used")]
        public uint HintsUsed;
        [DataMember(Name = "result_summary")]
        public string? ResultSummary;

        public SetAttemptResult(
            string AttemptId,
            string PracticeStatus,
            uint StepsCompleted,
            uint StepsTotal,
            uint Mistakes,
            uint HintsUsed,
            string? ResultSummary
        )
        {
            this.AttemptId = AttemptId;
            this.PracticeStatus = PracticeStatus;
            this.StepsCompleted = StepsCompleted;
            this.StepsTotal = StepsTotal;
            this.Mistakes = Mistakes;
            this.HintsUsed = HintsUsed;
            this.ResultSummary = ResultSummary;
        }

        public SetAttemptResult()
        {
            this.AttemptId = "";
            this.PracticeStatus = "";
        }
    }
}
