// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SetCoachStatus
    {
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "detail")]
        public string? Detail;

        public SetCoachStatus(
            string SessionId,
            string Status,
            string? Detail
        )
        {
            this.SessionId = SessionId;
            this.Status = Status;
            this.Detail = Detail;
        }

        public SetCoachStatus()
        {
            this.SessionId = "";
            this.Status = "";
        }
    }
}
