// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SetEncounterPhase
    {
        [DataMember(Name = "encounter_id")]
        public string EncounterId;
        [DataMember(Name = "phase")]
        public string Phase;

        public SetEncounterPhase(
            string EncounterId,
            string Phase
        )
        {
            this.EncounterId = EncounterId;
            this.Phase = Phase;
        }

        public SetEncounterPhase()
        {
            this.EncounterId = "";
            this.Phase = "";
        }
    }
}
