// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SetEncounterResult
    {
        [DataMember(Name = "encounter_id")]
        public string EncounterId;
        [DataMember(Name = "score_total")]
        public uint ScoreTotal;
        [DataMember(Name = "grade")]
        public string Grade;
        [DataMember(Name = "scorecard_json")]
        public string ScorecardJson;

        public SetEncounterResult(
            string EncounterId,
            uint ScoreTotal,
            string Grade,
            string ScorecardJson
        )
        {
            this.EncounterId = EncounterId;
            this.ScoreTotal = ScoreTotal;
            this.Grade = Grade;
            this.ScorecardJson = ScorecardJson;
        }

        public SetEncounterResult()
        {
            this.EncounterId = "";
            this.Grade = "";
            this.ScorecardJson = "";
        }
    }
}
