// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SetMediaSource
    {
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "status")]
        public string Status;
        [DataMember(Name = "label")]
        public string? Label;
        [DataMember(Name = "detail")]
        public string? Detail;
        [DataMember(Name = "width")]
        public uint? Width;
        [DataMember(Name = "height")]
        public uint? Height;

        public SetMediaSource(
            string SessionId,
            string Status,
            string? Label,
            string? Detail,
            uint? Width,
            uint? Height
        )
        {
            this.SessionId = SessionId;
            this.Status = Status;
            this.Label = Label;
            this.Detail = Detail;
            this.Width = Width;
            this.Height = Height;
        }

        public SetMediaSource()
        {
            this.SessionId = "";
            this.Status = "";
        }
    }
}
