// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SimLog
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "session_id")]
        public string SessionId;
        [DataMember(Name = "coach_session_id")]
        public string CoachSessionId;
        [DataMember(Name = "kind")]
        public string Kind;
        [DataMember(Name = "text")]
        public string Text;
        [DataMember(Name = "data_json")]
        public string DataJson;
        [DataMember(Name = "at")]
        public SpacetimeDB.Timestamp At;

        public SimLog(
            ulong Id,
            string SessionId,
            string CoachSessionId,
            string Kind,
            string Text,
            string DataJson,
            SpacetimeDB.Timestamp At
        )
        {
            this.Id = Id;
            this.SessionId = SessionId;
            this.CoachSessionId = CoachSessionId;
            this.Kind = Kind;
            this.Text = Text;
            this.DataJson = DataJson;
            this.At = At;
        }

        public SimLog()
        {
            this.SessionId = "";
            this.CoachSessionId = "";
            this.Kind = "";
            this.Text = "";
            this.DataJson = "";
        }
    }
}
