// Authored patient encounters: the 1-on-1 interview before surgery. Keyed by the same plan subject as
// CASE_PLANS, so a sandbox patient gets the encounter of the demo patient its scenario mirrors.
//
// The patient agent never holds these facts in its prompt. It must call answer/examine/order_test, which
// return one fact at a time and log what the learner actually elicited. That keeps the patient from
// inventing history and makes scoring deterministic. Medications, allergies, and problems come from the
// FinchNode chart unless an encounter overrides them (a patient can tell you what an empty chart cannot).
// Illustrative teaching content, not clinical guidance.

export const HISTORY_TOPICS = [
  "chief_complaint",
  "onset",
  "location",
  "migration",
  "character",
  "severity",
  "aggravating_relieving",
  "nausea_vomiting",
  "appetite",
  "fever",
  "bowel",
  "urinary",
  "menstrual_pregnancy",
  "last_meal",
  "past_medical",
  "past_surgical",
  "medications",
  "allergies",
  "social",
  "family",
  "recent_illness",
] as const;
export type HistoryTopic = (typeof HISTORY_TOPICS)[number];

export const EXAM_MANEUVERS = [
  "general_appearance",
  "vitals",
  "abdomen_inspection",
  "abdomen_palpation",
  "mcburney_point",
  "rebound",
  "guarding_rigidity",
  "rovsing",
  "psoas",
  "obturator",
  "murphy",
  "cva_tenderness",
  "chest_lungs",
  "genitourinary",
  "pelvic",
] as const;
export type ExamManeuver = (typeof EXAM_MANEUVERS)[number];

export const TESTS = [
  "cbc",
  "crp",
  "bmp",
  "lactate",
  "lipase",
  "urinalysis",
  "pregnancy_test",
  "lfts",
  "ultrasound",
  "ct_abdomen_pelvis",
  "type_and_screen",
] as const;
export type TestId = (typeof TESTS)[number];

export type RubricItem =
  | { kind: "history"; id: HistoryTopic; why: string }
  | { kind: "exam"; id: ExamManeuver; why: string }
  | { kind: "test"; id: TestId; why: string };

export interface DifferentialItem {
  id: string;
  label: string;
  keywords: string[]; // any match counts
}

// Voice presets for the person talking. Ids live in DEFAULT_PATIENT_VOICES (src/encounter.ts).
export const PATIENT_VOICE_KEYS = [
  "adult_female",
  "parent_female",
  "adult_male",
  "mature_female",
  "middle_female",
  "older_female",
  "senior_female",
  "middle_male",
] as const;
export type PatientVoiceKey = (typeof PATIENT_VOICE_KEYS)[number];

export interface Encounter {
  planSubject: string;
  persona: {
    speaker: "patient" | "parent";
    name: string; // who is talking
    patientName: string; // who is sick
    age: number; // the sick patient's age
    sex: "female" | "male"; // the sick patient's sex, not the speaker's: a mother can speak for her son
    // Only for a chart the patient chose not to share demographics with. The guard then requires that the
    // chart really has no name, age, or sex, and the learner must confirm identity in person.
    chartDemographics?: "not_shared";
    voiceKey: PatientVoiceKey;
    demeanor: string; // how they talk, for the persona prompt
    // Who they are as a person: life, personality, mood arc, lay worries. Never symptoms, medications,
    // allergies, history, exam, or results: the learner earns those by asking, through the tools.
    character?: string;
    opener: string; // first line, before any questions
  };
  history: Partial<Record<HistoryTopic, string>>; // first person, plain language; missing topics fall back to the chart or "not sure"
  exam: Partial<Record<ExamManeuver, { reaction: string; finding: string }>>;
  tests: Partial<Record<TestId, { result: string; abnormal: boolean }>>;
  diagnosis: { label: string; keywords: string[][]; partial?: { label: string; keywords: string[][] } }; // every group must match
  procedureKeywords: string[][];
  urgency: "elective" | "urgent" | "emergency";
  differential: DifferentialItem[];
  critical: RubricItem[]; // missing any of these is called out first
  expected: RubricItem[];
  testNotes?: Partial<Record<TestId, string>>; // teaching notes when a test is ordered (e.g. radiation in children)
}

const ddx = (id: string, label: string, ...keywords: string[]): DifferentialItem => ({ id, label, keywords });

const COMMON_APPY_EXPECTED: RubricItem[] = [
  { kind: "history", id: "onset", why: "Timing separates early appendicitis from perforation." },
  { kind: "history", id: "migration", why: "Pain that starts at the umbilicus and moves to the right lower quadrant is the classic appendicitis pattern." },
  { kind: "history", id: "nausea_vomiting", why: "Anorexia and nausea after the pain starts support appendicitis." },
  { kind: "history", id: "fever", why: "Fever points to inflammation and, when high, to perforation." },
  { kind: "history", id: "bowel", why: "Diarrhea or blood suggests gastroenteritis or colitis instead." },
  { kind: "history", id: "urinary", why: "Urinary symptoms point to infection or a stone." },
  { kind: "history", id: "past_surgical", why: "A prior appendectomy rules the diagnosis out." },
  { kind: "history", id: "medications", why: "Anticoagulants, steroids, and other drugs change the plan." },
  { kind: "exam", id: "vitals", why: "Tachycardia and fever set urgency and flag sepsis." },
  { kind: "exam", id: "abdomen_palpation", why: "Localized right lower quadrant tenderness is the key finding." },
  { kind: "exam", id: "rebound", why: "Rebound tenderness signals peritoneal irritation." },
  { kind: "test", id: "cbc", why: "Leukocytosis supports the diagnosis and the Alvarado score." },
  { kind: "test", id: "urinalysis", why: "Rules out urinary infection and stones." },
];

const CHOLE_PROCEDURE_KEYWORDS = ["cholecystectomy", "remove the gallbladder", "take out the gallbladder", "take the gallbladder out", "gallbladder removal", "gallbladder out"];

export const ENCOUNTERS: Encounter[] = [
  {
    planSubject: "patient-demo-multi-source",
    persona: {
      speaker: "patient",
      name: "Priya Ramaswamy",
      patientName: "Priya Ramaswamy",
      age: 40,
      sex: "female",
      voiceKey: "adult_female",
      demeanor: "An accountant, articulate and a little anxious. Lies still because moving hurts. Answers directly, sometimes asks what a medical term means.",
      character:
        "You're a senior accountant at a property-management company, and quarter-end next week is on your mind. Your husband Arjun, a high-school chemistry teacher, drove you in; your daughter Meera is eleven. You run a slow 5K on Saturdays and bake banana bread on Sundays. You're clear, organized, a bit formal, and polite: you say 'sorry' when you wince, often start with 'Honestly,' and ask 'What does that mean?' for any medical word. You never exaggerate or minimize. You're anxious, tired after a bad night, and trying to be a good patient. If the doctor sounds sure something needs doing, you say 'Okay. Okay.' and then ask practical things: how long, when you can get back to work, who picks up Meera. At first you wondered if it was something you ate at the office.",
      opener: "Hi, sorry, I'm trying not to move much. My stomach has been killing me since yesterday.",
    },
    history: {
      chief_complaint: "My stomach really hurts, down on the right side.",
      onset: "It started yesterday morning, around nine. It came on slowly, not all at once.",
      location: "Right now it's low on the right side, about here.",
      migration: "It actually started around my belly button, kind of dull. By the afternoon it moved down to the right and got sharper.",
      character: "It's constant and sharp now. It never fully goes away.",
      severity: "Maybe a seven out of ten. The car ride over was awful, every bump hurt.",
      aggravating_relieving: "Moving, coughing, and bumps make it worse. Lying still helps a little. I took ibuprofen last night and it barely touched it.",
      nausea_vomiting: "I've been nauseous since the pain started, but I haven't thrown up.",
      appetite: "I haven't wanted to eat anything since yesterday.",
      fever: "I felt hot and had chills last night. I didn't check my temperature.",
      bowel: "My last bowel movement was yesterday morning and it was normal. No diarrhea, no blood.",
      urinary: "No burning or blood when I pee. Maybe going a little more often, I'm not sure.",
      menstrual_pregnancy: "My last period was about two weeks ago, it was normal. I don't think I'm pregnant, but I'm not on any birth control right now.",
      last_meal: "I had a small dinner at around seven last night, just soup. Only water since then, last sip about two hours ago.",
      past_surgical: "No surgeries. I've never been operated on.",
      social: "I'm an accountant. I don't smoke, I have a glass of wine on weekends.",
      family: "Nothing like this in my family that I know of.",
      recent_illness: "No, I haven't been sick lately.",
    },
    exam: {
      general_appearance: { reaction: "", finding: "Uncomfortable, lying still with knees slightly bent, avoids moving." },
      vitals: { reaction: "", finding: "Temperature 37.9 C, heart rate 98, blood pressure 124/78, respiratory rate 16, oxygen saturation 99% on room air." },
      abdomen_inspection: { reaction: "", finding: "Flat abdomen, no scars, no distension." },
      abdomen_palpation: { reaction: "Ow! Yes, right there, that's the spot.", finding: "Tender in the right lower quadrant with voluntary guarding. Left side soft and nontender." },
      mcburney_point: { reaction: "Ah, yes, that's exactly where it hurts.", finding: "Maximal tenderness at McBurney's point." },
      rebound: { reaction: "Ow, letting go was worse than pushing!", finding: "Rebound tenderness in the right lower quadrant." },
      guarding_rigidity: { reaction: "I'm tensing up, sorry, I can't help it.", finding: "Voluntary guarding in the right lower quadrant, no generalized rigidity." },
      rovsing: { reaction: "Wait, pushing on the left made my right side hurt.", finding: "Positive Rovsing sign." },
      psoas: { reaction: "That pulls on the right side a bit.", finding: "Mildly positive right psoas sign." },
      obturator: { reaction: "That's fine, it doesn't really hurt.", finding: "Negative obturator sign." },
      murphy: { reaction: "No, that's okay up there.", finding: "Negative Murphy sign, no right upper quadrant tenderness." },
      cva_tenderness: { reaction: "No, my back is fine.", finding: "No costovertebral angle tenderness." },
      chest_lungs: { reaction: "", finding: "Lungs clear to auscultation." },
      pelvic: { reaction: "Okay, that's uncomfortable but not the bad pain.", finding: "No cervical motion tenderness, no adnexal mass or tenderness, no discharge." },
    },
    tests: {
      cbc: { result: "White count 13.1 with 82% neutrophils. Hemoglobin 11.6 (low, consistent with her known iron deficiency). Platelets 280.", abnormal: true },
      crp: { result: "CRP 48 mg/L (elevated).", abnormal: true },
      bmp: { result: "Sodium 138, potassium 4.1, creatinine 0.8, glucose 96. Normal kidney function.", abnormal: false },
      lactate: { result: "Lactate 1.2 (normal).", abnormal: false },
      lipase: { result: "Lipase 32 (normal).", abnormal: false },
      urinalysis: { result: "No blood, no leukocyte esterase, no nitrites. Normal.", abnormal: false },
      pregnancy_test: { result: "Serum beta-hCG negative.", abnormal: false },
      ultrasound: { result: "Appendix not clearly visualized. No free fluid. Ovaries normal with normal flow.", abnormal: false },
      ct_abdomen_pelvis: { result: "Dilated 11 mm appendix with periappendiceal fat stranding. No abscess, no free air.", abnormal: true },
      type_and_screen: { result: "Type O positive, antibody screen negative.", abnormal: false },
    },
    diagnosis: { label: "Acute appendicitis", keywords: [["appendicitis", "appendix"]] },
    procedureKeywords: [["appendectomy", "appendicectomy", "remove the appendix", "take out the appendix", "take the appendix out"]],
    urgency: "urgent",
    differential: [
      ddx("ectopic", "Ectopic pregnancy", "ectopic"),
      ddx("torsion", "Ovarian torsion", "torsion", "ovarian"),
      ddx("cyst", "Ruptured ovarian cyst", "cyst"),
      ddx("pid", "Pelvic inflammatory disease or tubo-ovarian abscess", "pid", "pelvic inflammatory", "tubo"),
      ddx("stone", "Ureteric stone", "stone", "kidney", "renal colic", "ureter"),
      ddx("uti", "Urinary tract infection or pyelonephritis", "uti", "urinary", "pyelo"),
      ddx("crohns", "Crohn's disease or terminal ileitis", "crohn", "ileitis", "ibd"),
      ddx("adenitis", "Mesenteric adenitis", "adenitis", "lymph"),
    ],
    critical: [
      { kind: "history", id: "allergies", why: "She has a high-severity latex allergy: the room, gloves, and catheters must be latex free." },
      { kind: "history", id: "menstrual_pregnancy", why: "A woman of reproductive age with right lower quadrant pain needs pregnancy excluded: ectopic pregnancy is the can't-miss diagnosis." },
      { kind: "test", id: "pregnancy_test", why: "History alone does not exclude pregnancy. Order a beta-hCG before imaging and surgery." },
      { kind: "history", id: "last_meal", why: "Last oral intake sets anesthesia timing and aspiration risk." },
    ],
    expected: [
      ...COMMON_APPY_EXPECTED,
      { kind: "history", id: "past_medical", why: "Her anemia lowers her tolerance for blood loss." },
      { kind: "test", id: "ct_abdomen_pelvis", why: "In an adult with an equivocal ultrasound, CT confirms the diagnosis." },
    ],
  },
  {
    planSubject: "patient-demo-pediatric-asthma",
    persona: {
      speaker: "parent",
      name: "Laura Abernathy",
      patientName: "Theo Abernathy",
      age: 9,
      sex: "male",
      voiceKey: "parent_female",
      demeanor: "Theo's mom. Worried but organized, knows his medical history well. Speaks for Theo and sometimes relays what he says ('he says it hurts more when he walks').",
      character:
        "You're 41, a dental office manager, and you left work to bring Theo in. His dad Mark drives for UPS and is coming as soon as he can; his little sister Ruby is at grandma's. Theo loves Pokemon cards, Minecraft, and playing defense on his Saturday soccer team, and he's clutching a stuffed shark called Chompy that he says he's too old for. You're calm on the surface and efficient, and when stressed you list things. You start with 'Okay, so...' and check with Theo: 'Right, buddy?' Theo is a quiet, tired kid who uses small words. You get more anxious and protective when the exam makes him cry, and you ask people to tell him before they touch him. Last night you thought it was a stomach bug, and you're a little defensive that you waited overnight. Once there's a plan you want to call Mark.",
      opener: "Hi, I'm Laura, Theo's mom. He's been miserable since last night and he won't let anyone touch his belly.",
    },
    history: {
      chief_complaint: "His tummy hurts, on the lower right side now.",
      onset: "It started last night around six, before dinner. Maybe eighteen hours ago.",
      location: "He points to the lower right side of his belly.",
      migration: "At first he said it was around his belly button. This morning he said it moved down to the right.",
      character: "He says it's a sharp, steady pain. It doesn't come and go.",
      severity: "He says eight. He's usually tough about this stuff.",
      aggravating_relieving: "He's walking hunched over. The car ride here made him cry, and he won't jump or run. Lying curled up helps a bit.",
      nausea_vomiting: "He threw up once this morning. He's been nauseous since last night.",
      appetite: "He didn't want his pizza last night, and he never refuses pizza.",
      fever: "He felt warm, I checked this morning and it was 38.0.",
      bowel: "His last poop was yesterday and it was normal. No diarrhea.",
      urinary: "No complaints about peeing.",
      last_meal: "A few crackers around seven last night. Just sips of water this morning, the last about an hour ago.",
      past_surgical: "He's never had surgery.",
      social: "He's in third grade. Nobody smokes at home.",
      family: "No one in the family has had problems with anesthesia that I know of.",
      recent_illness: "No colds or stomach bugs lately. Nobody at home is sick.",
      past_medical: "He has asthma, it's well controlled. He's never been hospitalized for it or needed a breathing tube. He has eczema too. His vaccines are up to date.",
      medications: "He uses his fluticasone inhaler twice a day, and albuterol when he needs it. Last time he needed the albuterol was two days ago. He also chews a montelukast every evening, and takes cetirizine when his allergies act up.",
      allergies: "He's very allergic to peanuts. He had anaphylaxis once when he was five, so he carries an EpiPen. He's also allergic to dust mites. No medication allergies that we know of.",
    },
    exam: {
      general_appearance: { reaction: "", finding: "Quiet, lying still curled on his side, reluctant to move. Not toxic appearing." },
      vitals: { reaction: "", finding: "Temperature 38.0 C, heart rate 112, blood pressure 104/66, respiratory rate 20, oxygen saturation 98% on room air. Weight 30 kg." },
      abdomen_inspection: { reaction: "", finding: "Flat, not distended. He guards with his hand over the right lower quadrant." },
      abdomen_palpation: { reaction: "He's pulling away, he says that's where it hurts.", finding: "Right lower quadrant tenderness with guarding. Rest of the abdomen soft." },
      mcburney_point: { reaction: "He yelped, that's the spot.", finding: "Maximal tenderness at McBurney's point." },
      rebound: { reaction: "He's crying, he says letting go hurt more.", finding: "Rebound tenderness in the right lower quadrant." },
      guarding_rigidity: { reaction: "He's tensing his tummy.", finding: "Voluntary guarding in the right lower quadrant, no generalized rigidity." },
      rovsing: { reaction: "He says pushing on the left made the right side hurt.", finding: "Positive Rovsing sign." },
      psoas: { reaction: "He doesn't like lifting his right leg.", finding: "Positive right psoas sign." },
      obturator: { reaction: "He says that's okay.", finding: "Negative obturator sign." },
      murphy: { reaction: "He says that's fine up there.", finding: "No right upper quadrant tenderness." },
      cva_tenderness: { reaction: "", finding: "No costovertebral angle tenderness." },
      chest_lungs: { reaction: "", finding: "Clear breath sounds bilaterally, no wheeze. Normal work of breathing." },
      genitourinary: { reaction: "He's embarrassed but says it doesn't hurt there.", finding: "Normal testicular exam, no swelling or tenderness, normal cremasteric reflex." },
    },
    tests: {
      cbc: { result: "White count 14.2 with 85% neutrophils. Hemoglobin 13.1. Platelets 310.", abnormal: true },
      crp: { result: "CRP 32 mg/L (elevated).", abnormal: true },
      bmp: { result: "Sodium 137, potassium 4.0, creatinine 0.5, glucose 102.", abnormal: false },
      lipase: { result: "Lipase normal.", abnormal: false },
      urinalysis: { result: "Normal. No blood, no leukocytes, no nitrites.", abnormal: false },
      ultrasound: { result: "Noncompressible 9 mm appendix with periappendiceal fluid and hyperemia. No abscess.", abnormal: true },
      ct_abdomen_pelvis: { result: "Dilated 9 mm appendix with fat stranding, no abscess.", abnormal: true },
      type_and_screen: { result: "Type A positive, antibody screen negative.", abnormal: false },
    },
    testNotes: {
      ct_abdomen_pelvis: "In children, ultrasound comes first to avoid radiation. CT is for an equivocal ultrasound.",
    },
    diagnosis: { label: "Acute appendicitis", keywords: [["appendicitis", "appendix"]] },
    procedureKeywords: [["appendectomy", "appendicectomy", "remove the appendix", "take out the appendix", "take the appendix out"]],
    urgency: "urgent",
    differential: [
      ddx("adenitis", "Mesenteric adenitis", "adenitis", "lymph"),
      ddx("gastro", "Gastroenteritis", "gastroenteritis", "stomach bug", "viral"),
      ddx("constipation", "Constipation", "constipation"),
      ddx("intussusception", "Intussusception", "intussusception"),
      ddx("testicular", "Testicular torsion", "testicular", "torsion"),
      ddx("uti", "Urinary tract infection", "uti", "urinary"),
      ddx("pneumonia", "Right lower lobe pneumonia", "pneumonia"),
      ddx("meckel", "Meckel's diverticulitis", "meckel"),
    ],
    critical: [
      { kind: "history", id: "allergies", why: "Peanut anaphylaxis with an EpiPen: the team needs to know before induction, even though it is not a drug allergy." },
      { kind: "history", id: "past_medical", why: "Asthma changes anesthesia: ask about control, recent rescue inhaler use, and past intubations." },
      { kind: "history", id: "last_meal", why: "Last oral intake sets anesthesia timing and aspiration risk." },
      { kind: "exam", id: "genitourinary", why: "Every boy with lower abdominal pain needs a testicular exam: torsion is the can't-miss mimic." },
    ],
    expected: [
      ...COMMON_APPY_EXPECTED,
      { kind: "history", id: "medications", why: "His controller and rescue inhaler use tell you how stable his asthma is." },
      { kind: "exam", id: "chest_lungs", why: "Check for wheeze before anesthesia, and right lower lobe pneumonia can mimic appendicitis." },
      { kind: "test", id: "ultrasound", why: "Ultrasound is the first imaging test in children." },
    ],
  },
  {
    planSubject: "patient-demo-sparse",
    persona: {
      speaker: "patient",
      name: "Jonah Okoye",
      patientName: "Jonah Okoye",
      age: 30,
      sex: "male",
      voiceKey: "adult_male",
      demeanor: "A construction worker, normally stoic, now clearly sick: short sentences, sweaty, shivering, in a lot of pain. Wants it fixed.",
      character:
        "You're a framing carpenter, proud of never calling in sick. Your girlfriend Dani made you come in and drove you; your dog Tank is at home. You play pickup basketball on Sundays and watch Arsenal with your dad. Normally you're stoic and joking, but right now you talk in short, broken sentences, a few words at a time, and you can't laugh. You call the clinician 'Doc' or 'man', say 'Man...' on the exhale, and 'I'm good, I'm good' when you're not. A long question gets 'Sorry, what? Say that again.' You hate admitting you're scared and cover it with 'just fix it.' You're embarrassed you waited this long. If they explain surgery you feel relief, 'Do it, whatever you gotta do,' then ask someone to text Dani and your boss. You thought it was food poisoning; now you just know something's really wrong.",
      opener: "Doc, I'm in bad shape. My whole stomach is on fire.",
    },
    history: {
      chief_complaint: "My whole stomach hurts. It's bad.",
      onset: "Started two days ago, Wednesday morning.",
      location: "It was on the right side low. Now it's everywhere.",
      migration: "First it was around my belly button, then it moved down to the right. Yesterday afternoon it actually got better for an hour or so, then it came back worse and spread everywhere.",
      character: "Constant. Like my whole gut is burning.",
      severity: "Nine. I don't go to doctors, so you know it's bad.",
      aggravating_relieving: "Any movement. Even breathing deep hurts. Nothing makes it better.",
      nausea_vomiting: "Threw up maybe four or five times since yesterday.",
      appetite: "Haven't eaten anything since yesterday morning.",
      fever: "Chills and sweats all night. I'm shaking.",
      bowel: "Haven't gone since Wednesday. No diarrhea.",
      urinary: "Peeing less than normal. No burning.",
      last_meal: "A breakfast sandwich yesterday morning, around seven. A little water about two hours ago.",
      past_medical: "Nothing. I'm never sick.",
      past_surgical: "Never had surgery.",
      medications: "I don't take anything. Some ibuprofen yesterday, didn't help.",
      allergies: "Penicillin. I broke out in hives when I was a kid.",
      social: "I work construction. I smoke about half a pack a day, and I drink on weekends.",
      family: "My dad has high blood pressure. That's all I know.",
      recent_illness: "No, I was fine before this.",
    },
    exam: {
      general_appearance: { reaction: "", finding: "Ill appearing, diaphoretic, lying completely still, shivering." },
      vitals: { reaction: "", finding: "Temperature 38.9 C, heart rate 118, blood pressure 102/64, respiratory rate 22, oxygen saturation 97% on room air." },
      abdomen_inspection: { reaction: "", finding: "Mildly distended, not moving with respiration." },
      abdomen_palpation: { reaction: "Agh! Everywhere hurts!", finding: "Diffuse tenderness, worst in the right lower quadrant." },
      mcburney_point: { reaction: "That's the worst spot!", finding: "Maximal tenderness in the right lower quadrant." },
      rebound: { reaction: "Don't do that again!", finding: "Diffuse rebound tenderness." },
      guarding_rigidity: { reaction: "I can't relax it, man.", finding: "Involuntary guarding and board-like rigidity. Generalized peritonitis." },
      rovsing: { reaction: "Everything hurts when you do that.", finding: "Positive Rovsing sign." },
      psoas: { reaction: "No, I can't lift my leg.", finding: "Positive right psoas sign." },
      obturator: { reaction: "Ah, that hurts too.", finding: "Positive obturator sign." },
      murphy: { reaction: "It's all bad.", finding: "Diffuse tenderness, not localized to the right upper quadrant." },
      cva_tenderness: { reaction: "My back's okay.", finding: "No costovertebral angle tenderness." },
      chest_lungs: { reaction: "", finding: "Clear, shallow breaths because of pain." },
      genitourinary: { reaction: "No, that's fine.", finding: "Normal testicular exam." },
    },
    tests: {
      cbc: { result: "White count 18.6 with 12% bands. Hemoglobin 15.1. Platelets 410.", abnormal: true },
      crp: { result: "CRP 180 mg/L (markedly elevated).", abnormal: true },
      bmp: { result: "Sodium 134, potassium 3.6, creatinine 1.3 (mildly elevated, likely dehydration), glucose 128.", abnormal: true },
      lactate: { result: "Lactate 2.8 (elevated).", abnormal: true },
      lipase: { result: "Lipase normal.", abnormal: false },
      urinalysis: { result: "Concentrated, specific gravity 1.030. No blood, no infection.", abnormal: true },
      ultrasound: { result: "Limited by bowel gas and guarding. Free fluid in the right lower quadrant.", abnormal: true },
      ct_abdomen_pelvis: { result: "Perforated appendicitis with periappendiceal phlegmon and free fluid. No drainable abscess. No free air under the diaphragm.", abnormal: true },
      type_and_screen: { result: "Type B positive, antibody screen negative.", abnormal: false },
    },
    diagnosis: {
      label: "Perforated appendicitis with peritonitis and sepsis",
      keywords: [["appendicitis", "appendix"], ["perforat", "ruptur", "burst"]],
      partial: { label: "Appendicitis (perforation not named)", keywords: [["appendicitis", "appendix"]] },
    },
    procedureKeywords: [["appendectomy", "appendicectomy", "remove the appendix", "take out the appendix", "take the appendix out", "washout"]],
    urgency: "emergency",
    differential: [
      ddx("ulcer", "Perforated peptic ulcer", "ulcer", "peptic"),
      ddx("diverticulitis", "Diverticulitis", "diverticul"),
      ddx("crohns", "Crohn's disease with perforation or abscess", "crohn", "ileitis", "ibd"),
      ddx("obstruction", "Small bowel obstruction", "obstruction"),
      ddx("stone", "Ureteric stone with infection", "stone", "kidney", "ureter"),
      ddx("ischemia", "Mesenteric ischemia", "ischemi"),
    ],
    critical: [
      { kind: "history", id: "allergies", why: "His chart is empty, but he is allergic to penicillin: that changes the antibiotic for an infected abdomen. Only asking him found it." },
      { kind: "history", id: "medications", why: "With no chart, medications have to come from the patient." },
      { kind: "exam", id: "vitals", why: "Fever, tachycardia, and soft blood pressure mean sepsis: fluids and antibiotics before the operating room." },
      { kind: "history", id: "last_meal", why: "Last oral intake sets anesthesia timing and aspiration risk." },
    ],
    expected: [
      ...COMMON_APPY_EXPECTED,
      { kind: "exam", id: "guarding_rigidity", why: "Rigidity means generalized peritonitis." },
      { kind: "test", id: "lactate", why: "Lactate grades sepsis severity." },
      { kind: "test", id: "ct_abdomen_pelvis", why: "CT defines perforation, phlegmon, or a drainable abscess." },
      { kind: "test", id: "bmp", why: "Vomiting and sepsis threaten the kidneys and electrolytes." },
    ],
  },
  {
    planSubject: "patient-demo-polypharmacy",
    persona: {
      speaker: "patient",
      name: "Harriet Lindqvist",
      patientName: "Harriet Lindqvist",
      age: 78,
      sex: "female",
      voiceKey: "senior_female",
      demeanor: "A retired librarian, polite and precise, tired and a little breathless. Keeps a folded medication list in her purse. Tends to downplay her pain and apologizes for being a bother.",
      character:
        "You're a retired reference librarian who worked 38 years at the county library. Your daughter Karin drove you in and is filling out forms at the desk, and your old orange cat Dewey needs feeding tonight. You do the newspaper crossword in pen and paint watercolor postcards for your grandchildren. You're polite, precise, and a little formal, with proper grammar. You call everyone 'dear', say 'Oh, dear' and 'Well, now', and apologize for being a bother. You downplay things at first ('It's not so bad, really'); the real story comes out only when asked specifically. You gently correct small mistakes. You worry about being a burden on Karin. If surgery comes up you're quietly worried about going through it at your age, and if asked what scares you, you say 'Is it my heart?' At the end you want Karin brought in for the plan, and someone to feed Dewey.",
      opener: "Hello, dear. I'm sorry to be a bother. This pain under my ribs just won't let up.",
    },
    history: {
      chief_complaint: "Pain up here under my right ribs. It just won't go away.",
      onset: "It started two days ago, after supper. I thought it was my reflux, but it never settled down.",
      location: "Right here, under the ribs on the right side.",
      migration: "It stays in the same place, but it goes through to my back, under my right shoulder blade.",
      character: "A constant, heavy ache. Last year I had a few short spells like this that went away on their own in an hour or two. This one hasn't.",
      severity: "Seven, maybe eight when I take a deep breath.",
      aggravating_relieving: "Breathing in deep hurts, and so did the car ride. Eating made it worse. Tylenol takes the edge off for an hour or so.",
      nausea_vomiting: "I've been sick to my stomach the whole time. I threw up twice yesterday.",
      appetite: "I haven't eaten much of anything since it started.",
      fever: "I've had chills. Last night I was shaking under two blankets.",
      bowel: "My bowels are about normal. No black or bloody stools.",
      urinary: "I'm passing less water than usual because I haven't been drinking much. It doesn't burn.",
      menstrual_pregnancy: "Oh, I went through the change nearly thirty years ago.",
      last_meal: "A few spoonfuls of broth last night around six. Sips of water this morning, and I took my morning pills with a little water at seven.",
      past_medical: "My heart has the atrial fibrillation, and I have heart failure, so they watch my water pill closely. My kidneys are weak, stage three they told me. Diabetes, blood pressure, thyroid, cholesterol, reflux, and bad knees. I've never had a heart attack.",
      past_surgical: "My appendix came out when I was a girl, and I had both cataracts done. They keep talking about replacing my knees.",
      medications: "It's a long list, it's in my purse. The important one is my blood thinner, apixaban, twice a day. I took last night's at seven and this morning's at seven. I also take a baby aspirin, metoprolol, furosemide, lisinopril, metformin, my thyroid pill, omeprazole, atorvastatin, sertraline, trazodone for sleep, a potassium pill, vitamin D, and Tylenol for my knees.",
      allergies: "Sulfa drugs give me hives all over, that was a bad one. And the dye they use for scans made me throw up once.",
      social: "I'm a widow and I live alone in an apartment. My daughter lives nearby. I walk with a cane. I never smoked, just a small sherry at Christmas.",
      family: "My mother had gallstones.",
      recent_illness: "No, I was fine before this started.",
    },
    exam: {
      general_appearance: { reaction: "", finding: "Elderly woman, uncomfortable, lying still. Dry mucous membranes. No scleral icterus. Alert and oriented." },
      vitals: { reaction: "", finding: "Temperature 38.3 C, heart rate 104 and irregularly irregular, blood pressure 128/70, respiratory rate 20, oxygen saturation 95% on room air. Weight 70 kg." },
      abdomen_inspection: { reaction: "", finding: "Not distended. Old healed right lower quadrant incision. No jaundice." },
      abdomen_palpation: { reaction: "Oh! Yes, that's it, right there under the ribs.", finding: "Right upper quadrant tenderness with voluntary guarding and a tender fullness below the right costal margin. Rest of the abdomen soft." },
      murphy: { reaction: "Ah! I can't breathe in when you press there.", finding: "Positive Murphy sign: inspiration stops on deep right subcostal palpation." },
      rebound: { reaction: "That hurt when you let go, but only up there.", finding: "Mild rebound tenderness confined to the right upper quadrant. No generalized peritonitis." },
      guarding_rigidity: { reaction: "I'm trying to relax, dear.", finding: "Voluntary guarding in the right upper quadrant, no rigidity." },
      mcburney_point: { reaction: "No, that's alright down there.", finding: "Nontender in the right lower quadrant." },
      cva_tenderness: { reaction: "My back's just stiff, that doesn't hurt.", finding: "No costovertebral angle tenderness." },
      chest_lungs: { reaction: "", finding: "Irregularly irregular rhythm, no new murmur. Faint crackles at both lung bases, trace ankle edema. No focal consolidation." },
    },
    tests: {
      cbc: { result: "White count 14.8 with 84% neutrophils. Hemoglobin 11.0 (her baseline is about 11.4). Platelets 205.", abnormal: true },
      crp: { result: "CRP 96 mg/L (elevated).", abnormal: true },
      bmp: { result: "Sodium 134, potassium 5.1, bicarbonate 21, BUN 38, creatinine 1.9 (baseline 1.7), eGFR 27, glucose 186. Acute kidney injury on chronic kidney disease.", abnormal: true },
      lfts: { result: "Total bilirubin 1.0, alkaline phosphatase 110, AST 34, ALT 31. Normal: no pattern of a common bile duct stone or cholangitis.", abnormal: false },
      lipase: { result: "Lipase 38 (normal).", abnormal: false },
      lactate: { result: "Lactate 1.6 (normal).", abnormal: false },
      urinalysis: { result: "Concentrated, specific gravity 1.025. No leukocytes, no nitrites, no bilirubin.", abnormal: true },
      ultrasound: { result: "Multiple gallstones with one impacted in the gallbladder neck. Gallbladder wall 6 mm with pericholecystic fluid and a positive sonographic Murphy sign. Common bile duct 5 mm, no duct stones seen.", abnormal: true },
      ct_abdomen_pelvis: { result: "Noncontrast CT: distended gallbladder with wall thickening and pericholecystic stranding. Gallstones not well seen. No free air, no abscess.", abnormal: true },
      type_and_screen: { result: "Type A negative, antibody screen negative.", abnormal: false },
    },
    testNotes: {
      ct_abdomen_pelvis: "Ultrasound is the first test for suspected cholecystitis. CT misses many gallstones, and her contrast allergy and eGFR near 30 argue against giving contrast.",
    },
    diagnosis: {
      label: "Acute calculous cholecystitis, moderate (Tokyo grade II)",
      keywords: [["cholecystitis"]],
      partial: { label: "Gallstone disease (acute cholecystitis not named)", keywords: [["gallstone", "cholelithiasis", "biliary", "gallbladder"]] },
    },
    procedureKeywords: [CHOLE_PROCEDURE_KEYWORDS],
    urgency: "urgent",
    differential: [
      ddx("cholangitis", "Choledocholithiasis or acute cholangitis", "cholangitis", "choledocho", "duct stone", "bile duct"),
      ddx("pancreatitis", "Acute pancreatitis", "pancreatitis"),
      ddx("ulcer", "Peptic ulcer disease or perforated ulcer", "ulcer", "peptic"),
      ddx("pneumonia", "Right lower lobe pneumonia", "pneumonia"),
      ddx("mi", "Inferior myocardial infarction", "myocardial", "heart attack", "infarct", "coronary"),
      ddx("mesenteric", "Mesenteric ischemia (she is in atrial fibrillation)", "mesenteric"),
      ddx("pyelo", "Right pyelonephritis", "pyelo", "kidney infection"),
    ],
    critical: [
      { kind: "history", id: "medications", why: "She took apixaban this morning and also takes aspirin. Apixaban clears partly through the kidneys, so with an eGFR near 30 it lingers: a planned operation usually waits about 48 hours after the last dose, with no heparin bridge, and that delay has to be weighed against early cholecystectomy." },
      { kind: "history", id: "allergies", why: "Contrast allergy with an eGFR near 30: avoid contrast CT and plan any intraoperative cholangiogram around the allergy. Her sulfa allergy causes hives, so sulfonamide antibiotics are out." },
      { kind: "test", id: "bmp", why: "Creatinine is up from her baseline: acute kidney injury on stage 3 CKD. Dose antibiotics and analgesics for her kidneys, avoid NSAIDs, hold metformin and lisinopril, and watch potassium because she takes a potassium supplement." },
      { kind: "history", id: "last_meal", why: "Last oral intake sets anesthesia timing and aspiration risk." },
    ],
    expected: [
      { kind: "history", id: "onset", why: "Tokyo guidelines favor cholecystectomy within about 72 hours of symptom onset when the patient can tolerate it." },
      { kind: "history", id: "character", why: "Constant pain lasting days, after past self-limited spells, separates cholecystitis from biliary colic." },
      { kind: "history", id: "fever", why: "Fever and chills point to inflammation or infection, and with jaundice would suggest cholangitis." },
      { kind: "history", id: "nausea_vomiting", why: "Vomiting and poor intake explain her dehydration and kidney injury." },
      { kind: "history", id: "past_medical", why: "Atrial fibrillation, heart failure, and CKD raise her operative risk. Tokyo grading weighs comorbidity when choosing early surgery versus antibiotics and gallbladder drainage." },
      { kind: "history", id: "social", why: "She lives alone and uses a cane: frailty and discharge planning start before surgery." },
      { kind: "exam", id: "vitals", why: "Fever and tachycardia grade severity, and atrial fibrillation makes the heart rate harder to interpret." },
      { kind: "exam", id: "abdomen_palpation", why: "Right upper quadrant tenderness with a tender palpable gallbladder is a Tokyo grade II feature." },
      { kind: "exam", id: "murphy", why: "A positive Murphy sign is the classic bedside sign of acute cholecystitis." },
      { kind: "exam", id: "chest_lungs", why: "Check her heart failure volume status before fluids and anesthesia, and exclude a right lower lobe pneumonia." },
      { kind: "test", id: "cbc", why: "Leukocytosis supports cholecystitis, and her hemoglobin is already low." },
      { kind: "test", id: "ultrasound", why: "Ultrasound is the first imaging test: stones, wall thickening, pericholecystic fluid, and duct size." },
      { kind: "test", id: "lfts", why: "Normal bilirubin and liver enzymes make a common bile duct stone or cholangitis unlikely." },
      { kind: "test", id: "lipase", why: "Excludes gallstone pancreatitis." },
      { kind: "test", id: "type_and_screen", why: "Anemic and anticoagulated: have blood available." },
    ],
  },
  {
    planSubject: "patient-demo-001",
    persona: {
      speaker: "patient",
      name: "Morgan Rivera",
      patientName: "Morgan Rivera",
      age: 38,
      sex: "female",
      voiceKey: "mature_female",
      demeanor: "A seventh grade science teacher seen in surgery clinic, friendly and organized. Pain-free today. Asks practical questions about time off work and recovery.",
      character:
        "You teach seventh grade science, eleven years now, and run the after-school garden club; your classroom has a corn snake named Biscuit. You're married to Daniel, and you have a goofy dog named Pepper you walk every morning. You bake bread on Sundays and love true crime podcasts. You're friendly, upbeat, and organized, and you talk like a teacher: 'Okay, so...', 'Here's the thing', 'honestly', with a small laugh when you're nervous. If a clinician uses a medical word, you ask what it means. You took a personal day and have a sub covering your class, so you start out a bit businesslike, then open up. Near the end you want practical answers: when, how long off work, what you can eat. If surgery is recommended you feel relieved: 'Honestly, good. I just want my evenings back.'",
      opener: "Hi! My doctor sent me over about my gallbladder. I feel fine right now, but these attacks are wrecking my evenings.",
    },
    history: {
      chief_complaint: "I keep getting attacks of pain under my right ribs after I eat.",
      onset: "The first one was about three months ago. I've had four now. The last one was eight days ago.",
      location: "Up under my right ribs, and sometimes in the middle, right under my breastbone.",
      migration: "Sometimes it goes through to my back, near my right shoulder blade.",
      character: "It builds over about twenty minutes, then it's a hard, steady squeezing. It doesn't come in waves, it just sits there.",
      severity: "During an attack, an eight. Right now, zero.",
      aggravating_relieving: "It's always after a big or greasy dinner, like pizza or fried chicken. It eases off on its own after two or three hours. Moving around doesn't change it.",
      nausea_vomiting: "I get nauseous during the attacks. I threw up once, with the worst one.",
      appetite: "Normal between attacks. I've been avoiding fatty food.",
      fever: "No fevers or chills, not even during the attacks.",
      bowel: "Normal. No pale or greasy stools, no blood.",
      urinary: "No problems. My urine has never looked dark.",
      menstrual_pregnancy: "My last period started about three weeks ago, it was normal. We're not trying, but I'm not on birth control. We use condoms.",
      last_meal: "A salad at noon, before I came in.",
      past_medical: "Type 2 diabetes, about five years now, and high blood pressure. My sugars have been better lately. No heart or lung problems.",
      past_surgical: "Just a C-section with my son, eight years ago. The anesthesia went fine.",
      medications: "Metformin, 500 twice a day with meals, and lisinopril 10 in the morning. Sometimes Tums. Nothing else.",
      allergies: "Penicillin. I got an itchy rash on my arms as a kid when I took it for strep. No swelling, no trouble breathing. I've had cephalexin since then with no problem.",
      social: "I teach seventh grade science. I don't smoke. Maybe a glass of wine a week. I'm married with one son.",
      family: "My mom had her gallbladder out in her forties.",
      recent_illness: "No, I've been healthy otherwise.",
    },
    exam: {
      general_appearance: { reaction: "", finding: "Well appearing and comfortable. No jaundice or scleral icterus." },
      vitals: { reaction: "", finding: "Temperature 36.8 C, heart rate 74, blood pressure 126/80, respiratory rate 14, oxygen saturation 98% on room air. Weight 74 kg, BMI 27." },
      abdomen_inspection: { reaction: "", finding: "Flat abdomen with a healed low transverse cesarean scar. No distension." },
      abdomen_palpation: { reaction: "That's fine. Maybe a little sore up on the right, but nothing like an attack.", finding: "Soft. Minimal right upper quadrant tenderness to deep palpation, no guarding, no mass." },
      murphy: { reaction: "A little tender, but I can breathe in fine.", finding: "Negative Murphy sign between attacks." },
      rebound: { reaction: "No, that's fine.", finding: "No rebound tenderness." },
      mcburney_point: { reaction: "Nope, nothing there.", finding: "Nontender in the right lower quadrant." },
      cva_tenderness: { reaction: "No.", finding: "No costovertebral angle tenderness." },
      chest_lungs: { reaction: "", finding: "Lungs clear, regular heart rhythm." },
    },
    tests: {
      cbc: { result: "White count 7.2, hemoglobin 13.5, platelets 260. Normal.", abnormal: false },
      crp: { result: "CRP 3 mg/L (normal).", abnormal: false },
      bmp: { result: "Sodium 139, potassium 4.2, creatinine 0.86, glucose 118. Normal kidney function.", abnormal: false },
      lfts: { result: "Total bilirubin 0.6, alkaline phosphatase 82, AST 22, ALT 25. Normal.", abnormal: false },
      lipase: { result: "Lipase 28 (normal).", abnormal: false },
      urinalysis: { result: "Normal. No blood, no leukocytes, no bilirubin.", abnormal: false },
      pregnancy_test: { result: "Urine hCG negative.", abnormal: false },
      ultrasound: { result: "Multiple mobile gallstones up to 12 mm. Gallbladder wall 2 mm, no pericholecystic fluid, sonographic Murphy sign negative. Common bile duct 4 mm. Normal liver.", abnormal: true },
      ct_abdomen_pelvis: { result: "No acute abnormality. Gallstones not well seen on CT.", abnormal: false },
      type_and_screen: { result: "Type O positive, antibody screen negative.", abnormal: false },
    },
    testNotes: {
      ct_abdomen_pelvis: "Ultrasound is the test for gallstones. CT adds radiation and misses many stones.",
    },
    diagnosis: {
      label: "Symptomatic cholelithiasis (biliary colic)",
      keywords: [["biliary colic", "symptomatic cholelithiasis", "symptomatic gallstone"]],
      partial: { label: "Gallstones (symptomatic biliary colic not named)", keywords: [["gallstone", "cholelithiasis"]] },
    },
    procedureKeywords: [CHOLE_PROCEDURE_KEYWORDS],
    urgency: "elective",
    differential: [
      ddx("cholecystitis", "Acute cholecystitis", "cholecystitis"),
      ddx("cbd", "Choledocholithiasis", "choledocho", "duct stone", "bile duct"),
      ddx("ulcer", "Peptic ulcer disease or gastritis", "ulcer", "peptic", "gastritis"),
      ddx("gerd", "Gastroesophageal reflux", "reflux", "gerd"),
      ddx("pancreatitis", "Pancreatitis", "pancreatitis"),
      ddx("dyspepsia", "Functional dyspepsia or irritable bowel", "dyspepsia", "ibs", "irritable"),
      ddx("liver", "Fatty liver disease or hepatitis", "fatty liver", "hepatitis", "nafld", "masld"),
      ddx("cardiac", "Cardiac ischemia (a diabetic can present atypically)", "angina", "cardiac", "coronary"),
    ],
    critical: [
      { kind: "history", id: "allergies", why: "Her chart says penicillin, but the reaction matters: a mild childhood rash, and she has since taken cephalexin safely. Cefazolin prophylaxis is appropriate. An unexamined penicillin label pushes teams to broader, less effective antibiotics." },
      { kind: "history", id: "medications", why: "Metformin and lisinopril: hold both the morning of surgery, check glucose before incision, and restart metformin once she is eating and her kidney function is confirmed." },
      { kind: "test", id: "pregnancy_test", why: "A 38-year-old not on reliable contraception needs a pregnancy test before elective surgery and anesthesia." },
    ],
    expected: [
      { kind: "history", id: "onset", why: "The number and frequency of attacks justify elective removal." },
      { kind: "history", id: "character", why: "Steady pain that builds and settles within a few hours is biliary colic." },
      { kind: "history", id: "aggravating_relieving", why: "A fatty meal trigger and spontaneous relief within about six hours separate colic from cholecystitis." },
      { kind: "history", id: "fever", why: "Fever would mean cholecystitis or cholangitis, not simple colic." },
      { kind: "history", id: "urinary", why: "Dark urine and pale stools signal a stone blocking the bile duct." },
      { kind: "history", id: "menstrual_pregnancy", why: "Pregnancy changes the timing and approach of an elective operation." },
      { kind: "history", id: "past_medical", why: "Diabetes and hypertension shape the anesthetic and glucose plan." },
      { kind: "history", id: "past_surgical", why: "Prior abdominal surgery affects port placement, and prior anesthesia problems matter." },
      { kind: "exam", id: "vitals", why: "Normal temperature and heart rate fit colic, not acute inflammation." },
      { kind: "exam", id: "abdomen_palpation", why: "A soft abdomen between attacks supports uncomplicated gallstones." },
      { kind: "exam", id: "murphy", why: "A positive Murphy sign would point to acute cholecystitis instead." },
      { kind: "test", id: "ultrasound", why: "Confirms stones and shows no wall thickening or duct dilation." },
      { kind: "test", id: "lfts", why: "Normal liver tests make a common bile duct stone unlikely, so no MRCP or ERCP is needed first." },
      { kind: "test", id: "bmp", why: "Kidney function and glucose before continuing metformin and lisinopril around surgery." },
      { kind: "test", id: "cbc", why: "A normal white count supports colic over cholecystitis." },
    ],
  },
  {
    planSubject: "patient-demo-source-unavailable",
    persona: {
      speaker: "patient",
      name: "Ingrid Solano",
      patientName: "Ingrid Solano",
      age: 68,
      sex: "female",
      voiceKey: "older_female",
      demeanor: "A retired bookkeeper seen in surgery clinic, organized and matter-of-fact. Feels well now and wants to avoid another hospital stay. Remembers details of her admission clearly.",
      character:
        "You're a retired bookkeeper who still keeps your church's books in pencil, in a green ledger. You love crosswords in pen, quilting, and your tomato plants, and you're still annoyed the hospital stay made you miss them at their best. You kept a notebook during that stay but left it on the kitchen table today, and you're annoyed with yourself about it. You're matter-of-fact, precise, and a little dry. You start answers with 'Well,', say 'Let me be exact', and when you don't know something you say so plainly: 'They didn't tell me.' You're businesslike and want to get this on the calendar. Your main goal is never to go through that pain again; if told it could come back, you get more motivated, not more anxious. You're a bit irritated the hospital didn't take care of it while you were there, and may ask about that once, calmly.",
      opener: "Hello, I'm Ingrid. The hospital told me to come see you about taking my gallbladder out after that pancreatitis business.",
    },
    history: {
      chief_complaint: "I'm here to get my gallbladder out. Last month the gallstones gave me pancreatitis.",
      onset: "I was in the hospital about four weeks ago, for three days. I've felt fine for the last three weeks.",
      location: "Back then it was in the upper middle of my belly, boring straight through to my back. Nothing now.",
      migration: "It stayed in the middle and went straight through to my back.",
      character: "Back then a terrible, steady pain. Now nothing at all.",
      severity: "In the hospital it was a ten. Today it's zero.",
      aggravating_relieving: "Back then eating made it worse and leaning forward helped a little. Now I eat normally, I just stay away from fried food.",
      nausea_vomiting: "I threw up a lot in the hospital. None since I got home.",
      appetite: "Good. I've been eating fine.",
      fever: "No fevers since I got home.",
      bowel: "Normal. No pale stools.",
      urinary: "Normal. My urine hasn't been dark.",
      menstrual_pregnancy: "I'm long past menopause.",
      last_meal: "Toast and coffee at eight this morning.",
      past_medical: "High blood pressure and high cholesterol. And the pancreatitis last month, at Quillhaven. They said it was mild, I never went to the ICU. Before I went home they did an MRI of my bile ducts and said no stones were stuck. They asked a lot about drinking, but I hardly drink.",
      past_surgical: "I've never had surgery. I had a colonoscopy at sixty and it was fine.",
      medications: "Lisinopril in the morning and atorvastatin at night. The hospital didn't start anything new. I also take a baby aspirin most days on my own, nobody prescribed it.",
      social: "I'm a retired bookkeeper and I live with my husband. I never smoked. Maybe a glass of wine at a wedding.",
      family: "My sister had gallstones.",
      recent_illness: "Just the pancreatitis.",
    },
    exam: {
      general_appearance: { reaction: "", finding: "Well appearing. No jaundice, no scleral icterus." },
      vitals: { reaction: "", finding: "Temperature 36.7 C, heart rate 72, blood pressure 132/80, respiratory rate 14, oxygen saturation 98% on room air. Weight 81 kg." },
      abdomen_inspection: { reaction: "", finding: "Soft, mildly obese abdomen. No scars, no flank or periumbilical bruising." },
      abdomen_palpation: { reaction: "No, that's all fine now.", finding: "Soft and nontender. No mass." },
      murphy: { reaction: "No, that doesn't hurt.", finding: "Negative Murphy sign." },
      rebound: { reaction: "That's fine.", finding: "No rebound tenderness." },
      mcburney_point: { reaction: "No.", finding: "Nontender in the right lower quadrant." },
      cva_tenderness: { reaction: "No.", finding: "No costovertebral angle tenderness." },
      chest_lungs: { reaction: "", finding: "Lungs clear, regular heart rhythm." },
    },
    tests: {
      cbc: { result: "White count 6.9, hemoglobin 13.4, platelets 245. Normal.", abnormal: false },
      crp: { result: "CRP 4 mg/L (normal).", abnormal: false },
      bmp: { result: "Sodium 140, potassium 4.4, creatinine 0.9, glucose 102, calcium 9.4. Normal.", abnormal: false },
      lfts: { result: "Total bilirubin 0.7, alkaline phosphatase 88, AST 24, ALT 21. Normal: no sign of a retained bile duct stone.", abnormal: false },
      lipase: { result: "Lipase 42 (normal).", abnormal: false },
      urinalysis: { result: "Normal.", abnormal: false },
      ultrasound: { result: "Multiple small gallstones and sludge. Gallbladder wall 3 mm, no pericholecystic fluid. Common bile duct 5 mm. Pancreas partly obscured by bowel gas, no peripancreatic fluid seen.", abnormal: true },
      ct_abdomen_pelvis: { result: "No peripancreatic collection or necrosis. Gallstones not well seen.", abnormal: false },
      type_and_screen: { result: "Type B positive, antibody screen negative.", abnormal: false },
    },
    testNotes: {
      ct_abdomen_pelvis: "After mild pancreatitis that has resolved, CT adds radiation without changing the plan. Ultrasound shows the stones.",
    },
    diagnosis: {
      label: "Resolved mild gallstone pancreatitis, due for interval cholecystectomy",
      keywords: [["pancreatitis"], ["gallstone", "biliary", "cholelithiasis", "gallbladder"]],
      partial: { label: "Gallstone disease (the prior gallstone pancreatitis not named)", keywords: [["gallstone", "cholelithiasis", "biliary"]] },
    },
    procedureKeywords: [CHOLE_PROCEDURE_KEYWORDS],
    urgency: "elective",
    differential: [
      ddx("alcohol", "Alcohol-related pancreatitis", "alcohol"),
      ddx("triglycerides", "Hypertriglyceridemia", "triglycerid"),
      ddx("calcium", "Hypercalcemia", "hypercalc", "calcium"),
      ddx("drug", "Drug-induced pancreatitis", "drug", "medication"),
      ddx("tumor", "Pancreatic tumor or cystic neoplasm", "tumor", "cancer", "ipmn", "neoplasm", "mass"),
      ddx("cbd", "Retained common bile duct stone", "duct stone", "choledocho", "retained", "bile duct"),
    ],
    critical: [
      { kind: "history", id: "past_medical", why: "Her pancreatitis admission lives in the record source that failed to sync. Only she can tell you it was mild, that an MRCP cleared the bile duct, and that alcohol was not the cause." },
      { kind: "test", id: "lfts", why: "After gallstone pancreatitis, normal liver tests (with her clear MRCP) make a retained bile duct stone unlikely. Abnormal ones would mean clearing the duct before removing the gallbladder." },
      { kind: "history", id: "medications", why: "She takes aspirin on her own and it is in no chart. Low-dose aspirin is usually continued for a laparoscopic cholecystectomy, but the team has to know." },
      { kind: "history", id: "allergies", why: "A penicillin rash is on file. Confirm the reaction so prophylaxis is chosen around it: a remote mild rash still allows cefazolin." },
    ],
    expected: [
      { kind: "history", id: "onset", why: "After mild gallstone pancreatitis the gallbladder should come out soon, ideally during the same admission or within a few weeks, because recurrence is common." },
      { kind: "history", id: "social", why: "Alcohol is the other common cause of pancreatitis and changes the diagnosis." },
      { kind: "history", id: "fever", why: "Fever since discharge would raise concern for an infected collection or cholangitis." },
      { kind: "history", id: "urinary", why: "Dark urine would suggest a retained stone blocking the bile duct." },
      { kind: "history", id: "family", why: "A family history of gallstones supports the cause." },
      { kind: "exam", id: "general_appearance", why: "Jaundice would point to a retained duct stone." },
      { kind: "exam", id: "vitals", why: "Normal vitals confirm she has recovered and is fit for elective surgery." },
      { kind: "exam", id: "abdomen_palpation", why: "A tender epigastric mass would suggest a pseudocyst or collection." },
      { kind: "exam", id: "murphy", why: "Confirms there is no ongoing gallbladder inflammation." },
      { kind: "test", id: "lipase", why: "A normal lipase confirms the pancreatitis has resolved." },
      { kind: "test", id: "ultrasound", why: "Shows the stones and sludge and the size of the bile duct." },
      { kind: "test", id: "bmp", why: "Kidney function on lisinopril, and calcium to exclude hypercalcemia as a cause." },
      { kind: "test", id: "cbc", why: "A baseline blood count before surgery." },
    ],
  },
  {
    planSubject: "patient-demo-messy-coding",
    persona: {
      speaker: "patient",
      name: "Dolores Marchetti",
      patientName: "Dolores Marchetti",
      age: 63,
      sex: "female",
      voiceKey: "middle_female",
      demeanor: "A retired bakery owner seen in surgery clinic, warm and talkative, a bit vague about her pills until she checks the bottles in her purse. Fed up with antibiotic courses and ready to be done with this.",
      character:
        "Everyone calls you Dee. For thirty years you ran Marchetti's, a corner bakery famous for its cannoli and birthday cakes, and you still bake for church and every grandchild's birthday. Your daughter Gina is expecting your sixth grandchild in January and you plan to help with the baby. You play cards with 'the girls' on Wednesdays and watch cooking shows to yell at them. You're warm, chatty, and funny, call the clinician 'honey' or 'sweetheart' now and then, tell little stories, and sometimes need a nudge back on track ('Where was I?'). You're fed up and determined to be done with this, but anxious underneath: what you dread most is waking up with a bag, like your neighbor Sal. You blame your diet, years of tasting frosting and not enough vegetables. At the end you want a date: 'Can we do it before the baby comes in January?'",
      opener: "Hi there. My stomach doctor says it's time to take out the bad part of my colon. After three rounds of this, honestly, I'm ready.",
    },
    history: {
      chief_complaint: "These infections in the pouches of my colon keep coming back. Three times in a year and a half.",
      onset: "The first was a year and a half ago, then last fall, then a bad one in June. I've been okay since July.",
      location: "Always low on the left side of my belly.",
      migration: "No, it always stays low on the left.",
      character: "During an attack, a deep, constant ache. Now just a twinge on the left now and then.",
      severity: "The attacks were a seven or eight. Today maybe a one.",
      aggravating_relieving: "A big meal or getting constipated brings on the twinges. Going to the bathroom helps a bit.",
      nausea_vomiting: "Only during the attacks. Not now.",
      appetite: "Fine.",
      fever: "I had a fever every time, up to 39 in June. None since.",
      bowel: "I go every day or two, a little constipated sometimes. No blood, no black stools, and my stools haven't gotten thinner.",
      urinary: "No. I've never had air bubbles or anything strange in my urine, and no bladder infections.",
      menstrual_pregnancy: "I went through menopause at fifty-one. No bleeding since.",
      last_meal: "Oatmeal at seven this morning.",
      past_medical: "Diabetes, blood pressure, and cholesterol. And the diverticulitis: every time they did a CT scan that showed it. In June there was a small pocket of pus. They treated it with antibiotics, no drain.",
      past_surgical: "My tubes tied after my last baby. And a colonoscopy in August, after I got better. They said no cancer, just lots of pouches on the left side.",
      medications: "Metformin twice a day, amlodipine, and metoprolol. The blood pressure pill on my list is the water pill, I brought the bottle: hydrochlorothiazide, 25 milligrams, once a day. The cholesterol one, simvastatin, I stopped in the spring because my legs ached. I never told anyone.",
      allergies: "Amoxicillin. I broke out in hives all over when I was about forty. And seasonal allergies, pollen in the spring.",
      social: "I ran a bakery for thirty years, retired now. I quit smoking twenty years ago. A glass of wine with dinner sometimes. I live with my husband.",
      family: "My father had colon cancer in his seventies.",
      recent_illness: "Just the June attack. I finished the antibiotics in July.",
    },
    exam: {
      general_appearance: { reaction: "", finding: "Well appearing, comfortable, no distress." },
      vitals: { reaction: "", finding: "Temperature 36.9 C, heart rate 70, blood pressure 144/82, respiratory rate 14, oxygen saturation 98% on room air. Weight 76 kg." },
      abdomen_inspection: { reaction: "", finding: "Mildly obese, not distended. Small healed umbilical scar from the tubal ligation. No hernia." },
      abdomen_palpation: { reaction: "Mm, a little sore down there on the left, but nothing like before.", finding: "Mild deep tenderness in the left lower quadrant. No mass, no guarding, no peritonitis." },
      rebound: { reaction: "No, that's okay.", finding: "No rebound tenderness." },
      guarding_rigidity: { reaction: "I'm relaxed, go ahead.", finding: "No guarding or rigidity." },
      mcburney_point: { reaction: "No, the right side's fine.", finding: "Nontender in the right lower quadrant." },
      murphy: { reaction: "No.", finding: "Negative Murphy sign." },
      cva_tenderness: { reaction: "No.", finding: "No costovertebral angle tenderness." },
      chest_lungs: { reaction: "", finding: "Lungs clear, regular heart rhythm." },
    },
    tests: {
      cbc: { result: "White count 7.8, hemoglobin 13.0, platelets 268. Normal.", abnormal: false },
      crp: { result: "CRP 6 mg/L (normal).", abnormal: false },
      bmp: { result: "Sodium 137, potassium 3.4 (low, likely from the thiazide), creatinine 0.9, eGFR above 60, glucose 128. This replaces the cancelled creatinine on her chart.", abnormal: true },
      urinalysis: { result: "No blood, leukocytes, nitrites, or debris. No sign of a colovesical fistula.", abnormal: false },
      ct_abdomen_pelvis: { result: "Sigmoid diverticulosis with mild wall thickening. The June pericolic abscess has resolved. No fistula, no free air, no mass.", abnormal: true },
      type_and_screen: { result: "Type O positive, antibody screen negative.", abnormal: false },
    },
    diagnosis: {
      label: "Recurrent sigmoid diverticulitis, complicated by a resolved abscess",
      keywords: [["diverticul"], ["sigmoid", "recurrent", "complicated", "chronic", "abscess"]],
      partial: { label: "Diverticulitis (recurrent sigmoid disease not named)", keywords: [["diverticul"]] },
    },
    procedureKeywords: [["sigmoid colectomy", "sigmoidectomy", "sigmoid resection", "colectomy", "colon resection", "resect the sigmoid", "remove the sigmoid"]],
    urgency: "elective",
    differential: [
      ddx("cancer", "Colon cancer", "cancer", "carcinoma", "malignan", "tumor"),
      ddx("ibd", "Inflammatory bowel disease", "crohn", "ulcerative", "ibd", "inflammatory bowel"),
      ddx("ischemic", "Ischemic colitis", "ischemi"),
      ddx("ibs", "Irritable bowel syndrome", "ibs", "irritable"),
      ddx("fistula", "Colovesical or colovaginal fistula", "fistula"),
      ddx("ovarian", "Ovarian or adnexal pathology", "ovar", "adnex"),
      ddx("infectious", "Infectious colitis, including C. difficile", "infectious", "c diff", "c. diff", "clostrid"),
    ],
    critical: [
      { kind: "history", id: "medications", why: "Her chart lists an uncoded 'blood pressure pill' and a statin with unknown status. Only she can reconcile them: the pill is hydrochlorothiazide, which lowers potassium and adds to dehydration with bowel prep, and she stopped simvastatin months ago." },
      { kind: "test", id: "bmp", why: "The creatinine on her chart was cancelled, so her kidney function is unknown. She takes metformin and a diuretic and faces bowel prep: check creatinine and potassium before surgery." },
      { kind: "history", id: "past_surgical", why: "A colonoscopy after recovery must exclude cancer before an elective resection: a perforated sigmoid cancer can look exactly like diverticulitis on CT." },
      { kind: "history", id: "allergies", why: "Her chart says only 'Amoxicillin allergy'. She had hives, an immediate-type reaction, so avoid aminopenicillins such as ampicillin-sulbactam. Cefazolin with metronidazole remains a standard colorectal prophylaxis because cefazolin does not share amoxicillin's side chain." },
    ],
    expected: [
      { kind: "history", id: "onset", why: "The pattern of episodes, and above all complicated disease such as her abscess, drive the decision to resect." },
      { kind: "history", id: "past_medical", why: "CT confirmation of each episode proves the diagnosis was diverticulitis and documents the abscess." },
      { kind: "history", id: "urinary", why: "Air or stool in the urine means a colovesical fistula, which changes the operation." },
      { kind: "history", id: "bowel", why: "Bleeding or thinner stools would raise concern for cancer." },
      { kind: "history", id: "family", why: "Her father's colon cancer raises her risk and makes the colonoscopy result essential." },
      { kind: "history", id: "fever", why: "Fever now would mean active disease, and surgery should wait." },
      { kind: "exam", id: "vitals", why: "Normal vitals confirm she is between episodes and fit for an elective resection." },
      { kind: "exam", id: "abdomen_palpation", why: "Mild left lower quadrant tenderness without a mass fits quiescent sigmoid disease. A mass or peritonitis would change the timing." },
      { kind: "test", id: "ct_abdomen_pelvis", why: "Confirms the abscess has resolved and excludes a fistula before planning the resection." },
      { kind: "test", id: "cbc", why: "A normal white count confirms there is no active infection." },
      { kind: "test", id: "urinalysis", why: "Screens for a colovesical fistula and urinary infection." },
      { kind: "test", id: "type_and_screen", why: "A colectomy can bleed: have a type and screen." },
    ],
  },
  {
    planSubject: "patient-demo-consent-partial",
    // This chart shares only medications and allergies: no name, birth date, or sex. The persona is
    // authored for exactly that chart, and the guard refuses it if demographics ever appear.
    persona: {
      speaker: "patient",
      name: "Sam Ortiz",
      patientName: "Sam Ortiz",
      age: 61,
      sex: "male",
      chartDemographics: "not_shared",
      voiceKey: "middle_male",
      demeanor: "A retired city bus driver seen in surgery clinic, friendly but private. He chose to share only his medications and allergies, and is happy to answer questions in person. Pain-free today.",
      character:
        "You drove a city bus for twenty-eight years and retired two years ago. You fish at the reservoir on weekday mornings, grill on Sundays, and listen to baseball on the radio; your grandson Mateo is six. You're private: after a data breach letter you decided apps and hospitals only get what they need, and you'd rather tell a person face to face. When asked something personal you just answer it. You're friendly, easygoing, and polite, call the clinician 'doc', and talk in short plain sentences: 'Yeah, no...', 'Tell you the truth...', and the odd bus-driver comparison. You don't know medical words: 'I'm a bus driver, doc, say it simple.' You warm up once someone talks to you like a person, and you like being asked to confirm who you are: 'Good. That's how it should be.' At the end you're practical and want it done before Mateo's birthday in December.",
      opener: "Afternoon, doc. I'm Sam. They told me to come see you about my gallbladder.",
    },
    history: {
      chief_complaint: "Attacks of pain up under my right ribs, mostly after dinner.",
      onset: "About six months now. Five or six attacks. The last one was two weeks ago.",
      location: "Right side, under the ribs.",
      migration: "Sometimes it goes up to my right shoulder.",
      character: "Steady and hard, like a fist pressing. Not crampy.",
      severity: "A seven during an attack. Nothing right now.",
      aggravating_relieving: "Fried food or a big dinner sets it off. It goes away on its own in an hour or two.",
      nausea_vomiting: "I feel queasy during them. Never thrown up.",
      appetite: "Fine between attacks.",
      fever: "No fevers, no chills.",
      bowel: "Normal. No pale stools, no blood.",
      urinary: "Normal. It's never been dark.",
      last_meal: "Coffee and a muffin at seven.",
      past_medical: "High blood pressure and high cholesterol. No heart attacks, no lung problems, no diabetes that I know of. I only let them see my medicines and allergies. The rest I'd rather tell you myself.",
      past_surgical: "An open hernia repair on the right side, about fifteen years ago. No problems with the anesthesia.",
      allergies: "Penicillin gave me a rash when I was in the army. No swelling, no breathing trouble. Nothing since.",
      social: "Retired bus driver. I quit smoking ten years ago, I smoked a pack a day for about thirty years. A couple of beers on the weekend. I live with my wife.",
      family: "Nothing I know of.",
      recent_illness: "No, I've been fine.",
    },
    exam: {
      general_appearance: { reaction: "", finding: "Well appearing and comfortable. No jaundice or scleral icterus." },
      vitals: { reaction: "", finding: "Temperature 36.8 C, heart rate 76, blood pressure 138/84, respiratory rate 14, oxygen saturation 97% on room air." },
      abdomen_inspection: { reaction: "", finding: "Not distended. Healed right inguinal hernia incision." },
      abdomen_palpation: { reaction: "That's alright. A little tender up on the right, but not like an attack.", finding: "Soft. Minimal right upper quadrant tenderness to deep palpation, no guarding, no mass." },
      murphy: { reaction: "No, I can breathe in fine.", finding: "Negative Murphy sign between attacks." },
      rebound: { reaction: "No.", finding: "No rebound tenderness." },
      mcburney_point: { reaction: "Nothing there.", finding: "Nontender in the right lower quadrant." },
      cva_tenderness: { reaction: "No.", finding: "No costovertebral angle tenderness." },
      chest_lungs: { reaction: "", finding: "Lungs clear, regular heart rhythm." },
      genitourinary: { reaction: "No problems down there.", finding: "No recurrent inguinal hernia." },
    },
    tests: {
      cbc: { result: "White count 6.8, hemoglobin 14.6, platelets 232. Normal.", abnormal: false },
      crp: { result: "CRP 2 mg/L (normal).", abnormal: false },
      bmp: { result: "Sodium 140, potassium 4.5, creatinine 1.0, glucose 104. Normal kidney function.", abnormal: false },
      lfts: { result: "Total bilirubin 0.8, alkaline phosphatase 90, AST 26, ALT 30. Normal.", abnormal: false },
      lipase: { result: "Lipase 30 (normal).", abnormal: false },
      urinalysis: { result: "Normal.", abnormal: false },
      ultrasound: { result: "Multiple gallstones up to 15 mm. Gallbladder wall 3 mm, no pericholecystic fluid, sonographic Murphy sign negative. Common bile duct 4 mm.", abnormal: true },
      ct_abdomen_pelvis: { result: "No acute abnormality. Gallstones not well seen on CT.", abnormal: false },
      type_and_screen: { result: "Type A positive, antibody screen negative.", abnormal: false },
    },
    testNotes: {
      ct_abdomen_pelvis: "Ultrasound is the test for gallstones. CT adds radiation and misses many stones.",
    },
    diagnosis: {
      label: "Symptomatic cholelithiasis (biliary colic)",
      keywords: [["biliary colic", "symptomatic cholelithiasis", "symptomatic gallstone"]],
      partial: { label: "Gallstones (symptomatic biliary colic not named)", keywords: [["gallstone", "cholelithiasis"]] },
    },
    procedureKeywords: [CHOLE_PROCEDURE_KEYWORDS],
    urgency: "elective",
    differential: [
      ddx("cholecystitis", "Acute cholecystitis", "cholecystitis"),
      ddx("cbd", "Choledocholithiasis", "choledocho", "duct stone", "bile duct"),
      ddx("ulcer", "Peptic ulcer disease or gastritis", "ulcer", "peptic", "gastritis"),
      ddx("gerd", "Gastroesophageal reflux", "reflux", "gerd"),
      ddx("pancreatitis", "Pancreatitis", "pancreatitis"),
      ddx("cardiac", "Cardiac ischemia (a former smoker with hypertension)", "angina", "cardiac", "coronary"),
      ddx("liver", "Fatty liver disease or hepatitis", "fatty liver", "hepatitis", "nafld", "masld"),
    ],
    critical: [
      { kind: "history", id: "past_medical", why: "He shared only medications and allergies, so there is no problem list, and no name or birth date on the chart. Ask about heart, lung, kidney, and diabetes history directly, and confirm his identity in person before any procedure." },
      { kind: "test", id: "bmp", why: "No labs were shared. He takes lisinopril, so check kidney function and potassium before surgery." },
      { kind: "test", id: "lfts", why: "No labs were shared. Liver tests screen for a common bile duct stone before an elective cholecystectomy." },
      { kind: "history", id: "allergies", why: "A penicillin rash is on file. Confirm the reaction in person: a remote mild rash still allows cefazolin prophylaxis." },
    ],
    expected: [
      { kind: "history", id: "onset", why: "Repeated attacks over months justify elective removal." },
      { kind: "history", id: "aggravating_relieving", why: "A meal trigger and relief within hours separate colic from cholecystitis." },
      { kind: "history", id: "fever", why: "Fever would mean cholecystitis or cholangitis, not simple colic." },
      { kind: "history", id: "urinary", why: "Dark urine signals a stone blocking the bile duct." },
      { kind: "history", id: "medications", why: "Confirm the shared list is complete and current, including anything over the counter." },
      { kind: "history", id: "social", why: "Thirty pack-years of smoking raises pulmonary and cardiac risk under anesthesia." },
      { kind: "history", id: "past_surgical", why: "Prior surgery and any anesthesia problems shape the plan." },
      { kind: "exam", id: "vitals", why: "There are no vitals on the chart: get a baseline." },
      { kind: "exam", id: "abdomen_palpation", why: "A soft abdomen between attacks supports uncomplicated gallstones." },
      { kind: "exam", id: "murphy", why: "A positive Murphy sign would point to acute cholecystitis instead." },
      { kind: "test", id: "ultrasound", why: "Confirms stones and shows no wall thickening or duct dilation." },
      { kind: "test", id: "cbc", why: "No labs were shared: a baseline blood count before surgery." },
    ],
  },
];

// Subjects a learner can never reach with a buildable case, so they get no interview. Every case plan
// subject must have an encounter or an entry here (validate.ts enforces it).
export const ENCOUNTER_EXCLUSIONS: Record<string, string> = {
  "patient-demo-rate-limited": "FinchNode always rate-limits this record (429), so no chart or case can be built.",
  "patient-demo-consent-revoked": "Consent is revoked (410), so no chart may be read and no case is built.",
};

export const ENCOUNTERS_BY_PLAN = new Map(ENCOUNTERS.map((e) => [e.planSubject, e]));
