import { OPEN_BODY, OPEN_STEPS } from "./open-appendectomy.js";
import type { Port, Procedure, ProcedureStep, Severity, StepMistake, SuccessCheck, Vec3 } from "../types.js";

// Port positions are in the torso frame, meters, for an adult torso (case.bodyScale rescales them):
// origin = umbilicus on the skin surface, +x = patient's left, +y = anterior (up when supine), +z = cranial.
// Registration owns mapping this frame onto the participant; Unity parents ports under the torso root.
// Technique follows standard laparoscopic descriptions and is illustrative, not clinical guidance.

const v = (x: number, y: number, z: number): Vec3 => ({ x, y, z });

const port = (id: string, label: string, sizeMm: number, position: Vec3, instrumentIds: string[]): Port => ({
  id,
  label,
  sizeMm,
  position,
  instrumentIds,
});

const check = (type: SuccessCheck["type"], targets: string[] = [], count = 0): SuccessCheck => ({ type, targets, count });

const mistake = (
  id: string,
  trigger: StepMistake["trigger"],
  structure: string,
  severity: Severity,
  feedback: string,
): StepMistake => ({ id, trigger, structure, severity, feedback });

type StepInput = Omit<ProcedureStep, "next" | "portIds" | "mistakes" | "hints"> &
  Partial<Pick<ProcedureStep, "portIds" | "mistakes" | "hints">>;

// Steps run in array order; next is derived so a step can never point at a missing step.
const chain = (steps: StepInput[]): ProcedureStep[] =>
  steps.map((s, i) => ({
    portIds: [],
    mistakes: [],
    hints: [],
    ...s,
    next: steps[i + 1]?.id ?? "",
  }));

const procedure = (p: Omit<Procedure, "firstStep">): Procedure => ({ ...p, firstStep: p.steps[0]?.id ?? "" });

const cholecystectomy = procedure({
  id: "lap_cholecystectomy",
  title: "Laparoscopic cholecystectomy",
  shortTitle: "Gallbladder removal",
  approach: "Four-port laparoscopic, American position",
  summary:
    "Remove the gallbladder after establishing the critical view of safety: clear the hepatocystic triangle until only the cystic duct and cystic artery enter the gallbladder, then clip, divide, and dissect it off the liver bed.",
  typicalMinutes: 60,
  structures: [
    "abdominal_wall", "umbilicus", "liver", "gallbladder", "cystic_duct", "cystic_artery",
    "common_hepatic_duct", "common_bile_duct", "right_hepatic_artery", "duodenum", "stomach",
    "transverse_colon", "greater_omentum",
  ],
  focusStructures: ["gallbladder", "cystic_duct", "cystic_artery", "common_bile_duct"],
  ports: [
    port("umbilical", "Umbilical camera port", 12, v(0, 0, 0), ["trocar_12mm", "laparoscope_30", "retrieval_bag", "fascial_closure"]),
    port("epigastric", "Epigastric operating port", 12, v(-0.02, 0.01, 0.16), ["trocar_12mm", "maryland_dissector", "hook_cautery", "clip_applier", "lap_scissors", "suction_irrigator", "fascial_closure"]),
    port("right_mcl", "Right midclavicular port", 5, v(-0.07, 0, 0.11), ["trocar_5mm", "atraumatic_grasper"]),
    port("right_aal", "Right anterior axillary port", 5, v(-0.13, -0.02, 0.07), ["trocar_5mm", "atraumatic_grasper"]),
  ],
  steps: chain([
    {
      id: "access_umbilical",
      title: "Open umbilical access",
      instruction: "Enter the peritoneum at the umbilicus with an open technique, place the 12 mm camera port, and insufflate.",
      action: "place_port",
      instrumentId: "trocar_12mm",
      targets: ["umbilicus"],
      portIds: ["umbilical"],
      check: check("place_ports", ["umbilical"], 1),
      hints: ["The camera goes in first so every other port is placed under direct vision."],
    },
    {
      id: "working_ports",
      title: "Place working ports",
      instruction: "Under vision, place the epigastric port and two right subcostal 5 mm ports.",
      action: "place_port",
      instrumentId: "trocar_5mm",
      targets: ["abdominal_wall"],
      portIds: ["epigastric", "right_mcl", "right_aal"],
      check: check("place_ports", ["epigastric", "right_mcl", "right_aal"], 3),
      mistakes: [mistake("port_into_liver", "touch_structure", "liver", "moderate", "The trocar tip contacted the liver. Watch each trocar enter under the camera.")],
      hints: ["Spread the ports so instruments triangulate on the gallbladder instead of clashing."],
    },
    {
      id: "retract_fundus",
      title: "Retract the fundus",
      instruction: "Grasp the gallbladder fundus through the lateral port and push it cephalad over the liver.",
      action: "retract",
      instrumentId: "atraumatic_grasper",
      targets: ["gallbladder"],
      portIds: ["right_aal"],
      check: check("touch_target", ["gallbladder"], 1),
      hints: ["Cephalad fundus retraction lifts the liver edge and exposes the gallbladder neck."],
    },
    {
      id: "retract_infundibulum",
      title: "Retract the infundibulum laterally",
      instruction: "Grasp the infundibulum and pull laterally and inferiorly to open the hepatocystic triangle.",
      action: "retract",
      instrumentId: "atraumatic_grasper",
      targets: ["gallbladder"],
      portIds: ["right_mcl"],
      check: check("touch_target", ["gallbladder"], 1),
      mistakes: [mistake("infundibulum_medial", "wrong_order", "common_bile_duct", "high", "Medial traction aligns the cystic duct with the common bile duct, the classic setup for misidentification. Pull lateral.")],
      hints: ["Lateral traction widens the angle between the cystic duct and the common bile duct."],
    },
    {
      id: "dissect_triangle",
      title: "Clear the hepatocystic triangle",
      instruction: "Open the peritoneum on both sides of the gallbladder neck and clear fat and fibrous tissue from the triangle.",
      action: "dissect",
      instrumentId: "hook_cautery",
      targets: ["gallbladder", "cystic_duct", "cystic_artery"],
      portIds: ["epigastric"],
      check: check("touch_target", ["cystic_duct", "cystic_artery"], 2),
      mistakes: [
        mistake("cautery_on_cbd", "touch_structure", "common_bile_duct", "high", "Energy touched the common bile duct. Stay on the gallbladder side, high on the neck."),
        mistake("cautery_on_rha", "touch_structure", "right_hepatic_artery", "high", "Energy touched the right hepatic artery. It can loop close to the triangle."),
      ],
      hints: ["Dissect close to the gallbladder, both anterior and posterior, before naming any structure."],
    },
    {
      id: "critical_view",
      title: "Confirm the critical view of safety",
      instruction: "Name the two structures entering the gallbladder. Only the cystic duct and cystic artery should remain, with the lower gallbladder lifted off the liver.",
      action: "identify",
      instrumentId: "maryland_dissector",
      targets: ["cystic_duct", "cystic_artery"],
      portIds: ["epigastric"],
      check: check("identify_targets", ["cystic_duct", "cystic_artery"], 2),
      mistakes: [
        mistake("cbd_as_cystic", "wrong_identification", "common_bile_duct", "high", "That is the common bile duct. Clipping it here is the classic bile duct injury. Return to dissection."),
        mistake("cha_as_cystic", "wrong_identification", "common_hepatic_duct", "high", "That is the common hepatic duct, not the cystic duct."),
      ],
      hints: ["Two and only two structures should enter the gallbladder. If you cannot see that, keep dissecting or bail out."],
    },
    {
      id: "clip_artery",
      title: "Clip the cystic artery",
      instruction: "Apply clips to the cystic artery: two on the patient side, one on the gallbladder side.",
      action: "clip",
      instrumentId: "clip_applier",
      targets: ["cystic_artery"],
      portIds: ["epigastric"],
      check: check("apply_count", ["cystic_artery"], 3),
      mistakes: [mistake("clip_rha", "touch_structure", "right_hepatic_artery", "high", "That clip caught the right hepatic artery.")],
    },
    {
      id: "clip_duct",
      title: "Clip the cystic duct",
      instruction: "Apply clips to the cystic duct: two on the patient side, one on the gallbladder side.",
      action: "clip",
      instrumentId: "clip_applier",
      targets: ["cystic_duct"],
      portIds: ["epigastric"],
      check: check("apply_count", ["cystic_duct"], 3),
      mistakes: [mistake("clip_cbd", "touch_structure", "common_bile_duct", "high", "That clip is on the common bile duct.")],
      hints: ["Clips should cross the full width of the duct without catching surrounding tissue."],
    },
    {
      id: "divide_structures",
      title: "Divide the duct and artery",
      instruction: "Cut the cystic artery and cystic duct between the clips with scissors.",
      action: "divide",
      instrumentId: "lap_scissors",
      targets: ["cystic_artery", "cystic_duct"],
      portIds: ["epigastric"],
      check: check("touch_target", ["cystic_artery", "cystic_duct"], 2),
      hints: ["Leave two clips on the patient side of every cut."],
    },
    {
      id: "liver_bed",
      title: "Dissect off the liver bed",
      instruction: "Separate the gallbladder from the cystic plate with the hook, staying in the plane against the gallbladder wall.",
      action: "dissect",
      instrumentId: "hook_cautery",
      targets: ["gallbladder"],
      portIds: ["epigastric"],
      check: check("touch_target", ["gallbladder"], 1),
      mistakes: [mistake("into_liver", "touch_structure", "liver", "moderate", "You entered the liver bed. Too deep bleeds; too shallow perforates the gallbladder.")],
    },
    {
      id: "hemostasis",
      title: "Check hemostasis",
      instruction: "Inspect the liver bed and clips, irrigate, and suction until clear.",
      action: "inspect",
      instrumentId: "suction_irrigator",
      targets: ["liver"],
      portIds: ["epigastric"],
      check: check("touch_target", ["liver"], 1),
    },
    {
      id: "extract",
      title: "Extract the gallbladder",
      instruction: "Place the gallbladder in a retrieval bag and remove it through the umbilical port.",
      action: "extract",
      instrumentId: "retrieval_bag",
      targets: ["gallbladder"],
      portIds: ["umbilical"],
      check: check("touch_target", ["gallbladder"], 1),
    },
    {
      id: "close",
      title: "Close",
      instruction: "Remove ports under vision, release the pneumoperitoneum, and close the fascia at the 12 mm sites.",
      action: "close",
      instrumentId: "fascial_closure",
      targets: ["abdominal_wall"],
      portIds: ["umbilical", "epigastric"],
      check: check("confirm"),
    },
  ]),
});

const appendectomy = procedure({
  id: "lap_appendectomy",
  title: "Laparoscopic appendectomy",
  shortTitle: "Appendix removal",
  approach: "Three-port laparoscopic",
  summary:
    "Find the appendix by following the taeniae of the cecum, divide the mesoappendix with its artery, secure and divide the appendix base, and remove it in a bag.",
  typicalMinutes: 45,
  structures: [
    "abdominal_wall", "umbilicus", "cecum", "appendix", "mesoappendix", "appendicular_artery",
    "terminal_ileum", "small_bowel", "right_ureter", "urinary_bladder", "greater_omentum",
  ],
  focusStructures: ["appendix", "mesoappendix", "appendicular_artery", "cecum"],
  ports: [
    port("umbilical", "Umbilical camera port", 12, v(0, 0, 0), ["trocar_12mm", "laparoscope_30", "endo_stapler", "retrieval_bag", "fascial_closure"]),
    port("left_lower", "Left lower quadrant port", 5, v(0.07, 0, -0.08), ["trocar_5mm", "atraumatic_grasper", "maryland_dissector", "vessel_sealer", "suction_irrigator"]),
    port("suprapubic", "Suprapubic port", 5, v(0, 0, -0.13), ["trocar_5mm", "atraumatic_grasper"]),
  ],
  steps: chain([
    {
      id: "access_umbilical",
      title: "Open umbilical access",
      instruction: "Enter at the umbilicus with an open technique, place the camera port, and insufflate.",
      action: "place_port",
      instrumentId: "trocar_12mm",
      targets: ["umbilicus"],
      portIds: ["umbilical"],
      check: check("place_ports", ["umbilical"], 1),
    },
    {
      id: "working_ports",
      title: "Place working ports",
      instruction: "Place the left lower quadrant and suprapubic ports under vision.",
      action: "place_port",
      instrumentId: "trocar_5mm",
      targets: ["abdominal_wall"],
      portIds: ["left_lower", "suprapubic"],
      check: check("place_ports", ["left_lower", "suprapubic"], 2),
      mistakes: [mistake("port_into_bladder", "touch_structure", "urinary_bladder", "high", "The suprapubic trocar hit the bladder. It should be emptied before surgery and the trocar watched in.")],
    },
    {
      id: "find_appendix",
      title: "Locate the appendix",
      instruction: "Tilt head down and left side down, sweep the small bowel away, and follow the taeniae of the cecum to the appendix base.",
      action: "identify",
      instrumentId: "atraumatic_grasper",
      targets: ["cecum", "appendix"],
      portIds: ["left_lower", "suprapubic"],
      check: check("identify_targets", ["cecum", "appendix"], 2),
      mistakes: [mistake("grab_appendix", "touch_structure", "appendix", "moderate", "Grasping an inflamed appendix can perforate it. Hold the mesoappendix instead.")],
      hints: ["All three taeniae converge on the appendix base."],
    },
    {
      id: "inspect",
      title: "Assess the appendix",
      instruction: "Look for perforation, abscess, or a mass, and run the terminal ileum.",
      action: "inspect",
      instrumentId: "atraumatic_grasper",
      targets: ["appendix", "terminal_ileum"],
      portIds: ["left_lower"],
      check: check("touch_target", ["appendix", "terminal_ileum"], 2),
    },
    {
      id: "mesoappendix_window",
      title: "Window the mesoappendix",
      instruction: "Create a window in the mesoappendix right at the appendix base.",
      action: "dissect",
      instrumentId: "maryland_dissector",
      targets: ["mesoappendix"],
      portIds: ["left_lower"],
      check: check("touch_target", ["mesoappendix"], 1),
    },
    {
      id: "divide_mesoappendix",
      title: "Divide the mesoappendix",
      instruction: "Seal and divide the mesoappendix, including the appendicular artery.",
      action: "seal",
      instrumentId: "vessel_sealer",
      targets: ["mesoappendix", "appendicular_artery"],
      portIds: ["left_lower"],
      check: check("touch_target", ["appendicular_artery"], 1),
      mistakes: [mistake("sealer_on_ileum", "touch_structure", "terminal_ileum", "high", "The sealer jaws were on the terminal ileum. Thermal spread can cause a delayed leak.")],
    },
    {
      id: "staple_base",
      title: "Staple the appendix base",
      instruction: "Fire the stapler across the appendix flush with the cecum.",
      action: "staple",
      instrumentId: "endo_stapler",
      targets: ["appendix"],
      portIds: ["umbilical"],
      check: check("touch_target", ["appendix"], 1),
      mistakes: [
        mistake("staple_cecum_wide", "touch_structure", "cecum", "moderate", "Too much cecum in the jaws. Stay at the base."),
        mistake("staple_ileum", "touch_structure", "terminal_ileum", "high", "The stapler caught the terminal ileum."),
      ],
      hints: ["A long stump left behind can cause stump appendicitis later."],
    },
    {
      id: "extract",
      title: "Extract the appendix",
      instruction: "Bag the appendix and remove it through the umbilical port without touching the wound.",
      action: "extract",
      instrumentId: "retrieval_bag",
      targets: ["appendix"],
      portIds: ["umbilical"],
      check: check("touch_target", ["appendix"], 1),
    },
    {
      id: "irrigate",
      title: "Suction and inspect",
      instruction: "Suction any fluid from the right lower quadrant and pelvis and check the staple line.",
      action: "inspect",
      instrumentId: "suction_irrigator",
      targets: ["cecum"],
      portIds: ["left_lower"],
      check: check("touch_target", ["cecum"], 1),
    },
    {
      id: "close",
      title: "Close",
      instruction: "Remove ports under vision, release the pneumoperitoneum, and close the umbilical fascia.",
      action: "close",
      instrumentId: "fascial_closure",
      targets: ["abdominal_wall"],
      portIds: ["umbilical"],
      check: check("confirm"),
    },
  ]),
});

const sigmoidColectomy = procedure({
  id: "lap_sigmoid_colectomy",
  title: "Laparoscopic sigmoid colectomy",
  shortTitle: "Sigmoid colon resection",
  approach: "Four-port laparoscopic, medial-to-lateral",
  summary:
    "Resect the diseased sigmoid colon: identify and protect the left ureter, divide the inferior mesenteric vessels, mobilize the colon, transect the upper rectum, and restore continuity with a stapled colorectal anastomosis.",
  typicalMinutes: 180,
  structures: [
    "abdominal_wall", "umbilicus", "small_bowel", "greater_omentum", "descending_colon", "sigmoid_colon",
    "sigmoid_mesocolon", "inferior_mesenteric_artery", "left_ureter", "left_gonadal_vessels", "rectum",
    "urinary_bladder",
  ],
  focusStructures: ["sigmoid_colon", "inferior_mesenteric_artery", "left_ureter", "rectum"],
  ports: [
    port("umbilical", "Umbilical camera port", 12, v(0, 0, 0), ["trocar_12mm", "laparoscope_30", "fascial_closure"]),
    port("right_lower", "Right lower quadrant port", 12, v(-0.08, 0, -0.07), ["trocar_12mm", "maryland_dissector", "vessel_sealer", "endo_stapler", "fascial_closure"]),
    port("right_upper", "Right upper quadrant port", 5, v(-0.08, 0, 0.06), ["trocar_5mm", "atraumatic_grasper"]),
    port("left_lower", "Left lower quadrant port", 5, v(0.08, 0, -0.07), ["trocar_5mm", "atraumatic_grasper", "retrieval_bag"]),
  ],
  steps: chain([
    {
      id: "access_umbilical",
      title: "Open umbilical access",
      instruction: "Enter at the umbilicus with an open technique, place the camera port, and insufflate.",
      action: "place_port",
      instrumentId: "trocar_12mm",
      targets: ["umbilicus"],
      portIds: ["umbilical"],
      check: check("place_ports", ["umbilical"], 1),
    },
    {
      id: "working_ports",
      title: "Place working ports",
      instruction: "Place the right lower, right upper, and left lower quadrant ports under vision.",
      action: "place_port",
      instrumentId: "trocar_5mm",
      targets: ["abdominal_wall"],
      portIds: ["right_lower", "right_upper", "left_lower"],
      check: check("place_ports", ["right_lower", "right_upper", "left_lower"], 3),
    },
    {
      id: "expose_pelvis",
      title: "Clear the operative field",
      instruction: "Head down, right side down. Sweep the omentum above the transverse colon and the small bowel out of the pelvis.",
      action: "retract",
      instrumentId: "atraumatic_grasper",
      targets: ["small_bowel", "greater_omentum"],
      portIds: ["right_upper", "left_lower"],
      check: check("touch_target", ["small_bowel"], 1),
    },
    {
      id: "score_mesentery",
      title: "Score the sigmoid mesentery",
      instruction: "Lift the sigmoid mesocolon and score the peritoneum at the sacral promontory beneath the inferior mesenteric artery.",
      action: "dissect",
      instrumentId: "maryland_dissector",
      targets: ["sigmoid_mesocolon"],
      portIds: ["right_lower"],
      check: check("touch_target", ["sigmoid_mesocolon"], 1),
    },
    {
      id: "identify_ureter",
      title: "Identify the left ureter",
      instruction: "Dissect medial to lateral under the mesentery and positively identify the left ureter and gonadal vessels before dividing anything.",
      action: "identify",
      instrumentId: "maryland_dissector",
      targets: ["left_ureter"],
      portIds: ["right_lower"],
      check: check("identify_targets", ["left_ureter"], 1),
      mistakes: [mistake("gonadal_as_ureter", "wrong_identification", "left_gonadal_vessels", "high", "Those are the gonadal vessels. The ureter lies deeper and peristalses when touched.")],
      hints: ["The ureter crosses the iliac vessels near their bifurcation."],
    },
    {
      id: "divide_ima",
      title: "Divide the inferior mesenteric artery",
      instruction: "With the ureter safe, seal and divide the inferior mesenteric artery.",
      action: "seal",
      instrumentId: "vessel_sealer",
      targets: ["inferior_mesenteric_artery"],
      portIds: ["right_lower"],
      check: check("touch_target", ["inferior_mesenteric_artery"], 1),
      mistakes: [mistake("sealer_on_ureter", "touch_structure", "left_ureter", "high", "The ureter was in the sealer jaws.")],
    },
    {
      id: "mobilize_lateral",
      title: "Mobilize the colon laterally",
      instruction: "Release the lateral attachments of the sigmoid and descending colon along the white line of Toldt.",
      action: "dissect",
      instrumentId: "vessel_sealer",
      targets: ["sigmoid_colon", "descending_colon"],
      portIds: ["right_lower"],
      check: check("touch_target", ["sigmoid_colon", "descending_colon"], 2),
    },
    {
      id: "transect_rectum",
      title: "Transect the upper rectum",
      instruction: "Fire the linear stapler across the upper rectum below the diseased segment.",
      action: "staple",
      instrumentId: "endo_stapler",
      targets: ["rectum"],
      portIds: ["right_lower"],
      check: check("touch_target", ["rectum"], 1),
      hints: ["Leaving sigmoid behind raises recurrence risk. Transect on soft rectum where the taeniae splay."],
    },
    {
      id: "extract",
      title: "Extract and divide proximally",
      instruction: "Bring the specimen out through a protected small incision, divide the proximal colon, and seat the stapler anvil.",
      action: "extract",
      instrumentId: "retrieval_bag",
      targets: ["sigmoid_colon"],
      portIds: ["left_lower"],
      check: check("touch_target", ["sigmoid_colon"], 1),
    },
    {
      id: "anastomosis",
      title: "Create the anastomosis",
      instruction: "Pass the circular stapler transanally and join the descending colon to the rectum, with no tension and no twist.",
      action: "anastomose",
      instrumentId: "circular_stapler",
      targets: ["descending_colon", "rectum"],
      portIds: [],
      check: check("touch_target", ["descending_colon", "rectum"], 2),
      mistakes: [mistake("bladder_in_stapler", "touch_structure", "urinary_bladder", "high", "Pelvic tissue was caught in the stapler.")],
    },
    {
      id: "leak_test",
      title: "Leak test",
      instruction: "Fill the pelvis with saline, clamp above the anastomosis, and insufflate the rectum. No bubbles means no leak.",
      action: "inspect",
      instrumentId: "atraumatic_grasper",
      targets: ["rectum"],
      portIds: ["right_upper"],
      check: check("confirm"),
    },
    {
      id: "close",
      title: "Close",
      instruction: "Remove ports under vision, release the pneumoperitoneum, and close the extraction site and 12 mm fascia.",
      action: "close",
      instrumentId: "fascial_closure",
      targets: ["abdominal_wall"],
      portIds: ["umbilical", "right_lower"],
      check: check("confirm"),
    },
  ]),
});

// Open approach is a separate catalog; the retained lap procedure is not silently reinterpreted.
const openAppendectomy = procedure({
  id: "open_appendectomy", title: "Open appendectomy", shortTitle: "Open appendix removal",
  approach: "Open muscle-splitting incision", typicalMinutes: 45,
  summary: "Registered incision, layered exposure, delivery, vascular control and base ligation, then dry inspection.",
  structures: ["abdominal_wall", "umbilicus", "appendix", "mesoappendix", "appendicular_artery", "cecum", "terminal_ileum"],
  focusStructures: ["appendix", "mesoappendix", "cecum"], ports: [],
  openBody: OPEN_BODY,
  steps: OPEN_STEPS,
});

export const PROCEDURES: Procedure[] = [cholecystectomy, appendectomy, sigmoidColectomy, openAppendectomy];

export const PROCEDURES_BY_ID = new Map(PROCEDURES.map((p) => [p.id, p]));
