import { describe,it,expect } from 'vitest';
import { BodyState,bodyAction } from '../src/open-body.js';
import { OPEN_BODY } from '../src/catalog/open-appendectomy.js';
import { PROCEDURES_BY_ID } from '../src/catalog/procedures.js';
import { StepEngine,perfectEvents } from '../src/engine.js';
const procedure=PROCEDURES_BY_ID.get('open_appendectomy')!;
function exposed(){const engine=new StepEngine(procedure);for(const s of procedure.steps.slice(0,5))for(const e of perfectEvents(s))engine.handle(e);return engine;}
describe('case-agnostic body and predicate scorer',()=>{
 it('completes expected path without touch shortcuts',()=>{const e=new StepEngine(procedure);e.handle({type:'confirm'});expect(e.current?.id).toBe('mark_incision');for(const s of procedure.steps)for(const a of perfectEvents(s))e.handle(a);expect(e.completed).toBe(true);expect(e.mistakes).toEqual([]);});
 it('records bowel injury and contamination while coaching an unrelated milestone',()=>{const e=exposed();const r=e.handle({type:'surgery',evidence:bodyAction('cut','terminal_ileum',{lengthMm:4})});expect(r.mistake?.id).toBe('bowel_injury');expect(e.body!.get('','contamination')).toBe(1);expect(e.mistakes.map(m=>m.id)).toContain('critical_injury');});
 it('cut before clamp bleeds, accumulates loss, and clamp/tie stop it',()=>{const e=exposed();e.handle({type:'surgery',evidence:bodyAction('cut','mesoappendix',{lengthMm:4})});expect(e.body!.get('','activeBleeds')).toBe(1);e.handle({type:'surgery',evidence:bodyAction('clamp','mesoappendix',{instrumentId:'hemostat',timeMs:2000})});expect(e.body!.get('','bloodLostMl')).toBe(4);expect(e.body!.get('','activeBleeds')).toBe(0);e.handle({type:'surgery',evidence:bodyAction('cut','appendicular_artery',{timeMs:2000,lengthMm:4})});e.handle({type:'surgery',evidence:bodyAction('tie','appendicular_artery',{instrumentId:'suture_tie',timeMs:3000})});expect(e.body!.get('','activeBleeds')).toBe(0);expect(e.body!.get('','bloodLostMl')).toBe(6);expect(e.mistakes.length).toBe(2);});
 it('recognizes milestones out of order and records soft deviations',()=>{const e=exposed();for(const a of perfectEvents(procedure.steps[7]!))e.handle(a);expect(e.completedMilestones.has('ligate_base')).toBe(true);expect(e.current?.id).toBe('deliver_appendix');expect(e.orderDeviations).toContain('ligate_base');});
 it('requires measured stump length and decision; a long stump does not pass',()=>{const e=exposed();for(const a of perfectEvents(procedure.steps[7]!)){if(a.type==='surgery'&&a.evidence.verb==='cut')a.evidence.distanceMm=8;e.handle(a);}expect(e.completedMilestones.has('ligate_base')).toBe(false);expect(e.body!.get('appendix','stumpLengthMm')).toBe(8);expect(e.body!.test({tissueId:'missing',fact:'length',op:'lte',value:5})).toBe(false);});
 it('same verbs produce identical consequences under a second case',()=>{const a=exposed(),other={...procedure,id:'dummy_case',openBody:{...OPEN_BODY,milestones:[],guardrails:[]}};const b=new StepEngine(other);for(const s of procedure.steps.slice(0,5))for(const e of perfectEvents(s))b.handle(e);const injury={type:'surgery' as const,evidence:bodyAction('cut','terminal_ileum',{lengthMm:4})};a.handle(injury);b.handle(injury);expect([...b.body!.facts]).toEqual([...a.body!.facts]);expect(b.body!.log).toEqual(a.body!.log);});
 it('rejects invalid registration, replay, old clock, wrong tool, and blocks hidden layers',()=>{const b=new BodyState(OPEN_BODY.tissues);expect(b.apply(bodyAction('cut','skin',{registered:false}))).toBeNull();expect(b.apply(bodyAction('cut','skin',{instrumentId:'skin_marker'}))).toBeNull();const hidden=b.apply(bodyAction('cut','fascia',{timeMs:2}));expect(hidden?.outcomes).toEqual(['not_exposed']);expect(b.get('fascia','opened')).toBe(0);expect(b.apply(bodyAction('cut','fascia',{timeMs:2}))).toBeNull();expect(b.apply(bodyAction('cut','skin',{timeMs:1}))).toBeNull();});
 it('a new bleed invalidates the no-active-bleed milestone without erasing history',()=>{const e=exposed();for(const a of perfectEvents(procedure.steps[6]!))e.handle(a);expect(e.completedMilestones.has('divide_mesoappendix')).toBe(true);e.handle({type:'surgery',evidence:bodyAction('cut','appendicular_artery',{lengthMm:4})});expect(e.body!.test({tissueId:'',fact:'activeBleeds',op:'eq',value:0})).toBe(false);});
});
