// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MyRtcSignalsHandle : RemoteTableHandle<EventContext, RtcSignal>
        {
            public override string RemoteTableName => "my_rtc_signals";

            public sealed class SignalIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RtcSignal row) => row.SignalId;

                public SignalIdUniqueIndex(MyRtcSignalsHandle table) : base(table) { }
            }

            public readonly SignalIdUniqueIndex SignalId;

            internal MyRtcSignalsHandle(DbConnection conn) : base(conn)
            {
                SignalId = new(this);
            }

            protected override object GetPrimaryKey(RtcSignal row) => row.SignalId;
        }

        public readonly MyRtcSignalsHandle MyRtcSignals;
    }

    public sealed class MyRtcSignalsCols
    {
        public global::SpacetimeDB.Col<RtcSignal, ulong> SignalId { get; }
        public global::SpacetimeDB.Col<RtcSignal, string> SessionId { get; }
        public global::SpacetimeDB.Col<RtcSignal, SpacetimeDB.Identity> From { get; }
        public global::SpacetimeDB.Col<RtcSignal, SpacetimeDB.Identity> To { get; }
        public global::SpacetimeDB.Col<RtcSignal, string> PeerId { get; }
        public global::SpacetimeDB.Col<RtcSignal, string> Kind { get; }
        public global::SpacetimeDB.Col<RtcSignal, string> Payload { get; }
        public global::SpacetimeDB.Col<RtcSignal, SpacetimeDB.Timestamp> CreatedAt { get; }

        public MyRtcSignalsCols(string tableName)
        {
            SignalId = new global::SpacetimeDB.Col<RtcSignal, ulong>(tableName, "signal_id");
            SessionId = new global::SpacetimeDB.Col<RtcSignal, string>(tableName, "session_id");
            From = new global::SpacetimeDB.Col<RtcSignal, SpacetimeDB.Identity>(tableName, "from");
            To = new global::SpacetimeDB.Col<RtcSignal, SpacetimeDB.Identity>(tableName, "to");
            PeerId = new global::SpacetimeDB.Col<RtcSignal, string>(tableName, "peer_id");
            Kind = new global::SpacetimeDB.Col<RtcSignal, string>(tableName, "kind");
            Payload = new global::SpacetimeDB.Col<RtcSignal, string>(tableName, "payload");
            CreatedAt = new global::SpacetimeDB.Col<RtcSignal, SpacetimeDB.Timestamp>(tableName, "created_at");
        }
    }

    public sealed class MyRtcSignalsIxCols
    {
        public global::SpacetimeDB.IxCol<RtcSignal, ulong> SignalId { get; }

        public MyRtcSignalsIxCols(string tableName)
        {
            SignalId = new global::SpacetimeDB.IxCol<RtcSignal, ulong>(tableName, "signal_id");
        }
    }
}
