// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MyServiceGrantsHandle : RemoteTableHandle<EventContext, ServiceGrant>
        {
            public override string RemoteTableName => "my_service_grants";

            public sealed class GrantIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ServiceGrant row) => row.GrantId;

                public GrantIdUniqueIndex(MyServiceGrantsHandle table) : base(table) { }
            }

            public readonly GrantIdUniqueIndex GrantId;

            internal MyServiceGrantsHandle(DbConnection conn) : base(conn)
            {
                GrantId = new(this);
            }

            protected override object GetPrimaryKey(ServiceGrant row) => row.GrantId;
        }

        public readonly MyServiceGrantsHandle MyServiceGrants;
    }

    public sealed class MyServiceGrantsCols
    {
        public global::SpacetimeDB.Col<ServiceGrant, string> GrantId { get; }
        public global::SpacetimeDB.Col<ServiceGrant, string> SessionId { get; }
        public global::SpacetimeDB.Col<ServiceGrant, string> Kind { get; }
        public global::SpacetimeDB.Col<ServiceGrant, SpacetimeDB.Identity> RequestedBy { get; }
        public global::SpacetimeDB.Col<ServiceGrant, SpacetimeDB.Timestamp> RequestedAt { get; }
        public global::SpacetimeDB.Col<ServiceGrant, string> Status { get; }
        public global::SpacetimeDB.Col<ServiceGrant, string> Payload { get; }
        public global::SpacetimeDB.Col<ServiceGrant, string> Reason { get; }
        public global::SpacetimeDB.Col<ServiceGrant, SpacetimeDB.Timestamp> ExpiresAt { get; }

        public MyServiceGrantsCols(string tableName)
        {
            GrantId = new global::SpacetimeDB.Col<ServiceGrant, string>(tableName, "grant_id");
            SessionId = new global::SpacetimeDB.Col<ServiceGrant, string>(tableName, "session_id");
            Kind = new global::SpacetimeDB.Col<ServiceGrant, string>(tableName, "kind");
            RequestedBy = new global::SpacetimeDB.Col<ServiceGrant, SpacetimeDB.Identity>(tableName, "requested_by");
            RequestedAt = new global::SpacetimeDB.Col<ServiceGrant, SpacetimeDB.Timestamp>(tableName, "requested_at");
            Status = new global::SpacetimeDB.Col<ServiceGrant, string>(tableName, "status");
            Payload = new global::SpacetimeDB.Col<ServiceGrant, string>(tableName, "payload");
            Reason = new global::SpacetimeDB.Col<ServiceGrant, string>(tableName, "reason");
            ExpiresAt = new global::SpacetimeDB.Col<ServiceGrant, SpacetimeDB.Timestamp>(tableName, "expires_at");
        }
    }

    public sealed class MyServiceGrantsIxCols
    {
        public global::SpacetimeDB.IxCol<ServiceGrant, string> GrantId { get; }

        public MyServiceGrantsIxCols(string tableName)
        {
            GrantId = new global::SpacetimeDB.IxCol<ServiceGrant, string>(tableName, "grant_id");
        }
    }
}
