// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionEncountersHandle : RemoteTableHandle<EventContext, Encounter>
        {
            public override string RemoteTableName => "session_encounters";

            public sealed class EncounterIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Encounter row) => row.EncounterId;

                public EncounterIdUniqueIndex(SessionEncountersHandle table) : base(table) { }
            }

            public readonly EncounterIdUniqueIndex EncounterId;

            internal SessionEncountersHandle(DbConnection conn) : base(conn)
            {
                EncounterId = new(this);
            }

            protected override object GetPrimaryKey(Encounter row) => row.EncounterId;
        }

        public readonly SessionEncountersHandle SessionEncounters;
    }

    public sealed class SessionEncountersCols
    {
        public global::SpacetimeDB.Col<Encounter, string> EncounterId { get; }
        public global::SpacetimeDB.Col<Encounter, string> SessionId { get; }
        public global::SpacetimeDB.Col<Encounter, string> AttemptId { get; }
        public global::SpacetimeDB.Col<Encounter, string> PatientId { get; }
        public global::SpacetimeDB.Col<Encounter, string> PatientName { get; }
        public global::SpacetimeDB.Col<Encounter, string> Speaker { get; }
        public global::SpacetimeDB.Col<Encounter, string> SpeakerName { get; }
        public global::SpacetimeDB.Col<Encounter, string> Phase { get; }
        public global::SpacetimeDB.Col<Encounter, uint> ScoreTotal { get; }
        public global::SpacetimeDB.Col<Encounter, string> Grade { get; }
        public global::SpacetimeDB.Col<Encounter, string> ScorecardJson { get; }
        public global::SpacetimeDB.Col<Encounter, SpacetimeDB.Timestamp> StartedAt { get; }
        public global::SpacetimeDB.Col<Encounter, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public SessionEncountersCols(string tableName)
        {
            EncounterId = new global::SpacetimeDB.Col<Encounter, string>(tableName, "encounter_id");
            SessionId = new global::SpacetimeDB.Col<Encounter, string>(tableName, "session_id");
            AttemptId = new global::SpacetimeDB.Col<Encounter, string>(tableName, "attempt_id");
            PatientId = new global::SpacetimeDB.Col<Encounter, string>(tableName, "patient_id");
            PatientName = new global::SpacetimeDB.Col<Encounter, string>(tableName, "patient_name");
            Speaker = new global::SpacetimeDB.Col<Encounter, string>(tableName, "speaker");
            SpeakerName = new global::SpacetimeDB.Col<Encounter, string>(tableName, "speaker_name");
            Phase = new global::SpacetimeDB.Col<Encounter, string>(tableName, "phase");
            ScoreTotal = new global::SpacetimeDB.Col<Encounter, uint>(tableName, "score_total");
            Grade = new global::SpacetimeDB.Col<Encounter, string>(tableName, "grade");
            ScorecardJson = new global::SpacetimeDB.Col<Encounter, string>(tableName, "scorecard_json");
            StartedAt = new global::SpacetimeDB.Col<Encounter, SpacetimeDB.Timestamp>(tableName, "started_at");
            UpdatedAt = new global::SpacetimeDB.Col<Encounter, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class SessionEncountersIxCols
    {
        public global::SpacetimeDB.IxCol<Encounter, string> EncounterId { get; }

        public SessionEncountersIxCols(string tableName)
        {
            EncounterId = new global::SpacetimeDB.IxCol<Encounter, string>(tableName, "encounter_id");
        }
    }
}
