// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionPatientConditionHandle : RemoteTableHandle<EventContext, PatientCondition>
        {
            public override string RemoteTableName => "session_patient_condition";

            public sealed class SessionIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PatientCondition row) => row.SessionId;

                public SessionIdUniqueIndex(SessionPatientConditionHandle table) : base(table) { }
            }

            public readonly SessionIdUniqueIndex SessionId;

            internal SessionPatientConditionHandle(DbConnection conn) : base(conn)
            {
                SessionId = new(this);
            }

            protected override object GetPrimaryKey(PatientCondition row) => row.SessionId;
        }

        public readonly SessionPatientConditionHandle SessionPatientCondition;
    }

    public sealed class SessionPatientConditionCols
    {
        public global::SpacetimeDB.Col<PatientCondition, string> SessionId { get; }
        public global::SpacetimeDB.Col<PatientCondition, string> CoachSessionId { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> BaselineHr { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> BaselineRr { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> BaselineSys { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> BaselineDia { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> BaselineSpo2 { get; }
        public global::SpacetimeDB.Col<PatientCondition, string> BaselineSource { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> WeightKg { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> MlPerKg { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> EbvMl { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> Scale { get; }
        public global::SpacetimeDB.Col<PatientCondition, int> Hr { get; }
        public global::SpacetimeDB.Col<PatientCondition, int> Rr { get; }
        public global::SpacetimeDB.Col<PatientCondition, int> Sys { get; }
        public global::SpacetimeDB.Col<PatientCondition, int> Dia { get; }
        public global::SpacetimeDB.Col<PatientCondition, int> Spo2 { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> BloodLossPct { get; }
        public global::SpacetimeDB.Col<PatientCondition, uint> HemorrhageClass { get; }
        public global::SpacetimeDB.Col<PatientCondition, string> Label { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> BodyLostMl { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> RegionLostMl { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> BloodLostMl { get; }
        public global::SpacetimeDB.Col<PatientCondition, double> BodyBleedMlPerMin { get; }
        public global::SpacetimeDB.Col<PatientCondition, string> ActiveBleedsJson { get; }
        public global::SpacetimeDB.Col<PatientCondition, string> RegionInjuriesJson { get; }
        public global::SpacetimeDB.Col<PatientCondition, string> OutcomeResult { get; }
        public global::SpacetimeDB.Col<PatientCondition, string> OutcomeCause { get; }
        public global::SpacetimeDB.Col<PatientCondition, SpacetimeDB.Timestamp> OutcomeAt { get; }
        public global::SpacetimeDB.Col<PatientCondition, ulong> Version { get; }
        public global::SpacetimeDB.Col<PatientCondition, SpacetimeDB.Timestamp> StartedAt { get; }
        public global::SpacetimeDB.Col<PatientCondition, SpacetimeDB.Timestamp> AdvancedAt { get; }
        public global::SpacetimeDB.Col<PatientCondition, SpacetimeDB.Timestamp> UpdatedAt { get; }

        public SessionPatientConditionCols(string tableName)
        {
            SessionId = new global::SpacetimeDB.Col<PatientCondition, string>(tableName, "session_id");
            CoachSessionId = new global::SpacetimeDB.Col<PatientCondition, string>(tableName, "coach_session_id");
            BaselineHr = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "baseline_hr");
            BaselineRr = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "baseline_rr");
            BaselineSys = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "baseline_sys");
            BaselineDia = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "baseline_dia");
            BaselineSpo2 = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "baseline_spo_2");
            BaselineSource = new global::SpacetimeDB.Col<PatientCondition, string>(tableName, "baseline_source");
            WeightKg = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "weight_kg");
            MlPerKg = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "ml_per_kg");
            EbvMl = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "ebv_ml");
            Scale = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "scale");
            Hr = new global::SpacetimeDB.Col<PatientCondition, int>(tableName, "hr");
            Rr = new global::SpacetimeDB.Col<PatientCondition, int>(tableName, "rr");
            Sys = new global::SpacetimeDB.Col<PatientCondition, int>(tableName, "sys");
            Dia = new global::SpacetimeDB.Col<PatientCondition, int>(tableName, "dia");
            Spo2 = new global::SpacetimeDB.Col<PatientCondition, int>(tableName, "spo_2");
            BloodLossPct = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "blood_loss_pct");
            HemorrhageClass = new global::SpacetimeDB.Col<PatientCondition, uint>(tableName, "hemorrhage_class");
            Label = new global::SpacetimeDB.Col<PatientCondition, string>(tableName, "label");
            BodyLostMl = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "body_lost_ml");
            RegionLostMl = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "region_lost_ml");
            BloodLostMl = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "blood_lost_ml");
            BodyBleedMlPerMin = new global::SpacetimeDB.Col<PatientCondition, double>(tableName, "body_bleed_ml_per_min");
            ActiveBleedsJson = new global::SpacetimeDB.Col<PatientCondition, string>(tableName, "active_bleeds_json");
            RegionInjuriesJson = new global::SpacetimeDB.Col<PatientCondition, string>(tableName, "region_injuries_json");
            OutcomeResult = new global::SpacetimeDB.Col<PatientCondition, string>(tableName, "outcome_result");
            OutcomeCause = new global::SpacetimeDB.Col<PatientCondition, string>(tableName, "outcome_cause");
            OutcomeAt = new global::SpacetimeDB.Col<PatientCondition, SpacetimeDB.Timestamp>(tableName, "outcome_at");
            Version = new global::SpacetimeDB.Col<PatientCondition, ulong>(tableName, "version");
            StartedAt = new global::SpacetimeDB.Col<PatientCondition, SpacetimeDB.Timestamp>(tableName, "started_at");
            AdvancedAt = new global::SpacetimeDB.Col<PatientCondition, SpacetimeDB.Timestamp>(tableName, "advanced_at");
            UpdatedAt = new global::SpacetimeDB.Col<PatientCondition, SpacetimeDB.Timestamp>(tableName, "updated_at");
        }
    }

    public sealed class SessionPatientConditionIxCols
    {
        public global::SpacetimeDB.IxCol<PatientCondition, string> SessionId { get; }

        public SessionPatientConditionIxCols(string tableName)
        {
            SessionId = new global::SpacetimeDB.IxCol<PatientCondition, string>(tableName, "session_id");
        }
    }
}
