// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionExerciseStateHandle : RemoteTableHandle<EventContext, ExerciseState>
        {
            public override string RemoteTableName => "session_exercise_state";

            public sealed class SessionIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ExerciseState row) => row.SessionId;

                public SessionIdUniqueIndex(SessionExerciseStateHandle table) : base(table) { }
            }

            public readonly SessionIdUniqueIndex SessionId;

            internal SessionExerciseStateHandle(DbConnection conn) : base(conn)
            {
                SessionId = new(this);
            }

            protected override object GetPrimaryKey(ExerciseState row) => row.SessionId;
        }

        public readonly SessionExerciseStateHandle SessionExerciseState;
    }

    public sealed class SessionExerciseStateCols
    {
        public global::SpacetimeDB.Col<ExerciseState, string> SessionId { get; }
        public global::SpacetimeDB.Col<ExerciseState, string> AttemptId { get; }
        public global::SpacetimeDB.Col<ExerciseState, string> ExerciseId { get; }
        public global::SpacetimeDB.Col<ExerciseState, string> ExerciseVersion { get; }
        public global::SpacetimeDB.Col<ExerciseState, string> Mode { get; }
        public global::SpacetimeDB.Col<ExerciseState, string> StepId { get; }
        public global::SpacetimeDB.Col<ExerciseState, uint> StepIndex { get; }
        public global::SpacetimeDB.Col<ExerciseState, uint> StepCount { get; }
        public global::SpacetimeDB.Col<ExerciseState, string> SelectedStructureId { get; }
        public global::SpacetimeDB.Col<ExerciseState, string> HighlightedStructureId { get; }
        public global::SpacetimeDB.Col<ExerciseState, bool> PreviewRotating { get; }
        public global::SpacetimeDB.Col<ExerciseState, bool> Paused { get; }
        public global::SpacetimeDB.Col<ExerciseState, string> Registration { get; }
        public global::SpacetimeDB.Col<ExerciseState, string> RegistrationReason { get; }
        public global::SpacetimeDB.Col<ExerciseState, string> Recording { get; }
        public global::SpacetimeDB.Col<ExerciseState, ulong> StateVersion { get; }
        public global::SpacetimeDB.Col<ExerciseState, ulong> StepVersion { get; }
        public global::SpacetimeDB.Col<ExerciseState, SpacetimeDB.Timestamp> UpdatedAt { get; }
        public global::SpacetimeDB.Col<ExerciseState, SpacetimeDB.Identity> UpdatedBy { get; }

        public SessionExerciseStateCols(string tableName)
        {
            SessionId = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "session_id");
            AttemptId = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "attempt_id");
            ExerciseId = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "exercise_id");
            ExerciseVersion = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "exercise_version");
            Mode = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "mode");
            StepId = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "step_id");
            StepIndex = new global::SpacetimeDB.Col<ExerciseState, uint>(tableName, "step_index");
            StepCount = new global::SpacetimeDB.Col<ExerciseState, uint>(tableName, "step_count");
            SelectedStructureId = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "selected_structure_id");
            HighlightedStructureId = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "highlighted_structure_id");
            PreviewRotating = new global::SpacetimeDB.Col<ExerciseState, bool>(tableName, "preview_rotating");
            Paused = new global::SpacetimeDB.Col<ExerciseState, bool>(tableName, "paused");
            Registration = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "registration");
            RegistrationReason = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "registration_reason");
            Recording = new global::SpacetimeDB.Col<ExerciseState, string>(tableName, "recording");
            StateVersion = new global::SpacetimeDB.Col<ExerciseState, ulong>(tableName, "state_version");
            StepVersion = new global::SpacetimeDB.Col<ExerciseState, ulong>(tableName, "step_version");
            UpdatedAt = new global::SpacetimeDB.Col<ExerciseState, SpacetimeDB.Timestamp>(tableName, "updated_at");
            UpdatedBy = new global::SpacetimeDB.Col<ExerciseState, SpacetimeDB.Identity>(tableName, "updated_by");
        }
    }

    public sealed class SessionExerciseStateIxCols
    {
        public global::SpacetimeDB.IxCol<ExerciseState, string> SessionId { get; }

        public SessionExerciseStateIxCols(string tableName)
        {
            SessionId = new global::SpacetimeDB.IxCol<ExerciseState, string>(tableName, "session_id");
        }
    }
}
