// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionMembersHandle : RemoteTableHandle<EventContext, SessionMember>
        {
            public override string RemoteTableName => "session_members";

            public sealed class MembershipIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SessionMember row) => row.MembershipId;

                public MembershipIdUniqueIndex(SessionMembersHandle table) : base(table) { }
            }

            public readonly MembershipIdUniqueIndex MembershipId;

            internal SessionMembersHandle(DbConnection conn) : base(conn)
            {
                MembershipId = new(this);
            }

            protected override object GetPrimaryKey(SessionMember row) => row.MembershipId;
        }

        public readonly SessionMembersHandle SessionMembers;
    }

    public sealed class SessionMembersCols
    {
        public global::SpacetimeDB.Col<SessionMember, ulong> MembershipId { get; }
        public global::SpacetimeDB.Col<SessionMember, string> SessionId { get; }
        public global::SpacetimeDB.Col<SessionMember, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<SessionMember, string> Role { get; }
        public global::SpacetimeDB.Col<SessionMember, string> DisplayName { get; }
        public global::SpacetimeDB.Col<SessionMember, SpacetimeDB.Timestamp> JoinedAt { get; }
        public global::SpacetimeDB.Col<SessionMember, bool> Online { get; }

        public SessionMembersCols(string tableName)
        {
            MembershipId = new global::SpacetimeDB.Col<SessionMember, ulong>(tableName, "membership_id");
            SessionId = new global::SpacetimeDB.Col<SessionMember, string>(tableName, "session_id");
            Identity = new global::SpacetimeDB.Col<SessionMember, SpacetimeDB.Identity>(tableName, "identity");
            Role = new global::SpacetimeDB.Col<SessionMember, string>(tableName, "role");
            DisplayName = new global::SpacetimeDB.Col<SessionMember, string>(tableName, "display_name");
            JoinedAt = new global::SpacetimeDB.Col<SessionMember, SpacetimeDB.Timestamp>(tableName, "joined_at");
            Online = new global::SpacetimeDB.Col<SessionMember, bool>(tableName, "online");
        }
    }

    public sealed class SessionMembersIxCols
    {
        public global::SpacetimeDB.IxCol<SessionMember, ulong> MembershipId { get; }

        public SessionMembersIxCols(string tableName)
        {
            MembershipId = new global::SpacetimeDB.IxCol<SessionMember, ulong>(tableName, "membership_id");
        }
    }
}
