// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionArtifactsHandle : RemoteTableHandle<EventContext, Artifact>
        {
            public override string RemoteTableName => "session_artifacts";

            public sealed class ArtifactIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Artifact row) => row.ArtifactId;

                public ArtifactIdUniqueIndex(SessionArtifactsHandle table) : base(table) { }
            }

            public readonly ArtifactIdUniqueIndex ArtifactId;

            internal SessionArtifactsHandle(DbConnection conn) : base(conn)
            {
                ArtifactId = new(this);
            }

            protected override object GetPrimaryKey(Artifact row) => row.ArtifactId;
        }

        public readonly SessionArtifactsHandle SessionArtifacts;
    }

    public sealed class SessionArtifactsCols
    {
        public global::SpacetimeDB.Col<Artifact, string> ArtifactId { get; }
        public global::SpacetimeDB.Col<Artifact, string> SessionId { get; }
        public global::SpacetimeDB.Col<Artifact, string> AttemptId { get; }
        public global::SpacetimeDB.Col<Artifact, string> Kind { get; }
        public global::SpacetimeDB.Col<Artifact, string> StorageKey { get; }
        public global::SpacetimeDB.Col<Artifact, string> Filename { get; }
        public global::SpacetimeDB.Col<Artifact, string> ContentType { get; }
        public global::SpacetimeDB.Col<Artifact, ulong> DeclaredBytes { get; }
        public global::SpacetimeDB.Col<Artifact, ulong> VerifiedBytes { get; }
        public global::SpacetimeDB.Col<Artifact, string> Sha256 { get; }
        public global::SpacetimeDB.Col<Artifact, string> Status { get; }
        public global::SpacetimeDB.Col<Artifact, string> StatusReason { get; }
        public global::SpacetimeDB.Col<Artifact, string> JobId { get; }
        public global::SpacetimeDB.Col<Artifact, uint> JobRun { get; }
        public global::SpacetimeDB.Col<Artifact, SpacetimeDB.Identity> CreatedBy { get; }
        public global::SpacetimeDB.Col<Artifact, SpacetimeDB.Timestamp> CreatedAt { get; }
        public global::SpacetimeDB.Col<Artifact, SpacetimeDB.Timestamp> AvailableAt { get; }

        public SessionArtifactsCols(string tableName)
        {
            ArtifactId = new global::SpacetimeDB.Col<Artifact, string>(tableName, "artifact_id");
            SessionId = new global::SpacetimeDB.Col<Artifact, string>(tableName, "session_id");
            AttemptId = new global::SpacetimeDB.Col<Artifact, string>(tableName, "attempt_id");
            Kind = new global::SpacetimeDB.Col<Artifact, string>(tableName, "kind");
            StorageKey = new global::SpacetimeDB.Col<Artifact, string>(tableName, "storage_key");
            Filename = new global::SpacetimeDB.Col<Artifact, string>(tableName, "filename");
            ContentType = new global::SpacetimeDB.Col<Artifact, string>(tableName, "content_type");
            DeclaredBytes = new global::SpacetimeDB.Col<Artifact, ulong>(tableName, "declared_bytes");
            VerifiedBytes = new global::SpacetimeDB.Col<Artifact, ulong>(tableName, "verified_bytes");
            Sha256 = new global::SpacetimeDB.Col<Artifact, string>(tableName, "sha_256");
            Status = new global::SpacetimeDB.Col<Artifact, string>(tableName, "status");
            StatusReason = new global::SpacetimeDB.Col<Artifact, string>(tableName, "status_reason");
            JobId = new global::SpacetimeDB.Col<Artifact, string>(tableName, "job_id");
            JobRun = new global::SpacetimeDB.Col<Artifact, uint>(tableName, "job_run");
            CreatedBy = new global::SpacetimeDB.Col<Artifact, SpacetimeDB.Identity>(tableName, "created_by");
            CreatedAt = new global::SpacetimeDB.Col<Artifact, SpacetimeDB.Timestamp>(tableName, "created_at");
            AvailableAt = new global::SpacetimeDB.Col<Artifact, SpacetimeDB.Timestamp>(tableName, "available_at");
        }
    }

    public sealed class SessionArtifactsIxCols
    {
        public global::SpacetimeDB.IxCol<Artifact, string> ArtifactId { get; }

        public SessionArtifactsIxCols(string tableName)
        {
            ArtifactId = new global::SpacetimeDB.IxCol<Artifact, string>(tableName, "artifact_id");
        }
    }
}
