// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SessionRobotResultsHandle : RemoteTableHandle<EventContext, RobotResult>
        {
            public override string RemoteTableName => "session_robot_results";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(RobotResult row) => row.Id;

                public IdUniqueIndex(SessionRobotResultsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal SessionRobotResultsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(RobotResult row) => row.Id;
        }

        public readonly SessionRobotResultsHandle SessionRobotResults;
    }

    public sealed class SessionRobotResultsCols
    {
        public global::SpacetimeDB.Col<RobotResult, ulong> Id { get; }
        public global::SpacetimeDB.Col<RobotResult, string> SessionId { get; }
        public global::SpacetimeDB.Col<RobotResult, string> AttemptId { get; }
        public global::SpacetimeDB.Col<RobotResult, string> StepId { get; }
        public global::SpacetimeDB.Col<RobotResult, bool> Success { get; }
        public global::SpacetimeDB.Col<RobotResult, double> PathErrorMm { get; }
        public global::SpacetimeDB.Col<RobotResult, double> PolicySuccessRate { get; }
        public global::SpacetimeDB.Col<RobotResult, uint> DemosHuman { get; }
        public global::SpacetimeDB.Col<RobotResult, uint> DemosSynthetic { get; }
        public global::SpacetimeDB.Col<RobotResult, string> VideoUrl { get; }
        public global::SpacetimeDB.Col<RobotResult, SpacetimeDB.Timestamp> At { get; }

        public SessionRobotResultsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<RobotResult, ulong>(tableName, "id");
            SessionId = new global::SpacetimeDB.Col<RobotResult, string>(tableName, "session_id");
            AttemptId = new global::SpacetimeDB.Col<RobotResult, string>(tableName, "attempt_id");
            StepId = new global::SpacetimeDB.Col<RobotResult, string>(tableName, "step_id");
            Success = new global::SpacetimeDB.Col<RobotResult, bool>(tableName, "success");
            PathErrorMm = new global::SpacetimeDB.Col<RobotResult, double>(tableName, "path_error_mm");
            PolicySuccessRate = new global::SpacetimeDB.Col<RobotResult, double>(tableName, "policy_success_rate");
            DemosHuman = new global::SpacetimeDB.Col<RobotResult, uint>(tableName, "demos_human");
            DemosSynthetic = new global::SpacetimeDB.Col<RobotResult, uint>(tableName, "demos_synthetic");
            VideoUrl = new global::SpacetimeDB.Col<RobotResult, string>(tableName, "video_url");
            At = new global::SpacetimeDB.Col<RobotResult, SpacetimeDB.Timestamp>(tableName, "at");
        }
    }

    public sealed class SessionRobotResultsIxCols
    {
        public global::SpacetimeDB.IxCol<RobotResult, ulong> Id { get; }

        public SessionRobotResultsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<RobotResult, ulong>(tableName, "id");
        }
    }
}
