using System;
using Scalpal.Brand;
using Scalpal.Exercises.Coach;
using Scalpal.Instruments;
using UnityEngine.XR;
using UnityEditor;
using UnityEngine;

namespace Scalpal.Quest.Editor
{
    public static class NativePatientMonitorValidation
    {
        static int checks;
        const string Sid="synthetic-monitor-session",Patient="synthetic-monitor-patient",Procedure="open_appendectomy",Case="synthetic-monitor-case";
        // Exact JSON generated by the committed service PatientCondition (8d2bb9b),
        // same synthetic inputs as test/patient-condition.test.ts. No Unity physiology.
        const string Baseline="{\"vitals\":{\"hr\":70,\"rr\":14,\"sys\":120,\"dia\":80,\"hemorrhageClass\":1,\"bloodLossPct\":0,\"baseline\":{\"hr\":70,\"rr\":14,\"source\":\"chart\"},\"label\":\"HR 70 \u00b7 simulated from baseline 70 (chart)\",\"spo2\":98,\"simulated\":true,\"scale\":8},\"baselineSource\":\"chart\",\"weightKg\":60,\"rawBloodLossMl\":0,\"regions\":[],\"outcome\":{\"result\":\"in_progress\",\"cause\":\"\",\"at\":\"\"}}";
        const string Blood="{\"vitals\":{\"hr\":118,\"rr\":29,\"sys\":115,\"dia\":85,\"hemorrhageClass\":2,\"bloodLossPct\":28.6,\"baseline\":{\"hr\":70,\"rr\":14,\"source\":\"chart\"},\"label\":\"HR 118 \u00b7 simulated from baseline 70 (chart)\",\"spo2\":98,\"simulated\":true,\"scale\":8},\"baselineSource\":\"chart\",\"weightKg\":60,\"rawBloodLossMl\":150,\"regions\":[],\"outcome\":{\"result\":\"in_progress\",\"cause\":\"\",\"at\":\"\"}}";
        const string Death="{\"vitals\":{\"hr\":0,\"rr\":0,\"sys\":0,\"dia\":0,\"hemorrhageClass\":4,\"bloodLossPct\":57.1,\"baseline\":{\"hr\":70,\"rr\":14,\"source\":\"chart\"},\"label\":\"Asystole (simulated)\",\"spo2\":0,\"simulated\":true,\"scale\":8},\"baselineSource\":\"chart\",\"weightKg\":60,\"rawBloodLossMl\":300,\"regions\":[],\"outcome\":{\"result\":\"died\",\"cause\":\"hemorrhage (57% of blood volume, simulated)\",\"at\":\"1970-01-01T00:00:00.000Z\"}}";
        const string UnknownSpo2="{\"vitals\":{\"hr\":72,\"rr\":14,\"sys\":118,\"dia\":76,\"hemorrhageClass\":1,\"bloodLossPct\":0,\"baseline\":{\"hr\":72,\"rr\":14,\"source\":\"authored\"},\"label\":\"HR 72 \u00b7 simulated from baseline 72 (authored)\",\"spo2\":-1,\"simulated\":true,\"scale\":8},\"baselineSource\":\"authored\",\"weightKg\":70,\"rawBloodLossMl\":0,\"regions\":[],\"outcome\":{\"result\":\"in_progress\",\"cause\":\"\",\"at\":\"\"}}";
        const string AliveClassFour="{\"vitals\":{\"hr\":148,\"rr\":38,\"sys\":77,\"dia\":53,\"hemorrhageClass\":4,\"bloodLossPct\":45.7,\"baseline\":{\"hr\":70,\"rr\":14,\"source\":\"chart\"},\"label\":\"HR 148 \u00b7 simulated from baseline 70 (chart)\",\"spo2\":95,\"simulated\":true,\"scale\":8},\"baselineSource\":\"chart\",\"weightKg\":60,\"rawBloodLossMl\":240,\"regions\":[],\"outcome\":{\"result\":\"in_progress\",\"cause\":\"\",\"at\":\"\"}}";
        static void Require(bool valid,string message)
        {checks++;if(!valid)throw new InvalidOperationException("Patient monitor: "+message);}
        static string Feed(string condition,int version=1,string mode="virtual",string sid=Sid)=>
            "{\"latestSeq\":0,\"alerts\":[],\"snapshot\":{\"sessionId\":\""+sid+"\",\"patientId\":\""+Patient+"\",\"procedureId\":\""+Procedure+"\",\"caseId\":\""+Case+
            "\",\"mode\":\""+mode+"\",\"version\":"+version+",\"status\":\"active\",\"condition\":"+condition+"}}";
        static CoachSnapshotState Decode(string condition,int version=1,string mode="virtual",string sid=Sid)
        {Require(NativePatientMonitor.TryDecodeFeed(Feed(condition,version,mode,sid),sid,out var feed),"actual service fixture decodes and validates");return feed.snapshot;}
        static void Tick(NativePatientMonitor m,CoachSnapshotState snapshot,double now,bool ready=true,string sid=Sid,string mode="virtual")=>
            m.TickMonitor(snapshot,sid,Patient,Procedure,Case,mode,ready,now);
        [MenuItem("Scalpal/Quest/Validate Patient Monitor")]
        public static void Run()
        {
            checks=0;
            Require(!NativePatientMonitor.TryDecodeFeed("not json",Sid,out _)&&!NativePatientMonitor.TryDecodeFeed("{}",Sid,out _)&&
                !NativePatientMonitor.TryDecodeFeed(Feed("{}"),Sid,out _),"malformed/missing condition JSON refuses");
            var baseline=Decode(Baseline);
            Require(baseline.condition.vitals.hr==70&&baseline.condition.vitals.sys==120&&baseline.condition.vitals.dia==80&&baseline.condition.vitals.rr==14&&
                baseline.condition.vitals.spo2==98&&baseline.condition.baselineSource=="chart"&&baseline.condition.vitals.simulated&&baseline.condition.vitals.scale==8,
                "all baseline DTO values match the real TypeScript serialization");
            var blood=Decode(Blood,2);
            Require(blood.condition.vitals.hr==118&&blood.condition.vitals.rr==29&&blood.condition.vitals.sys==115&&blood.condition.vitals.dia==85&&
                blood.condition.vitals.hemorrhageClass==2&&Mathf.Abs(blood.condition.vitals.bloodLossPct-28.6f)<1e-6f&&blood.condition.rawBloodLossMl==150,
                "accelerated hemorrhage DTO values match the service, without a local model");
            var originalInput=XRInput.Source;var input=new MonitorInput();XRInput.Source=input;
            var root=new GameObject("SyntheticMonitorValidation");var viewer=new GameObject("SyntheticMonitorViewer");
            try
            {
                var monitor=root.AddComponent<NativePatientMonitor>();
                Require(monitor.HeadsetInputReady,"production input gate observes valid synthetic head/display/floor/focus");
                input.focus=false;Require(!monitor.HeadsetInputReady,"actual XR focus loss refuses display input");input.focus=true;
                input.head=false;Require(!monitor.HeadsetInputReady,"actual XR head tracking loss refuses display input");input.head=true;
                input.display=false;Require(!monitor.HeadsetInputReady,"stopped actual XR display refuses monitor input");input.display=true;
                input.floor=false;Require(!monitor.HeadsetInputReady,"unknown tracking frame refuses monitor input");input.floor=true;
                Tick(monitor,baseline,0);
                Require(monitor.HasFreshSample&&!monitor.Flatline&&monitor.DisplayText.Contains("HR 70 bpm")&&monitor.DisplayText.Contains("BP 120/80")&&
                    monitor.DisplayText.Contains("SpO2 98%")&&monitor.DisplayText.Contains("Baseline: chart")&&monitor.DisplayText.Contains("Not real volunteer vitals"),"visible baseline is correctly labeled simulated");
                monitor.EnsureView(viewer.transform);
                Require(monitor.ViewRoot&&monitor.ViewRoot.GetComponentsInChildren<TMPro.TextMeshPro>().Length==2,"runtime monitor creates branded world text");
                Readable(monitor,viewer.transform.position);
                Tick(monitor,blood,1);
                Require(monitor.DisplayText.Contains("HR 118 bpm")&&monitor.DisplayText.Contains("Raw loss 150 ml")&&monitor.DisplayText.Contains("demo x8")&&monitor.DisplayText.Contains("Class 2"),
                    "display distinguishes raw blood loss and demo acceleration");
                Readable(monitor,viewer.transform.position);
                Tick(monitor,Decode(AliveClassFour,3),2);
                Require(monitor.HasFreshSample&&!monitor.Flatline&&monitor.DisplayText.Contains("Class 4")&&!monitor.DisplayText.Contains("Outcome: died"),"high hemorrhage class never independently declares death");
                Tick(monitor,Decode(Death,4),3);
                Require(monitor.HasFreshSample&&monitor.Flatline&&monitor.DisplayText.Contains("HR 0 bpm")&&monitor.DisplayText.Contains("Outcome: died (simulated)")&&monitor.DisplayText.Contains("hemorrhage"),
                    "flatline appears only from actual validated server death outcome");
                var line=monitor.ViewRoot.GetComponentInChildren<LineRenderer>();
                Require(line&&line.enabled&&line.positionCount==2&&line.GetPosition(0).y==line.GetPosition(1).y,"actual server outcome enables the flatline visual");
                Readable(monitor,viewer.transform.position);
                Tick(monitor,Decode(Blood,3),3.5);
                Require(!monitor.HasFreshSample&&!monitor.Flatline&&!line.enabled&&!monitor.DisplayText.Contains("HR 118"),"old version cannot replace the current outcome or leave a misleading flatline");
                Tick(monitor,Decode(UnknownSpo2,5),4);
                Require(monitor.HasFreshSample&&monitor.DisplayText.Contains("SpO2 unavailable")&&!monitor.DisplayText.Contains("SpO2 0%"),"service -1 SpO2 sentinel displays unavailable");
                var repeated=Decode(UnknownSpo2,6);Tick(monitor,repeated,5);Tick(monitor,repeated,5+NativePatientMonitor.FreshSeconds+.01);
                Require(!monitor.HasFreshSample&&!monitor.DisplayText.Contains("HR 72 bpm"),"re-reading cached relay object cannot renew freshness");
                Tick(monitor,Decode(UnknownSpo2,6),9);
                Require(monitor.HasFreshSample,"fresh same-version poll is valid when server state is unchanged");
                Tick(monitor,Decode(Baseline,7),10,false);
                Require(!monitor.HasFreshSample&&!monitor.Flatline&&!monitor.DisplayText.Contains("HR 70 bpm"),"tracking/fit/focus/lifecycle pause removes numeric readings");
                var resumed=Decode(Baseline,8);Tick(monitor,resumed,11,false);Tick(monitor,resumed,11.1);
                Require(!monitor.HasFreshSample,"resume does not reuse the last paused sample");
                Tick(monitor,Decode(Baseline,8),11.2);
                Require(monitor.HasFreshSample,"a newly received resumed poll restores the monitor");
                Tick(monitor,Decode(Baseline,9,"virtual","older-session"),12);
                Require(!monitor.HasFreshSample,"wrong session is refused even at a newer version");
                var mismatch=Decode(Baseline,10);mismatch.patientId="other-patient";Tick(monitor,mismatch,13);
                Require(!monitor.HasFreshSample,"wrong patient is refused");
                Tick(monitor,Decode(Baseline,11,"mixed_reality"),14,mode:"virtual");
                Require(!monitor.HasFreshSample,"presentation mode mismatch is refused");
                Tick(monitor,Decode(Blood,1,"mixed_reality","new-session"),15,sid:"new-session",mode:"mixed_reality");
                Require(monitor.HasFreshSample&&monitor.DisplayText.Contains("Class 2")&&monitor.DisplayText.Contains("Not real volunteer vitals"),"new matched AR session resets old version floor and retains simulation attribution");
                Readable(monitor,viewer.transform.position);
                monitor.ResetMonitor();
                Require(!monitor.HasFreshSample&&!monitor.Flatline&&!monitor.DisplayText.Contains("HR 118"),"explicit retry/reset clears sample and terminal visualization");
                var ended=Decode(Baseline,12);ended.condition.outcome.result="ended";
                ended.condition.outcome.cause="ended before the case goals were reached";
                ended.condition.outcome.at="1970-01-01T00:00:00.000Z";
                Tick(monitor,ended,16);
                Require(monitor.HasFreshSample&&!monitor.Flatline&&monitor.DisplayText.Contains("Outcome: ended"),"upstream early ending is displayed without fabricating completion or death");
                Require(!line.enabled&&monitor.DisplayText.Contains("HR 70 bpm")&&!monitor.DisplayText.Contains("Cause:")&&!monitor.DisplayText.Contains("(simulated)\n"),
                    "an early ending keeps the frozen vitals and never shows the death flatline or cause");
                var endedAsystole=Decode(Death).condition;endedAsystole.outcome.result="ended";
                Require(!NativePatientMonitor.ValidCondition(endedAsystole),"asystole is accepted only with a death outcome, never with an early ending");
                var nan=Decode(Baseline).condition;nan.vitals.hr=float.NaN;
                Require(!NativePatientMonitor.ValidCondition(nan),"nonfinite server vitals refuse");
                var unmarked=Decode(Baseline).condition;unmarked.vitals.simulated=false;
                Require(!NativePatientMonitor.ValidCondition(unmarked),"unmarked real-vitals interpretation refuses");
            }
            finally{UnityEngine.Object.DestroyImmediate(root);UnityEngine.Object.DestroyImmediate(viewer);XRInput.Source=originalInput;}
            Debug.Log("SCALPAL_PATIENT_MONITOR_VALIDATION_OK checks="+checks+" actualServiceFixtureJson=true brandedTextFloor=true synthetic=true hardware=false");
        }
        sealed class MonitorInput:IXRInputSource
        {
            public bool head=true,display=true,floor=true,focus=true;
            public bool DisplayRunning=>display;
            public bool FloorTracking=>floor;
            public bool HasFocus=>focus;
            public bool TryPose(XRNode node,out Pose pose){pose=new Pose(Vector3.zero,Quaternion.identity);return node!=XRNode.Head||head;}
            public float Grip(XRNode node)=>0;
            public float Trigger(XRNode node)=>0;
            public bool Button(XRNode node,XRInputButton button)=>false;
        }
        static void Readable(NativePatientMonitor monitor,Vector3 viewer)
        {
            var measures=ScalpalBrandLayout.Measure(monitor.ViewRoot,viewer,true);
            Require(measures.Count==2,"both actual monitor text surfaces are measured");
            foreach(var measure in measures)Require(measure.Passes,"monitor visible line extent meets its brand readability floor: "+measure.fit.name+" "+measure.mmAt1m);
        }
    }
}
