using System;
using System.Linq;
using Scalpal.Brand;
using Scalpal.Exercises.Coach;
using Scalpal.Instruments;
using UnityEngine.XR;
using UnityEditor;
using UnityEngine;

namespace Scalpal.Quest.Editor
{
    public static class NativePatientMonitorValidation
    {
        static int checks;
        const string Sid="synthetic-monitor-session",Patient="synthetic-monitor-patient",Procedure="open_appendectomy",Case="synthetic-monitor-case";
        // Exact JSON generated by the committed service PatientCondition (8d2bb9b),
        // same synthetic inputs as test/patient-condition.test.ts. No Unity physiology.
        const string Baseline="{\"vitals\":{\"hr\":70,\"rr\":14,\"sys\":120,\"dia\":80,\"hemorrhageClass\":1,\"bloodLossPct\":0,\"baseline\":{\"hr\":70,\"rr\":14,\"source\":\"chart\"},\"label\":\"HR 70 \u00b7 simulated from baseline 70 (chart)\",\"spo2\":98,\"simulated\":true,\"scale\":8},\"baselineSource\":\"chart\",\"weightKg\":60,\"rawBloodLossMl\":0,\"regions\":[],\"outcome\":{\"result\":\"in_progress\",\"cause\":\"\",\"at\":\"\"}}";
        const string Blood="{\"vitals\":{\"hr\":118,\"rr\":29,\"sys\":115,\"dia\":85,\"hemorrhageClass\":2,\"bloodLossPct\":28.6,\"baseline\":{\"hr\":70,\"rr\":14,\"source\":\"chart\"},\"label\":\"HR 118 \u00b7 simulated from baseline 70 (chart)\",\"spo2\":98,\"simulated\":true,\"scale\":8},\"baselineSource\":\"chart\",\"weightKg\":60,\"rawBloodLossMl\":150,\"regions\":[],\"outcome\":{\"result\":\"in_progress\",\"cause\":\"\",\"at\":\"\"}}";
        const string Death="{\"vitals\":{\"hr\":0,\"rr\":0,\"sys\":0,\"dia\":0,\"hemorrhageClass\":4,\"bloodLossPct\":57.1,\"baseline\":{\"hr\":70,\"rr\":14,\"source\":\"chart\"},\"label\":\"Asystole (simulated)\",\"spo2\":0,\"simulated\":true,\"scale\":8},\"baselineSource\":\"chart\",\"weightKg\":60,\"rawBloodLossMl\":300,\"regions\":[],\"outcome\":{\"result\":\"died\",\"cause\":\"hemorrhage (57% of blood volume, simulated)\",\"at\":\"1970-01-01T00:00:00.000Z\"}}";
        const string UnknownSpo2="{\"vitals\":{\"hr\":72,\"rr\":14,\"sys\":118,\"dia\":76,\"hemorrhageClass\":1,\"bloodLossPct\":0,\"baseline\":{\"hr\":72,\"rr\":14,\"source\":\"authored\"},\"label\":\"HR 72 \u00b7 simulated from baseline 72 (authored)\",\"spo2\":-1,\"simulated\":true,\"scale\":8},\"baselineSource\":\"authored\",\"weightKg\":70,\"rawBloodLossMl\":0,\"regions\":[],\"outcome\":{\"result\":\"in_progress\",\"cause\":\"\",\"at\":\"\"}}";
        const string AliveClassFour="{\"vitals\":{\"hr\":148,\"rr\":38,\"sys\":77,\"dia\":53,\"hemorrhageClass\":4,\"bloodLossPct\":45.7,\"baseline\":{\"hr\":70,\"rr\":14,\"source\":\"chart\"},\"label\":\"HR 148 \u00b7 simulated from baseline 70 (chart)\",\"spo2\":95,\"simulated\":true,\"scale\":8},\"baselineSource\":\"chart\",\"weightKg\":60,\"rawBloodLossMl\":240,\"regions\":[],\"outcome\":{\"result\":\"in_progress\",\"cause\":\"\",\"at\":\"\"}}";
        static void Require(bool valid,string message)
        {checks++;if(!valid)throw new InvalidOperationException("Patient monitor: "+message);}
        static string Feed(string condition,int version=1,string mode="virtual",string sid=Sid)=>
            "{\"latestSeq\":0,\"alerts\":[],\"snapshot\":{\"sessionId\":\""+sid+"\",\"patientId\":\""+Patient+"\",\"procedureId\":\""+Procedure+"\",\"caseId\":\""+Case+
            "\",\"mode\":\""+mode+"\",\"version\":"+version+",\"status\":\"active\",\"condition\":"+condition+"}}";
        static CoachSnapshotState Decode(string condition,int version=1,string mode="virtual",string sid=Sid)
        {Require(NativePatientMonitor.TryDecodeFeed(Feed(condition,version,mode,sid),sid,out var feed),"actual service fixture decodes and validates");return feed.snapshot;}
        static void Tick(NativePatientMonitor m,CoachSnapshotState snapshot,double now,bool ready=true,string sid=Sid,string mode="virtual")=>
            m.TickMonitor(snapshot,sid,Patient,Procedure,Case,mode,ready,now);
        [MenuItem("Scalpal/Quest/Validate Patient Monitor")]
        public static void Run()
        {
            checks=0;
            Require(!NativePatientMonitor.TryDecodeFeed("not json",Sid,out _)&&!NativePatientMonitor.TryDecodeFeed("{}",Sid,out _)&&
                !NativePatientMonitor.TryDecodeFeed(Feed("{}"),Sid,out _),"malformed/missing condition JSON refuses");
            var baseline=Decode(Baseline);
            Require(baseline.condition.vitals.hr==70&&baseline.condition.vitals.sys==120&&baseline.condition.vitals.dia==80&&baseline.condition.vitals.rr==14&&
                baseline.condition.vitals.spo2==98&&baseline.condition.baselineSource=="chart"&&baseline.condition.vitals.simulated&&baseline.condition.vitals.scale==8,
                "all baseline DTO values match the real TypeScript serialization");
            var blood=Decode(Blood,2);
            Require(blood.condition.vitals.hr==118&&blood.condition.vitals.rr==29&&blood.condition.vitals.sys==115&&blood.condition.vitals.dia==85&&
                blood.condition.vitals.hemorrhageClass==2&&Mathf.Abs(blood.condition.vitals.bloodLossPct-28.6f)<1e-6f&&blood.condition.rawBloodLossMl==150,
                "accelerated hemorrhage DTO values match the service, without a local model");
            var originalInput=XRInput.Source;var input=new MonitorInput();XRInput.Source=input;
            var root=new GameObject("SyntheticMonitorValidation");var viewer=new GameObject("SyntheticMonitorViewer");
            try
            {
                var monitor=root.AddComponent<NativePatientMonitor>();
                Require(monitor.HeadsetInputReady,"production input gate observes valid synthetic head/display/floor/focus");
                input.focus=false;Require(!monitor.HeadsetInputReady,"actual XR focus loss refuses display input");input.focus=true;
                input.head=false;Require(!monitor.HeadsetInputReady,"actual XR head tracking loss refuses display input");input.head=true;
                input.display=false;Require(!monitor.HeadsetInputReady,"stopped actual XR display refuses monitor input");input.display=true;
                input.floor=false;Require(!monitor.HeadsetInputReady,"unknown tracking frame refuses monitor input");input.floor=true;
                Tick(monitor,baseline,0);
                Require(monitor.HasFreshSample&&!monitor.Flatline&&monitor.HeartRateValue=="HR 70"&&monitor.PressureValue=="BP 120/80"&&monitor.OxygenValue=="SpO2 98%"
                    &&monitor.RespirationValue=="RR 14"&&monitor.StateValue=="Stable"&&monitor.SourceValue=="Simulated from chart baseline","baseline sample fills every live field and is labeled simulated");
                var frame=new GameObject("SyntheticPatientFrame").transform;frame.SetParent(root.transform,false);frame.position=new Vector3(0,1.05f,0);
                viewer.transform.position=frame.TransformPoint(new Vector3(-.65f,.55f,0));
                monitor.EnsureView(viewer.transform);monitor.Place(frame,0);
                var view=monitor.ViewRoot;
                Require(view,"runtime creates the bedside monitor");
                foreach(var part in new[]{"MonitorHousing","MonitorScreen","MonitorMount","MonitorStandPole","MonitorStandBase"})
                {
                    var renderer=view.Find(part)?view.Find(part).GetComponent<MeshRenderer>():null;
                    Require(renderer&&renderer.enabled&&renderer.sharedMaterial&&!renderer.GetComponent<Collider>(),"monitor body part "+part+" is a rendered mesh with no contact collider");
                }
                var local=frame.InverseTransformPoint(view.position);
                Require(local.z>.6f&&local.x>.4f&&view.position.y>frame.position.y+.3f,"monitor stands at the head of the table on the patient's left, above the table");
                Require(Vector3.Dot(-view.forward,(viewer.transform.position-view.position).normalized)>.9f,"the screen faces the learner at the patient's right side");
                var stand=view.Find("MonitorStandBase").GetComponent<Renderer>().bounds;
                Require(Mathf.Abs(stand.min.y)<.01f,"the stand reaches the floor");
                var texts=view.GetComponentsInChildren<TMPro.TextMeshPro>(true);
                Require(texts.Length==7&&texts.All(text=>text.font==ScalpalBrand.Active.label||text.font==ScalpalBrand.Active.body),"monitor screen uses only the brand Geist Mono faces");
                TMPro.TextMeshPro Field(string name)=>texts.Single(text=>text.name==name);
                Require(Field("MonitorHeartRate").text=="HR 70"&&Field("MonitorPressure").text=="BP 120/80"&&Field("MonitorOxygen").text=="SpO2 98%"
                    &&Field("MonitorRespiration").text=="RR 14"&&Field("MonitorState").text=="Stable"&&Field("MonitorSource").text=="Simulated from chart baseline","screen draws the live snapshot fields");
                Require(Field("MonitorHeartRate").color==ScalpalBrand.SurgicalGreen&&monitor.Trace.startColor==ScalpalBrand.SurgicalGreen,"heart rate and ECG trace are surgical green");
                Readable(monitor,viewer.transform.position);
                Require(monitor.Trace.enabled&&monitor.Trace.positionCount==NativePatientMonitor.TracePoints,"a fresh sample shows the ECG trace");
                monitor.DrawTrace(100);Require(Beats(monitor.Trace)>=4&&Beats(monitor.Trace)<=6,"ECG trace beats at 70 bpm over four seconds: "+Beats(monitor.Trace));
                Tick(monitor,blood,1);
                Require(Field("MonitorHeartRate").text=="HR 118"&&Field("MonitorPressure").text=="BP 115/85"&&Field("MonitorRespiration").text=="RR 29"&&Field("MonitorState").text=="Bleeding 29%",
                    "a newer snapshot updates the screen; blood loss reads plainly instead of as a class number");
                Require(!monitor.DisplayText.Contains("Raw loss")&&!monitor.DisplayText.Contains("demo x")&&!monitor.DisplayText.Contains("Class"),"service internals stay off the learner's monitor");
                monitor.DrawTrace(100);Require(Beats(monitor.Trace)>=7&&Beats(monitor.Trace)<=9,"ECG trace follows the new heart rate of 118 bpm: "+Beats(monitor.Trace));
                Readable(monitor,viewer.transform.position);
                Tick(monitor,Decode(AliveClassFour,3),2);
                Require(monitor.HasFreshSample&&!monitor.Flatline&&monitor.StateValue=="Bleeding 46%"&&monitor.Outcome=="in_progress","high hemorrhage class never independently declares death");
                Tick(monitor,Decode(Death,4),3);
                Require(monitor.HasFreshSample&&monitor.Flatline&&Field("MonitorHeartRate").text=="HR 0"&&Field("MonitorState").text=="Asystole"&&monitor.Outcome=="died",
                    "asystole appears only from actual validated server death outcome");
                monitor.DrawTrace(100);Require(monitor.Trace.enabled&&Beats(monitor.Trace)==0&&Flat(monitor.Trace),"death draws a flat ECG line");
                Tick(monitor,null,3+NativePatientMonitor.FreshSeconds+1,false);
                Require(monitor.Holding&&monitor.Flatline&&Field("MonitorState").text=="Asystole","death stays on the monitor after practice stops and polling ends");
                Readable(monitor,viewer.transform.position);
                Tick(monitor,Decode(Blood,3),3.5);
                Require(!monitor.HasFreshSample&&!monitor.Flatline&&!monitor.Trace.enabled&&!monitor.DisplayText.Contains("HR 118")&&Field("MonitorState").text=="No signal","old version cannot replace the current outcome or leave a misleading flatline");
                Require(Field("MonitorHeartRate").text=="HR --"&&texts.All(text=>!text.text.Contains("coach")&&!text.text.Contains("Paused")&&!text.text.Contains("Rejected")),
                    "no signal shows dashes, never the diagnostic reason");
                Tick(monitor,Decode(UnknownSpo2,5),4);
                Require(monitor.HasFreshSample&&monitor.OxygenValue=="SpO2 --"&&!monitor.DisplayText.Contains("SpO2 0%"),"service -1 SpO2 sentinel displays as unavailable");
                var repeated=Decode(UnknownSpo2,6);Tick(monitor,repeated,5);Tick(monitor,repeated,5+NativePatientMonitor.FreshSeconds+.01);
                Require(!monitor.HasFreshSample&&!monitor.DisplayText.Contains("HR 72"),"re-reading cached relay object cannot renew freshness");
                Tick(monitor,Decode(UnknownSpo2,6),9);
                Require(monitor.HasFreshSample,"fresh same-version poll is valid when server state is unchanged");
                Tick(monitor,Decode(Baseline,7),10,false);
                Require(!monitor.HasFreshSample&&!monitor.Flatline&&!monitor.DisplayText.Contains("HR 70"),"tracking/fit/focus/lifecycle pause removes numeric readings of a live case");
                var resumed=Decode(Baseline,8);Tick(monitor,resumed,11,false);Tick(monitor,resumed,11.1);
                Require(!monitor.HasFreshSample,"resume does not reuse the last paused sample");
                Tick(monitor,Decode(Baseline,8),11.2);
                Require(monitor.HasFreshSample,"a newly received resumed poll restores the monitor");
                Tick(monitor,Decode(Baseline,9,"virtual","older-session"),12);
                Require(!monitor.HasFreshSample,"wrong session is refused even at a newer version");
                var mismatch=Decode(Baseline,10);mismatch.patientId="other-patient";Tick(monitor,mismatch,13);
                Require(!monitor.HasFreshSample,"wrong patient is refused");
                Tick(monitor,Decode(Baseline,11,"mixed_reality"),14,mode:"virtual");
                Require(!monitor.HasFreshSample,"presentation mode mismatch is refused");
                Tick(monitor,Decode(Blood,1,"mixed_reality","new-session"),15,sid:"new-session",mode:"mixed_reality");
                Require(monitor.HasFreshSample&&monitor.HeartRateValue=="HR 118"&&monitor.SourceValue.StartsWith("Simulated",StringComparison.Ordinal),"new matched AR session resets old version floor and retains simulation attribution");
                Readable(monitor,viewer.transform.position);
                monitor.ResetMonitor();
                Require(!monitor.HasFreshSample&&!monitor.Flatline&&!monitor.DisplayText.Contains("HR 118"),"explicit retry/reset clears sample and terminal visualization");
                var ended=Decode(Baseline,12);ended.condition.outcome.result="ended";
                ended.condition.outcome.cause="ended before the case goals were reached";
                ended.condition.outcome.at="1970-01-01T00:00:00.000Z";
                Tick(monitor,ended,16);
                Require(monitor.HasFreshSample&&!monitor.Flatline&&monitor.StateValue=="Case ended"&&monitor.HeartRateValue=="HR 70","upstream early ending is displayed without fabricating completion or death");
                monitor.DrawTrace(16);var still=new Vector3[NativePatientMonitor.TracePoints];monitor.Trace.GetPositions(still);
                monitor.DrawTrace(17.37);var later=new Vector3[NativePatientMonitor.TracePoints];monitor.Trace.GetPositions(later);
                Require(still.SequenceEqual(later)&&Beats(monitor.Trace)>=4,"an early ending freezes calm vitals and the last trace, never the death flatline");
                Tick(monitor,null,30,false);
                Require(monitor.Holding&&monitor.StateValue=="Case ended"&&monitor.HeartRateValue=="HR 70","the ended state stays frozen on screen after polling stops");
                var endedAsystole=Decode(Death).condition;endedAsystole.outcome.result="ended";
                Require(!NativePatientMonitor.ValidCondition(endedAsystole),"asystole is accepted only with a death outcome, never with an early ending");
                var nan=Decode(Baseline).condition;nan.vitals.hr=float.NaN;
                Require(!NativePatientMonitor.ValidCondition(nan),"nonfinite server vitals refuse");
                var unmarked=Decode(Baseline).condition;unmarked.vitals.simulated=false;
                Require(!NativePatientMonitor.ValidCondition(unmarked),"unmarked real-vitals interpretation refuses");
            }
            finally{UnityEngine.Object.DestroyImmediate(root);UnityEngine.Object.DestroyImmediate(viewer);XRInput.Source=originalInput;}
            Debug.Log("SCALPAL_PATIENT_MONITOR_VALIDATION_OK checks="+checks+" actualServiceFixtureJson=true bedsideMonitor=true ecgAtHeartRate=true brandedTextFloor=true synthetic=true hardware=false");
        }
        sealed class MonitorInput:IXRInputSource
        {
            public bool head=true,display=true,floor=true,focus=true;
            public bool DisplayRunning=>display;
            public bool FloorTracking=>floor;
            public bool HasFocus=>focus;
            public bool TryPose(XRNode node,out Pose pose){pose=new Pose(Vector3.zero,Quaternion.identity);return node!=XRNode.Head||head;}
            public float Grip(XRNode node)=>0;
            public float Trigger(XRNode node)=>0;
            public bool Button(XRNode node,XRInputButton button)=>false;
        }
        // R waves: local maxima above half the trace amplitude.
        static int Beats(LineRenderer trace)
        {
            var points=new Vector3[trace.positionCount];trace.GetPositions(points);int beats=0;
            for(int i=1;i<points.Length-1;i++)
                if(points[i].y-NativePatientMonitor.TraceBaseline>NativePatientMonitor.TraceAmplitude*.5f&&points[i].y>=points[i-1].y&&points[i].y>points[i+1].y)beats++;
            return beats;
        }
        static bool Flat(LineRenderer trace)
        {var points=new Vector3[trace.positionCount];trace.GetPositions(points);return points.All(point=>Mathf.Abs(point.y-NativePatientMonitor.TraceBaseline)<1e-6f);}
        static void Readable(NativePatientMonitor monitor,Vector3 viewer)
        {
            ScalpalBrandLayout.SizeForViewer(monitor.ViewRoot,viewer);
            var measures=ScalpalBrandLayout.Measure(monitor.ViewRoot,viewer,true);
            Require(measures.Count==7,"every monitor text surface is measured");
            foreach(var measure in measures)Require(measure.Passes,"monitor visible line extent meets its brand readability floor: "+measure.fit.name+" "+measure.mmAt1m);
        }
    }
}
