// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        internal RemoteReducers(DbConnection conn) : base(conn) { }
        internal event Action<ReducerEventContext, Exception>? InternalOnUnhandledReducerError;
    }

    public sealed partial class RemoteProcedures : RemoteBase
    {
        internal RemoteProcedures(DbConnection conn) : base(conn) { }
    }

    public sealed partial class RemoteTables : RemoteTablesBase
    {
        public RemoteTables(DbConnection conn)
        {
            AddTable(AmService = new(conn));
            AddTable(MyMemberships = new(conn));
            AddTable(MyRtcSignals = new(conn));
            AddTable(MyServiceGrants = new(conn));
            AddTable(MySessions = new(conn));
            AddTable(MyTransferGrants = new(conn));
            AddTable(SessionArtifacts = new(conn));
            AddTable(SessionAttempts = new(conn));
            AddTable(SessionCoachMessages = new(conn));
            AddTable(SessionCoachStatus = new(conn));
            AddTable(SessionCommands = new(conn));
            AddTable(SessionEncounterEvents = new(conn));
            AddTable(SessionEncounters = new(conn));
            AddTable(SessionEvents = new(conn));
            AddTable(SessionExerciseState = new(conn));
            AddTable(SessionInvites = new(conn));
            AddTable(SessionMediaSource = new(conn));
            AddTable(SessionMembers = new(conn));
            AddTable(SessionMotionJobs = new(conn));
            AddTable(SessionPatientCondition = new(conn));
            AddTable(SessionReplayState = new(conn));
            AddTable(SessionRobotResults = new(conn));
            AddTable(SessionSimLogs = new(conn));
        }
    }


        public interface IRemoteDbContext : IDbContext<RemoteTables, RemoteReducers, SubscriptionBuilder, RemoteProcedures> {
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError;
        }

        public sealed class EventContext : IEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;

            /// <summary>
            /// The event that caused this callback to run.
            /// </summary>
            public readonly Event<Reducer> Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal EventContext(DbConnection conn, Event<Reducer> Event)
            {
                this.conn = conn;
                this.Event = Event;
            }
        }

        public sealed class ReducerEventContext : IReducerEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The reducer event that caused this callback to run.
            /// </summary>
            public readonly ReducerEvent<Reducer> Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ReducerEventContext(DbConnection conn, ReducerEvent<Reducer> reducerEvent)
            {
                this.conn = conn;
                Event = reducerEvent;
            }
        }

        public sealed class ErrorContext : IErrorContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The <c>Exception</c> that caused this error callback to be run.
            /// </summary>
            public readonly Exception Event;
            Exception IErrorContext.Event {
                get {
                    return Event;
                }
            }

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ErrorContext(DbConnection conn, Exception error)
            {
                this.conn = conn;
                Event = error;
            }
        }

        public sealed class SubscriptionEventContext : ISubscriptionEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal SubscriptionEventContext(DbConnection conn)
            {
                this.conn = conn;
            }
        }

        public sealed class ProcedureEventContext : IProcedureEventContext, IRemoteDbContext
        {
            private readonly DbConnection conn;
            /// <summary>
            /// The procedure event that caused this callback to run.
            /// </summary>
            public readonly ProcedureEvent Event;

            /// <summary>
            /// Access to tables in the client cache, which stores a read-only replica of the remote database state.
            ///
            /// The returned <c>DbView</c> will have a method to access each table defined by the module.
            /// </summary>
            public RemoteTables Db => conn.Db;
            /// <summary>
            /// Access to reducers defined by the module.
            ///
            /// The returned <c>RemoteReducers</c> will have a method to invoke each reducer defined by the module,
            /// plus methods for adding and removing callbacks on each of those reducers.
            /// </summary>
            public RemoteReducers Reducers => conn.Reducers;
            /// <summary>
            /// Access to procedures defined by the module.
            ///
            /// The returned <c>RemoteProcedures</c> will have a method to invoke each procedure defined by the module,
            /// with a callback for when the procedure completes and returns a value.
            /// </summary>
            public RemoteProcedures Procedures => conn.Procedures;
            /// <summary>
            /// Returns <c>true</c> if the connection is active, i.e. has not yet disconnected.
            /// </summary>
            public bool IsActive => conn.IsActive;
            /// <summary>
            /// Close the connection.
            ///
            /// Throws an error if the connection is already closed.
            /// </summary>
            public void Disconnect() {
                conn.Disconnect();
            }
            /// <summary>
            /// Start building a subscription.
            /// </summary>
            /// <returns>A builder-pattern constructor for subscribing to queries,
            /// causing matching rows to be replicated into the client cache.</returns>
            public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
            /// <summary>
            /// Get the <c>Identity</c> of this connection.
            ///
            /// This method returns null if the connection was constructed anonymously
            /// and we have not yet received our newly-generated <c>Identity</c> from the host.
            /// </summary>
            public Identity? Identity => conn.Identity;
            /// <summary>
            /// Get this connection's <c>ConnectionId</c>.
            /// </summary>
            public ConnectionId ConnectionId => conn.ConnectionId;
            /// <summary>
            /// Register a callback to be called when a reducer with no handler returns an error.
            /// </summary>
            public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError {
                add => Reducers.InternalOnUnhandledReducerError += value;
                remove => Reducers.InternalOnUnhandledReducerError -= value;
            }

            internal ProcedureEventContext(DbConnection conn, ProcedureEvent Event)
            {
                this.conn = conn;
                this.Event = Event;
            }
        }

        /// <summary>
        /// Builder-pattern constructor for subscription queries.
        /// </summary>
        public sealed class SubscriptionBuilder
        {
            private readonly IDbConnection conn;

            private event Action<SubscriptionEventContext>? Applied;
            private event Action<ErrorContext, Exception>? Error;

            /// <summary>
            /// Private API, use <c>conn.SubscriptionBuilder()</c> instead.
            /// </summary>
            public SubscriptionBuilder(IDbConnection conn)
            {
                this.conn = conn;
            }

            /// <summary>
            /// Register a callback to run when the subscription is applied.
            /// </summary>
            public SubscriptionBuilder OnApplied(
                Action<SubscriptionEventContext> callback
            )
            {
                Applied += callback;
                return this;
            }

            /// <summary>
            /// Register a callback to run when the subscription fails.
            ///
            /// Note that this callback may run either when attempting to apply the subscription,
            /// in which case <c>Self::on_applied</c> will never run,
            /// or later during the subscription's lifetime if the module's interface changes,
            /// in which case <c>Self::on_applied</c> may have already run.
            /// </summary>
            public SubscriptionBuilder OnError(
                Action<ErrorContext, Exception> callback
            )
            {
                Error += callback;
                return this;
            }
        
            /// <summary>
            /// Add a typed query to this subscription.
            ///
            /// This is the entry point for building subscriptions without writing SQL by hand.
            /// Once a typed query is added, only typed queries may follow (SQL and typed queries cannot be mixed).
            /// </summary>
            public TypedSubscriptionBuilder AddQuery<TRow>(
                Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build
            )
            {
                var typed = new TypedSubscriptionBuilder(conn, Applied, Error);
                return typed.AddQuery(build);
            }

            /// <summary>
            /// Subscribe to the following SQL queries.
            ///
            /// This method returns immediately, with the data not yet added to the DbConnection.
            /// The provided callbacks will be invoked once the data is returned from the remote server.
            /// Data from all the provided queries will be returned at the same time.
            ///
            /// See the SpacetimeDB SQL docs for more information on SQL syntax:
            /// <a href="https://spacetimedb.com/docs/reference/sql">https://spacetimedb.com/docs/reference/sql</a>
            /// </summary>
            public SubscriptionHandle Subscribe(
                string[] querySqls
            ) => new(conn, Applied, Error, querySqls);

            /// <summary>
            /// Subscribe to all rows from all tables.
            ///
            /// This method is intended as a convenience
            /// for applications where client-side memory use and network bandwidth are not concerns.
            /// Applications where these resources are a constraint
            /// should register more precise queries via <c>Self.Subscribe</c>
            /// in order to replicate only the subset of data which the client needs to function.
            ///
            /// This method should not be combined with <c>Self.Subscribe</c> on the same <c>DbConnection</c>.
            /// A connection may either <c>Self.Subscribe</c> to particular queries,
            /// or <c>Self.SubscribeToAllTables</c>, but not both.
            /// Attempting to call <c>Self.Subscribe</c>
            /// on a <c>DbConnection</c> that has previously used <c>Self.SubscribeToAllTables</c>,
            /// or vice versa, may misbehave in any number of ways,
            /// including dropping subscriptions, corrupting the client cache, or panicking.
            /// </summary>
            public SubscriptionHandle SubscribeToAllTables() =>
                new(conn, Applied, Error, QueryBuilder.AllTablesSqlQueries());
        }

        public sealed class SubscriptionHandle : SubscriptionHandleBase<SubscriptionEventContext, ErrorContext> {
            /// <summary>
            /// Internal API. Construct <c>SubscriptionHandle</c>s using <c>conn.SubscriptionBuilder</c>.
            /// </summary>
            public SubscriptionHandle(
                IDbConnection conn,
                Action<SubscriptionEventContext>? onApplied,
                Action<ErrorContext, Exception>? onError,
                string[] querySqls
            ) : base(conn, onApplied, onError, querySqls)
            { }
        }

    public sealed class QueryBuilder
    {
        public From From { get; } = new();

        internal static string[] AllTablesSqlQueries() => new string[]
        {
            new QueryBuilder().From.AmService().ToSql(),
            new QueryBuilder().From.MyMemberships().ToSql(),
            new QueryBuilder().From.MyRtcSignals().ToSql(),
            new QueryBuilder().From.MyServiceGrants().ToSql(),
            new QueryBuilder().From.MySessions().ToSql(),
            new QueryBuilder().From.MyTransferGrants().ToSql(),
            new QueryBuilder().From.SessionArtifacts().ToSql(),
            new QueryBuilder().From.SessionAttempts().ToSql(),
            new QueryBuilder().From.SessionCoachMessages().ToSql(),
            new QueryBuilder().From.SessionCoachStatus().ToSql(),
            new QueryBuilder().From.SessionCommands().ToSql(),
            new QueryBuilder().From.SessionEncounterEvents().ToSql(),
            new QueryBuilder().From.SessionEncounters().ToSql(),
            new QueryBuilder().From.SessionEvents().ToSql(),
            new QueryBuilder().From.SessionExerciseState().ToSql(),
            new QueryBuilder().From.SessionInvites().ToSql(),
            new QueryBuilder().From.SessionMediaSource().ToSql(),
            new QueryBuilder().From.SessionMembers().ToSql(),
            new QueryBuilder().From.SessionMotionJobs().ToSql(),
            new QueryBuilder().From.SessionPatientCondition().ToSql(),
            new QueryBuilder().From.SessionReplayState().ToSql(),
            new QueryBuilder().From.SessionRobotResults().ToSql(),
            new QueryBuilder().From.SessionSimLogs().ToSql(),
        }
        ;
    }

    public sealed class From
    {
        public global::SpacetimeDB.Table<ServiceFlag, AmServiceCols, AmServiceIxCols> AmService() => new("am_service", new AmServiceCols("am_service"), new AmServiceIxCols("am_service"));
        public global::SpacetimeDB.Table<Membership, MyMembershipsCols, MyMembershipsIxCols> MyMemberships() => new("my_memberships", new MyMembershipsCols("my_memberships"), new MyMembershipsIxCols("my_memberships"));
        public global::SpacetimeDB.Table<RtcSignal, MyRtcSignalsCols, MyRtcSignalsIxCols> MyRtcSignals() => new("my_rtc_signals", new MyRtcSignalsCols("my_rtc_signals"), new MyRtcSignalsIxCols("my_rtc_signals"));
        public global::SpacetimeDB.Table<ServiceGrant, MyServiceGrantsCols, MyServiceGrantsIxCols> MyServiceGrants() => new("my_service_grants", new MyServiceGrantsCols("my_service_grants"), new MyServiceGrantsIxCols("my_service_grants"));
        public global::SpacetimeDB.Table<Session, MySessionsCols, MySessionsIxCols> MySessions() => new("my_sessions", new MySessionsCols("my_sessions"), new MySessionsIxCols("my_sessions"));
        public global::SpacetimeDB.Table<TransferGrant, MyTransferGrantsCols, MyTransferGrantsIxCols> MyTransferGrants() => new("my_transfer_grants", new MyTransferGrantsCols("my_transfer_grants"), new MyTransferGrantsIxCols("my_transfer_grants"));
        public global::SpacetimeDB.Table<Artifact, SessionArtifactsCols, SessionArtifactsIxCols> SessionArtifacts() => new("session_artifacts", new SessionArtifactsCols("session_artifacts"), new SessionArtifactsIxCols("session_artifacts"));
        public global::SpacetimeDB.Table<Attempt, SessionAttemptsCols, SessionAttemptsIxCols> SessionAttempts() => new("session_attempts", new SessionAttemptsCols("session_attempts"), new SessionAttemptsIxCols("session_attempts"));
        public global::SpacetimeDB.Table<CoachMessage, SessionCoachMessagesCols, SessionCoachMessagesIxCols> SessionCoachMessages() => new("session_coach_messages", new SessionCoachMessagesCols("session_coach_messages"), new SessionCoachMessagesIxCols("session_coach_messages"));
        public global::SpacetimeDB.Table<CoachStatus, SessionCoachStatusCols, SessionCoachStatusIxCols> SessionCoachStatus() => new("session_coach_status", new SessionCoachStatusCols("session_coach_status"), new SessionCoachStatusIxCols("session_coach_status"));
        public global::SpacetimeDB.Table<Command, SessionCommandsCols, SessionCommandsIxCols> SessionCommands() => new("session_commands", new SessionCommandsCols("session_commands"), new SessionCommandsIxCols("session_commands"));
        public global::SpacetimeDB.Table<EncounterEvent, SessionEncounterEventsCols, SessionEncounterEventsIxCols> SessionEncounterEvents() => new("session_encounter_events", new SessionEncounterEventsCols("session_encounter_events"), new SessionEncounterEventsIxCols("session_encounter_events"));
        public global::SpacetimeDB.Table<Encounter, SessionEncountersCols, SessionEncountersIxCols> SessionEncounters() => new("session_encounters", new SessionEncountersCols("session_encounters"), new SessionEncountersIxCols("session_encounters"));
        public global::SpacetimeDB.Table<ExerciseEvent, SessionEventsCols, SessionEventsIxCols> SessionEvents() => new("session_events", new SessionEventsCols("session_events"), new SessionEventsIxCols("session_events"));
        public global::SpacetimeDB.Table<ExerciseState, SessionExerciseStateCols, SessionExerciseStateIxCols> SessionExerciseState() => new("session_exercise_state", new SessionExerciseStateCols("session_exercise_state"), new SessionExerciseStateIxCols("session_exercise_state"));
        public global::SpacetimeDB.Table<SessionInvite, SessionInvitesCols, SessionInvitesIxCols> SessionInvites() => new("session_invites", new SessionInvitesCols("session_invites"), new SessionInvitesIxCols("session_invites"));
        public global::SpacetimeDB.Table<MediaSource, SessionMediaSourceCols, SessionMediaSourceIxCols> SessionMediaSource() => new("session_media_source", new SessionMediaSourceCols("session_media_source"), new SessionMediaSourceIxCols("session_media_source"));
        public global::SpacetimeDB.Table<SessionMember, SessionMembersCols, SessionMembersIxCols> SessionMembers() => new("session_members", new SessionMembersCols("session_members"), new SessionMembersIxCols("session_members"));
        public global::SpacetimeDB.Table<MotionJob, SessionMotionJobsCols, SessionMotionJobsIxCols> SessionMotionJobs() => new("session_motion_jobs", new SessionMotionJobsCols("session_motion_jobs"), new SessionMotionJobsIxCols("session_motion_jobs"));
        public global::SpacetimeDB.Table<PatientCondition, SessionPatientConditionCols, SessionPatientConditionIxCols> SessionPatientCondition() => new("session_patient_condition", new SessionPatientConditionCols("session_patient_condition"), new SessionPatientConditionIxCols("session_patient_condition"));
        public global::SpacetimeDB.Table<ReplayState, SessionReplayStateCols, SessionReplayStateIxCols> SessionReplayState() => new("session_replay_state", new SessionReplayStateCols("session_replay_state"), new SessionReplayStateIxCols("session_replay_state"));
        public global::SpacetimeDB.Table<RobotResult, SessionRobotResultsCols, SessionRobotResultsIxCols> SessionRobotResults() => new("session_robot_results", new SessionRobotResultsCols("session_robot_results"), new SessionRobotResultsIxCols("session_robot_results"));
        public global::SpacetimeDB.Table<SimLog, SessionSimLogsCols, SessionSimLogsIxCols> SessionSimLogs() => new("session_sim_logs", new SessionSimLogsCols("session_sim_logs"), new SessionSimLogsIxCols("session_sim_logs"));
    }

    public sealed class TypedSubscriptionBuilder
    {
        private readonly IDbConnection conn;
        private Action<SubscriptionEventContext>? Applied;
        private Action<ErrorContext, Exception>? Error;
        private readonly List<string> querySqls = new();

        internal TypedSubscriptionBuilder(IDbConnection conn, Action<SubscriptionEventContext>? applied, Action<ErrorContext, Exception>? error)
        {
            this.conn = conn;
            Applied = applied;
            Error = error;
        }

        public TypedSubscriptionBuilder OnApplied(Action<SubscriptionEventContext> callback)
        {
            Applied += callback;
            return this;
        }

        public TypedSubscriptionBuilder OnError(Action<ErrorContext, Exception> callback)
        {
            Error += callback;
            return this;
        }

        public TypedSubscriptionBuilder AddQuery<TRow>(Func<QueryBuilder, global::SpacetimeDB.IQuery<TRow>> build)
        {
            var qb = new QueryBuilder();
            querySqls.Add(build(qb).ToSql());
            return this;
        }

        public SubscriptionHandle Subscribe() => new(conn, Applied, Error, querySqls.ToArray());
    }

    public abstract partial class Reducer
    {
        private Reducer() { }
    }

    public abstract partial class Procedure
    {
        private Procedure() { }
    }

    public sealed class DbConnection : DbConnectionBase<DbConnection, RemoteTables, Reducer>
    {
        public override RemoteTables Db { get; }
        public readonly RemoteReducers Reducers;
        public readonly RemoteProcedures Procedures;

        public DbConnection()
        {
            Db = new(this);
            Reducers = new(this);
            Procedures = new(this);
        }

        protected override IEventContext ToEventContext(Event<Reducer> Event) =>
        new EventContext(this, Event);

        protected override IReducerEventContext ToReducerEventContext(ReducerEvent<Reducer> reducerEvent) =>
        new ReducerEventContext(this, reducerEvent);

        protected override ISubscriptionEventContext MakeSubscriptionEventContext() =>
        new SubscriptionEventContext(this);

        protected override IErrorContext ToErrorContext(Exception exception) =>
        new ErrorContext(this, exception);

        protected override IProcedureEventContext ToProcedureEventContext(ProcedureEvent procedureEvent) =>
        new ProcedureEventContext(this, procedureEvent);

        protected override bool Dispatch(IReducerEventContext context, Reducer reducer)
        {
            var eventContext = (ReducerEventContext)context;
            return reducer switch {
                Reducer.AckSignals args => Reducers.InvokeAckSignals(eventContext, args),
                Reducer.AddServiceIdentity args => Reducers.InvokeAddServiceIdentity(eventContext, args),
                Reducer.AppendEncounterEvent args => Reducers.InvokeAppendEncounterEvent(eventContext, args),
                Reducer.AppendExerciseEvent args => Reducers.InvokeAppendExerciseEvent(eventContext, args),
                Reducer.AppendSimLog args => Reducers.InvokeAppendSimLog(eventContext, args),
                Reducer.CancelMotionJob args => Reducers.InvokeCancelMotionJob(eventContext, args),
                Reducer.ClaimMotionJob args => Reducers.InvokeClaimMotionJob(eventContext, args),
                Reducer.CompleteMotionJob args => Reducers.InvokeCompleteMotionJob(eventContext, args),
                Reducer.ConfirmArtifact args => Reducers.InvokeConfirmArtifact(eventContext, args),
                Reducer.CreateSession args => Reducers.InvokeCreateSession(eventContext, args),
                Reducer.DeleteArtifact args => Reducers.InvokeDeleteArtifact(eventContext, args),
                Reducer.DenyGrant args => Reducers.InvokeDenyGrant(eventContext, args),
                Reducer.DenyServiceGrant args => Reducers.InvokeDenyServiceGrant(eventContext, args),
                Reducer.EndPatientCondition args => Reducers.InvokeEndPatientCondition(eventContext, args),
                Reducer.EndSession args => Reducers.InvokeEndSession(eventContext, args),
                Reducer.FailMotionJob args => Reducers.InvokeFailMotionJob(eventContext, args),
                Reducer.HeartbeatMotionJob args => Reducers.InvokeHeartbeatMotionJob(eventContext, args),
                Reducer.IssueGrant args => Reducers.InvokeIssueGrant(eventContext, args),
                Reducer.IssueServiceGrant args => Reducers.InvokeIssueServiceGrant(eventContext, args),
                Reducer.JoinSession args => Reducers.InvokeJoinSession(eventContext, args),
                Reducer.LeaveSession args => Reducers.InvokeLeaveSession(eventContext, args),
                Reducer.MarkUploaded args => Reducers.InvokeMarkUploaded(eventContext, args),
                Reducer.PostCoachMessage args => Reducers.InvokePostCoachMessage(eventContext, args),
                Reducer.PostRobotResult args => Reducers.InvokePostRobotResult(eventContext, args),
                Reducer.PublishExerciseState args => Reducers.InvokePublishExerciseState(eventContext, args),
                Reducer.RegisterJobOutput args => Reducers.InvokeRegisterJobOutput(eventContext, args),
                Reducer.RemoveMember args => Reducers.InvokeRemoveMember(eventContext, args),
                Reducer.RemoveServiceIdentity args => Reducers.InvokeRemoveServiceIdentity(eventContext, args),
                Reducer.ReportBodyState args => Reducers.InvokeReportBodyState(eventContext, args),
                Reducer.ReportInjury args => Reducers.InvokeReportInjury(eventContext, args),
                Reducer.RequestCommand args => Reducers.InvokeRequestCommand(eventContext, args),
                Reducer.RequestDownload args => Reducers.InvokeRequestDownload(eventContext, args),
                Reducer.RequestMotionJob args => Reducers.InvokeRequestMotionJob(eventContext, args),
                Reducer.RequestServiceGrant args => Reducers.InvokeRequestServiceGrant(eventContext, args),
                Reducer.RequestUpload args => Reducers.InvokeRequestUpload(eventContext, args),
                Reducer.ResolveCommand args => Reducers.InvokeResolveCommand(eventContext, args),
                Reducer.RetryMotionJob args => Reducers.InvokeRetryMotionJob(eventContext, args),
                Reducer.RotateInvite args => Reducers.InvokeRotateInvite(eventContext, args),
                Reducer.SendSignal args => Reducers.InvokeSendSignal(eventContext, args),
                Reducer.SetAttemptResult args => Reducers.InvokeSetAttemptResult(eventContext, args),
                Reducer.SetCoachStatus args => Reducers.InvokeSetCoachStatus(eventContext, args),
                Reducer.SetDisplayName args => Reducers.InvokeSetDisplayName(eventContext, args),
                Reducer.SetEncounterPhase args => Reducers.InvokeSetEncounterPhase(eventContext, args),
                Reducer.SetEncounterResult args => Reducers.InvokeSetEncounterResult(eventContext, args),
                Reducer.SetMediaSource args => Reducers.InvokeSetMediaSource(eventContext, args),
                Reducer.SetPatientBaseline args => Reducers.InvokeSetPatientBaseline(eventContext, args),
                Reducer.SetReplayState args => Reducers.InvokeSetReplayState(eventContext, args),
                Reducer.StartAttempt args => Reducers.InvokeStartAttempt(eventContext, args),
                Reducer.StartEncounter args => Reducers.InvokeStartEncounter(eventContext, args),
                Reducer.StartPatientCondition args => Reducers.InvokeStartPatientCondition(eventContext, args),
                _ => throw new ArgumentOutOfRangeException("Reducer", $"Unknown reducer {reducer}")
            };
        }

        public SubscriptionBuilder SubscriptionBuilder() => new(this);
        public event Action<ReducerEventContext, Exception> OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }
    }
}
