// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AckSignalsHandler(ReducerEventContext ctx, System.Collections.Generic.List<ulong> signalIds);
        public event AckSignalsHandler? OnAckSignals;

        public void AckSignals(System.Collections.Generic.List<ulong> signalIds)
        {
            conn.InternalCallReducer(new Reducer.AckSignals(signalIds));
        }

        public bool InvokeAckSignals(ReducerEventContext ctx, Reducer.AckSignals args)
        {
            if (OnAckSignals == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAckSignals(
                ctx,
                args.SignalIds
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AckSignals : Reducer, IReducerArgs
        {
            [DataMember(Name = "signal_ids")]
            public System.Collections.Generic.List<ulong> SignalIds;

            public AckSignals(System.Collections.Generic.List<ulong> SignalIds)
            {
                this.SignalIds = SignalIds;
            }

            public AckSignals()
            {
                this.SignalIds = new();
            }

            string IReducerArgs.ReducerName => "ack_signals";
        }
    }
}
