// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AppendExerciseEventHandler(ReducerEventContext ctx, string sessionId, string attemptId, string kind, string? stepId, string? structureId, string message, double? deviceTimeMs);
        public event AppendExerciseEventHandler? OnAppendExerciseEvent;

        public void AppendExerciseEvent(string sessionId, string attemptId, string kind, string? stepId, string? structureId, string message, double? deviceTimeMs)
        {
            conn.InternalCallReducer(new Reducer.AppendExerciseEvent(sessionId, attemptId, kind, stepId, structureId, message, deviceTimeMs));
        }

        public bool InvokeAppendExerciseEvent(ReducerEventContext ctx, Reducer.AppendExerciseEvent args)
        {
            if (OnAppendExerciseEvent == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAppendExerciseEvent(
                ctx,
                args.SessionId,
                args.AttemptId,
                args.Kind,
                args.StepId,
                args.StructureId,
                args.Message,
                args.DeviceTimeMs
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AppendExerciseEvent : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "attempt_id")]
            public string AttemptId;
            [DataMember(Name = "kind")]
            public string Kind;
            [DataMember(Name = "step_id")]
            public string? StepId;
            [DataMember(Name = "structure_id")]
            public string? StructureId;
            [DataMember(Name = "message")]
            public string Message;
            [DataMember(Name = "device_time_ms")]
            public double? DeviceTimeMs;

            public AppendExerciseEvent(
                string SessionId,
                string AttemptId,
                string Kind,
                string? StepId,
                string? StructureId,
                string Message,
                double? DeviceTimeMs
            )
            {
                this.SessionId = SessionId;
                this.AttemptId = AttemptId;
                this.Kind = Kind;
                this.StepId = StepId;
                this.StructureId = StructureId;
                this.Message = Message;
                this.DeviceTimeMs = DeviceTimeMs;
            }

            public AppendExerciseEvent()
            {
                this.SessionId = "";
                this.AttemptId = "";
                this.Kind = "";
                this.Message = "";
            }

            string IReducerArgs.ReducerName => "append_exercise_event";
        }
    }
}
