// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CompleteMotionJobHandler(ReducerEventContext ctx, string jobId, uint run, System.Collections.Generic.List<SpacetimeDB.Types.VerifiedOutput> outputs, SpacetimeDB.Types.QualitySummary quality);
        public event CompleteMotionJobHandler? OnCompleteMotionJob;

        public void CompleteMotionJob(string jobId, uint run, System.Collections.Generic.List<SpacetimeDB.Types.VerifiedOutput> outputs, SpacetimeDB.Types.QualitySummary quality)
        {
            conn.InternalCallReducer(new Reducer.CompleteMotionJob(jobId, run, outputs, quality));
        }

        public bool InvokeCompleteMotionJob(ReducerEventContext ctx, Reducer.CompleteMotionJob args)
        {
            if (OnCompleteMotionJob == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCompleteMotionJob(
                ctx,
                args.JobId,
                args.Run,
                args.Outputs,
                args.Quality
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CompleteMotionJob : Reducer, IReducerArgs
        {
            [DataMember(Name = "job_id")]
            public string JobId;
            [DataMember(Name = "run")]
            public uint Run;
            [DataMember(Name = "outputs")]
            public System.Collections.Generic.List<VerifiedOutput> Outputs;
            [DataMember(Name = "quality")]
            public QualitySummary Quality;

            public CompleteMotionJob(
                string JobId,
                uint Run,
                System.Collections.Generic.List<VerifiedOutput> Outputs,
                QualitySummary Quality
            )
            {
                this.JobId = JobId;
                this.Run = Run;
                this.Outputs = Outputs;
                this.Quality = Quality;
            }

            public CompleteMotionJob()
            {
                this.JobId = "";
                this.Outputs = new();
                this.Quality = new();
            }

            string IReducerArgs.ReducerName => "complete_motion_job";
        }
    }
}
