// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ConfirmArtifactHandler(ReducerEventContext ctx, string artifactId, bool ok, ulong? verifiedBytes, string? reason);
        public event ConfirmArtifactHandler? OnConfirmArtifact;

        public void ConfirmArtifact(string artifactId, bool ok, ulong? verifiedBytes, string? reason)
        {
            conn.InternalCallReducer(new Reducer.ConfirmArtifact(artifactId, ok, verifiedBytes, reason));
        }

        public bool InvokeConfirmArtifact(ReducerEventContext ctx, Reducer.ConfirmArtifact args)
        {
            if (OnConfirmArtifact == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnConfirmArtifact(
                ctx,
                args.ArtifactId,
                args.Ok,
                args.VerifiedBytes,
                args.Reason
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ConfirmArtifact : Reducer, IReducerArgs
        {
            [DataMember(Name = "artifact_id")]
            public string ArtifactId;
            [DataMember(Name = "ok")]
            public bool Ok;
            [DataMember(Name = "verified_bytes")]
            public ulong? VerifiedBytes;
            [DataMember(Name = "reason")]
            public string? Reason;

            public ConfirmArtifact(
                string ArtifactId,
                bool Ok,
                ulong? VerifiedBytes,
                string? Reason
            )
            {
                this.ArtifactId = ArtifactId;
                this.Ok = Ok;
                this.VerifiedBytes = VerifiedBytes;
                this.Reason = Reason;
            }

            public ConfirmArtifact()
            {
                this.ArtifactId = "";
            }

            string IReducerArgs.ReducerName => "confirm_artifact";
        }
    }
}
