// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateSessionHandler(ReducerEventContext ctx, string sessionId, string label, string exerciseId, string exerciseVersion, string displayName);
        public event CreateSessionHandler? OnCreateSession;

        public void CreateSession(string sessionId, string label, string exerciseId, string exerciseVersion, string displayName)
        {
            conn.InternalCallReducer(new Reducer.CreateSession(sessionId, label, exerciseId, exerciseVersion, displayName));
        }

        public bool InvokeCreateSession(ReducerEventContext ctx, Reducer.CreateSession args)
        {
            if (OnCreateSession == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateSession(
                ctx,
                args.SessionId,
                args.Label,
                args.ExerciseId,
                args.ExerciseVersion,
                args.DisplayName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateSession : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "label")]
            public string Label;
            [DataMember(Name = "exercise_id")]
            public string ExerciseId;
            [DataMember(Name = "exercise_version")]
            public string ExerciseVersion;
            [DataMember(Name = "display_name")]
            public string DisplayName;

            public CreateSession(
                string SessionId,
                string Label,
                string ExerciseId,
                string ExerciseVersion,
                string DisplayName
            )
            {
                this.SessionId = SessionId;
                this.Label = Label;
                this.ExerciseId = ExerciseId;
                this.ExerciseVersion = ExerciseVersion;
                this.DisplayName = DisplayName;
            }

            public CreateSession()
            {
                this.SessionId = "";
                this.Label = "";
                this.ExerciseId = "";
                this.ExerciseVersion = "";
                this.DisplayName = "";
            }

            string IReducerArgs.ReducerName => "create_session";
        }
    }
}
