// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeleteArtifactHandler(ReducerEventContext ctx, string artifactId);
        public event DeleteArtifactHandler? OnDeleteArtifact;

        public void DeleteArtifact(string artifactId)
        {
            conn.InternalCallReducer(new Reducer.DeleteArtifact(artifactId));
        }

        public bool InvokeDeleteArtifact(ReducerEventContext ctx, Reducer.DeleteArtifact args)
        {
            if (OnDeleteArtifact == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeleteArtifact(
                ctx,
                args.ArtifactId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeleteArtifact : Reducer, IReducerArgs
        {
            [DataMember(Name = "artifact_id")]
            public string ArtifactId;

            public DeleteArtifact(string ArtifactId)
            {
                this.ArtifactId = ArtifactId;
            }

            public DeleteArtifact()
            {
                this.ArtifactId = "";
            }

            string IReducerArgs.ReducerName => "delete_artifact";
        }
    }
}
