// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DenyServiceGrantHandler(ReducerEventContext ctx, string grantId, string reason);
        public event DenyServiceGrantHandler? OnDenyServiceGrant;

        public void DenyServiceGrant(string grantId, string reason)
        {
            conn.InternalCallReducer(new Reducer.DenyServiceGrant(grantId, reason));
        }

        public bool InvokeDenyServiceGrant(ReducerEventContext ctx, Reducer.DenyServiceGrant args)
        {
            if (OnDenyServiceGrant == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDenyServiceGrant(
                ctx,
                args.GrantId,
                args.Reason
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DenyServiceGrant : Reducer, IReducerArgs
        {
            [DataMember(Name = "grant_id")]
            public string GrantId;
            [DataMember(Name = "reason")]
            public string Reason;

            public DenyServiceGrant(
                string GrantId,
                string Reason
            )
            {
                this.GrantId = GrantId;
                this.Reason = Reason;
            }

            public DenyServiceGrant()
            {
                this.GrantId = "";
                this.Reason = "";
            }

            string IReducerArgs.ReducerName => "deny_service_grant";
        }
    }
}
