// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EndPatientConditionHandler(ReducerEventContext ctx, string sessionId, string result, string cause);
        public event EndPatientConditionHandler? OnEndPatientCondition;

        public void EndPatientCondition(string sessionId, string result, string cause)
        {
            conn.InternalCallReducer(new Reducer.EndPatientCondition(sessionId, result, cause));
        }

        public bool InvokeEndPatientCondition(ReducerEventContext ctx, Reducer.EndPatientCondition args)
        {
            if (OnEndPatientCondition == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEndPatientCondition(
                ctx,
                args.SessionId,
                args.Result,
                args.Cause
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EndPatientCondition : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "result")]
            public string Result;
            [DataMember(Name = "cause")]
            public string Cause;

            public EndPatientCondition(
                string SessionId,
                string Result,
                string Cause
            )
            {
                this.SessionId = SessionId;
                this.Result = Result;
                this.Cause = Cause;
            }

            public EndPatientCondition()
            {
                this.SessionId = "";
                this.Result = "";
                this.Cause = "";
            }

            string IReducerArgs.ReducerName => "end_patient_condition";
        }
    }
}
