// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EndSessionHandler(ReducerEventContext ctx, string sessionId);
        public event EndSessionHandler? OnEndSession;

        public void EndSession(string sessionId)
        {
            conn.InternalCallReducer(new Reducer.EndSession(sessionId));
        }

        public bool InvokeEndSession(ReducerEventContext ctx, Reducer.EndSession args)
        {
            if (OnEndSession == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEndSession(
                ctx,
                args.SessionId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EndSession : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public string SessionId;

            public EndSession(string SessionId)
            {
                this.SessionId = SessionId;
            }

            public EndSession()
            {
                this.SessionId = "";
            }

            string IReducerArgs.ReducerName => "end_session";
        }
    }
}
