// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void HeartbeatMotionJobHandler(ReducerEventContext ctx, string jobId, uint run, double? progress, string? stage, uint leaseMs);
        public event HeartbeatMotionJobHandler? OnHeartbeatMotionJob;

        public void HeartbeatMotionJob(string jobId, uint run, double? progress, string? stage, uint leaseMs)
        {
            conn.InternalCallReducer(new Reducer.HeartbeatMotionJob(jobId, run, progress, stage, leaseMs));
        }

        public bool InvokeHeartbeatMotionJob(ReducerEventContext ctx, Reducer.HeartbeatMotionJob args)
        {
            if (OnHeartbeatMotionJob == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnHeartbeatMotionJob(
                ctx,
                args.JobId,
                args.Run,
                args.Progress,
                args.Stage,
                args.LeaseMs
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class HeartbeatMotionJob : Reducer, IReducerArgs
        {
            [DataMember(Name = "job_id")]
            public string JobId;
            [DataMember(Name = "run")]
            public uint Run;
            [DataMember(Name = "progress")]
            public double? Progress;
            [DataMember(Name = "stage")]
            public string? Stage;
            [DataMember(Name = "lease_ms")]
            public uint LeaseMs;

            public HeartbeatMotionJob(
                string JobId,
                uint Run,
                double? Progress,
                string? Stage,
                uint LeaseMs
            )
            {
                this.JobId = JobId;
                this.Run = Run;
                this.Progress = Progress;
                this.Stage = Stage;
                this.LeaseMs = LeaseMs;
            }

            public HeartbeatMotionJob()
            {
                this.JobId = "";
            }

            string IReducerArgs.ReducerName => "heartbeat_motion_job";
        }
    }
}
