// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void IssueGrantHandler(ReducerEventContext ctx, string grantId, string url, string method, uint ttlMs);
        public event IssueGrantHandler? OnIssueGrant;

        public void IssueGrant(string grantId, string url, string method, uint ttlMs)
        {
            conn.InternalCallReducer(new Reducer.IssueGrant(grantId, url, method, ttlMs));
        }

        public bool InvokeIssueGrant(ReducerEventContext ctx, Reducer.IssueGrant args)
        {
            if (OnIssueGrant == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnIssueGrant(
                ctx,
                args.GrantId,
                args.Url,
                args.Method,
                args.TtlMs
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class IssueGrant : Reducer, IReducerArgs
        {
            [DataMember(Name = "grant_id")]
            public string GrantId;
            [DataMember(Name = "url")]
            public string Url;
            [DataMember(Name = "method")]
            public string Method;
            [DataMember(Name = "ttl_ms")]
            public uint TtlMs;

            public IssueGrant(
                string GrantId,
                string Url,
                string Method,
                uint TtlMs
            )
            {
                this.GrantId = GrantId;
                this.Url = Url;
                this.Method = Method;
                this.TtlMs = TtlMs;
            }

            public IssueGrant()
            {
                this.GrantId = "";
                this.Url = "";
                this.Method = "";
            }

            string IReducerArgs.ReducerName => "issue_grant";
        }
    }
}
