// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinSessionHandler(ReducerEventContext ctx, string code, string displayName);
        public event JoinSessionHandler? OnJoinSession;

        public void JoinSession(string code, string displayName)
        {
            conn.InternalCallReducer(new Reducer.JoinSession(code, displayName));
        }

        public bool InvokeJoinSession(ReducerEventContext ctx, Reducer.JoinSession args)
        {
            if (OnJoinSession == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnJoinSession(
                ctx,
                args.Code,
                args.DisplayName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class JoinSession : Reducer, IReducerArgs
        {
            [DataMember(Name = "code")]
            public string Code;
            [DataMember(Name = "display_name")]
            public string DisplayName;

            public JoinSession(
                string Code,
                string DisplayName
            )
            {
                this.Code = Code;
                this.DisplayName = DisplayName;
            }

            public JoinSession()
            {
                this.Code = "";
                this.DisplayName = "";
            }

            string IReducerArgs.ReducerName => "join_session";
        }
    }
}
