// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MarkUploadedHandler(ReducerEventContext ctx, string artifactId);
        public event MarkUploadedHandler? OnMarkUploaded;

        public void MarkUploaded(string artifactId)
        {
            conn.InternalCallReducer(new Reducer.MarkUploaded(artifactId));
        }

        public bool InvokeMarkUploaded(ReducerEventContext ctx, Reducer.MarkUploaded args)
        {
            if (OnMarkUploaded == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMarkUploaded(
                ctx,
                args.ArtifactId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MarkUploaded : Reducer, IReducerArgs
        {
            [DataMember(Name = "artifact_id")]
            public string ArtifactId;

            public MarkUploaded(string ArtifactId)
            {
                this.ArtifactId = ArtifactId;
            }

            public MarkUploaded()
            {
                this.ArtifactId = "";
            }

            string IReducerArgs.ReducerName => "mark_uploaded";
        }
    }
}
