// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PublishExerciseStateHandler(ReducerEventContext ctx, string sessionId, string attemptId, string mode, string? stepId, uint stepIndex, uint stepCount, string? selectedStructureId, bool clearSelectedStructure, string? highlightedStructureId, bool clearHighlightedStructure, bool previewRotating, bool paused, string registration, string? registrationReason, string recording);
        public event PublishExerciseStateHandler? OnPublishExerciseState;

        public void PublishExerciseState(string sessionId, string attemptId, string mode, string? stepId, uint stepIndex, uint stepCount, string? selectedStructureId, bool clearSelectedStructure, string? highlightedStructureId, bool clearHighlightedStructure, bool previewRotating, bool paused, string registration, string? registrationReason, string recording)
        {
            conn.InternalCallReducer(new Reducer.PublishExerciseState(sessionId, attemptId, mode, stepId, stepIndex, stepCount, selectedStructureId, clearSelectedStructure, highlightedStructureId, clearHighlightedStructure, previewRotating, paused, registration, registrationReason, recording));
        }

        public bool InvokePublishExerciseState(ReducerEventContext ctx, Reducer.PublishExerciseState args)
        {
            if (OnPublishExerciseState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPublishExerciseState(
                ctx,
                args.SessionId,
                args.AttemptId,
                args.Mode,
                args.StepId,
                args.StepIndex,
                args.StepCount,
                args.SelectedStructureId,
                args.ClearSelectedStructure,
                args.HighlightedStructureId,
                args.ClearHighlightedStructure,
                args.PreviewRotating,
                args.Paused,
                args.Registration,
                args.RegistrationReason,
                args.Recording
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PublishExerciseState : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "attempt_id")]
            public string AttemptId;
            [DataMember(Name = "mode")]
            public string Mode;
            [DataMember(Name = "step_id")]
            public string? StepId;
            [DataMember(Name = "step_index")]
            public uint StepIndex;
            [DataMember(Name = "step_count")]
            public uint StepCount;
            [DataMember(Name = "selected_structure_id")]
            public string? SelectedStructureId;
            [DataMember(Name = "clear_selected_structure")]
            public bool ClearSelectedStructure;
            [DataMember(Name = "highlighted_structure_id")]
            public string? HighlightedStructureId;
            [DataMember(Name = "clear_highlighted_structure")]
            public bool ClearHighlightedStructure;
            [DataMember(Name = "preview_rotating")]
            public bool PreviewRotating;
            [DataMember(Name = "paused")]
            public bool Paused;
            [DataMember(Name = "registration")]
            public string Registration;
            [DataMember(Name = "registration_reason")]
            public string? RegistrationReason;
            [DataMember(Name = "recording")]
            public string Recording;

            public PublishExerciseState(
                string SessionId,
                string AttemptId,
                string Mode,
                string? StepId,
                uint StepIndex,
                uint StepCount,
                string? SelectedStructureId,
                bool ClearSelectedStructure,
                string? HighlightedStructureId,
                bool ClearHighlightedStructure,
                bool PreviewRotating,
                bool Paused,
                string Registration,
                string? RegistrationReason,
                string Recording
            )
            {
                this.SessionId = SessionId;
                this.AttemptId = AttemptId;
                this.Mode = Mode;
                this.StepId = StepId;
                this.StepIndex = StepIndex;
                this.StepCount = StepCount;
                this.SelectedStructureId = SelectedStructureId;
                this.ClearSelectedStructure = ClearSelectedStructure;
                this.HighlightedStructureId = HighlightedStructureId;
                this.ClearHighlightedStructure = ClearHighlightedStructure;
                this.PreviewRotating = PreviewRotating;
                this.Paused = Paused;
                this.Registration = Registration;
                this.RegistrationReason = RegistrationReason;
                this.Recording = Recording;
            }

            public PublishExerciseState()
            {
                this.SessionId = "";
                this.AttemptId = "";
                this.Mode = "";
                this.Registration = "";
                this.Recording = "";
            }

            string IReducerArgs.ReducerName => "publish_exercise_state";
        }
    }
}
