// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveServiceIdentityHandler(ReducerEventContext ctx, SpacetimeDB.Identity identity);
        public event RemoveServiceIdentityHandler? OnRemoveServiceIdentity;

        public void RemoveServiceIdentity(SpacetimeDB.Identity identity)
        {
            conn.InternalCallReducer(new Reducer.RemoveServiceIdentity(identity));
        }

        public bool InvokeRemoveServiceIdentity(ReducerEventContext ctx, Reducer.RemoveServiceIdentity args)
        {
            if (OnRemoveServiceIdentity == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemoveServiceIdentity(
                ctx,
                args.Identity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveServiceIdentity : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public SpacetimeDB.Identity Identity;

            public RemoveServiceIdentity(SpacetimeDB.Identity Identity)
            {
                this.Identity = Identity;
            }

            public RemoveServiceIdentity()
            {
            }

            string IReducerArgs.ReducerName => "remove_service_identity";
        }
    }
}
