// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveMemberHandler(ReducerEventContext ctx, ulong membershipId);
        public event RemoveMemberHandler? OnRemoveMember;

        public void RemoveMember(ulong membershipId)
        {
            conn.InternalCallReducer(new Reducer.RemoveMember(membershipId));
        }

        public bool InvokeRemoveMember(ReducerEventContext ctx, Reducer.RemoveMember args)
        {
            if (OnRemoveMember == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRemoveMember(
                ctx,
                args.MembershipId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveMember : Reducer, IReducerArgs
        {
            [DataMember(Name = "membership_id")]
            public ulong MembershipId;

            public RemoveMember(ulong MembershipId)
            {
                this.MembershipId = MembershipId;
            }

            public RemoveMember()
            {
            }

            string IReducerArgs.ReducerName => "remove_member";
        }
    }
}
