// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RequestMotionJobHandler(ReducerEventContext ctx, string jobId, string inputArtifactId, System.Collections.Generic.List<string> extraArtifactIds, string configVersion);
        public event RequestMotionJobHandler? OnRequestMotionJob;

        public void RequestMotionJob(string jobId, string inputArtifactId, System.Collections.Generic.List<string> extraArtifactIds, string configVersion)
        {
            conn.InternalCallReducer(new Reducer.RequestMotionJob(jobId, inputArtifactId, extraArtifactIds, configVersion));
        }

        public bool InvokeRequestMotionJob(ReducerEventContext ctx, Reducer.RequestMotionJob args)
        {
            if (OnRequestMotionJob == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRequestMotionJob(
                ctx,
                args.JobId,
                args.InputArtifactId,
                args.ExtraArtifactIds,
                args.ConfigVersion
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RequestMotionJob : Reducer, IReducerArgs
        {
            [DataMember(Name = "job_id")]
            public string JobId;
            [DataMember(Name = "input_artifact_id")]
            public string InputArtifactId;
            [DataMember(Name = "extra_artifact_ids")]
            public System.Collections.Generic.List<string> ExtraArtifactIds;
            [DataMember(Name = "config_version")]
            public string ConfigVersion;

            public RequestMotionJob(
                string JobId,
                string InputArtifactId,
                System.Collections.Generic.List<string> ExtraArtifactIds,
                string ConfigVersion
            )
            {
                this.JobId = JobId;
                this.InputArtifactId = InputArtifactId;
                this.ExtraArtifactIds = ExtraArtifactIds;
                this.ConfigVersion = ConfigVersion;
            }

            public RequestMotionJob()
            {
                this.JobId = "";
                this.InputArtifactId = "";
                this.ExtraArtifactIds = new();
                this.ConfigVersion = "";
            }

            string IReducerArgs.ReducerName => "request_motion_job";
        }
    }
}
