// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RequestDownloadHandler(ReducerEventContext ctx, string grantId, string artifactId);
        public event RequestDownloadHandler? OnRequestDownload;

        public void RequestDownload(string grantId, string artifactId)
        {
            conn.InternalCallReducer(new Reducer.RequestDownload(grantId, artifactId));
        }

        public bool InvokeRequestDownload(ReducerEventContext ctx, Reducer.RequestDownload args)
        {
            if (OnRequestDownload == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRequestDownload(
                ctx,
                args.GrantId,
                args.ArtifactId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RequestDownload : Reducer, IReducerArgs
        {
            [DataMember(Name = "grant_id")]
            public string GrantId;
            [DataMember(Name = "artifact_id")]
            public string ArtifactId;

            public RequestDownload(
                string GrantId,
                string ArtifactId
            )
            {
                this.GrantId = GrantId;
                this.ArtifactId = ArtifactId;
            }

            public RequestDownload()
            {
                this.GrantId = "";
                this.ArtifactId = "";
            }

            string IReducerArgs.ReducerName => "request_download";
        }
    }
}
