// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RequestServiceGrantHandler(ReducerEventContext ctx, string grantId, string sessionId, string kind);
        public event RequestServiceGrantHandler? OnRequestServiceGrant;

        public void RequestServiceGrant(string grantId, string sessionId, string kind)
        {
            conn.InternalCallReducer(new Reducer.RequestServiceGrant(grantId, sessionId, kind));
        }

        public bool InvokeRequestServiceGrant(ReducerEventContext ctx, Reducer.RequestServiceGrant args)
        {
            if (OnRequestServiceGrant == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRequestServiceGrant(
                ctx,
                args.GrantId,
                args.SessionId,
                args.Kind
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RequestServiceGrant : Reducer, IReducerArgs
        {
            [DataMember(Name = "grant_id")]
            public string GrantId;
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "kind")]
            public string Kind;

            public RequestServiceGrant(
                string GrantId,
                string SessionId,
                string Kind
            )
            {
                this.GrantId = GrantId;
                this.SessionId = SessionId;
                this.Kind = Kind;
            }

            public RequestServiceGrant()
            {
                this.GrantId = "";
                this.SessionId = "";
                this.Kind = "";
            }

            string IReducerArgs.ReducerName => "request_service_grant";
        }
    }
}
