// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RetryMotionJobHandler(ReducerEventContext ctx, string jobId);
        public event RetryMotionJobHandler? OnRetryMotionJob;

        public void RetryMotionJob(string jobId)
        {
            conn.InternalCallReducer(new Reducer.RetryMotionJob(jobId));
        }

        public bool InvokeRetryMotionJob(ReducerEventContext ctx, Reducer.RetryMotionJob args)
        {
            if (OnRetryMotionJob == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRetryMotionJob(
                ctx,
                args.JobId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RetryMotionJob : Reducer, IReducerArgs
        {
            [DataMember(Name = "job_id")]
            public string JobId;

            public RetryMotionJob(string JobId)
            {
                this.JobId = JobId;
            }

            public RetryMotionJob()
            {
                this.JobId = "";
            }

            string IReducerArgs.ReducerName => "retry_motion_job";
        }
    }
}
