// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RotateInviteHandler(ReducerEventContext ctx, string sessionId, string role);
        public event RotateInviteHandler? OnRotateInvite;

        public void RotateInvite(string sessionId, string role)
        {
            conn.InternalCallReducer(new Reducer.RotateInvite(sessionId, role));
        }

        public bool InvokeRotateInvite(ReducerEventContext ctx, Reducer.RotateInvite args)
        {
            if (OnRotateInvite == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRotateInvite(
                ctx,
                args.SessionId,
                args.Role
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RotateInvite : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "role")]
            public string Role;

            public RotateInvite(
                string SessionId,
                string Role
            )
            {
                this.SessionId = SessionId;
                this.Role = Role;
            }

            public RotateInvite()
            {
                this.SessionId = "";
                this.Role = "";
            }

            string IReducerArgs.ReducerName => "rotate_invite";
        }
    }
}
