// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetPatientBaselineHandler(ReducerEventContext ctx, string sessionId, double baselineHr, double baselineRr, double baselineSys, double baselineDia, string baselineSource);
        public event SetPatientBaselineHandler? OnSetPatientBaseline;

        public void SetPatientBaseline(string sessionId, double baselineHr, double baselineRr, double baselineSys, double baselineDia, string baselineSource)
        {
            conn.InternalCallReducer(new Reducer.SetPatientBaseline(sessionId, baselineHr, baselineRr, baselineSys, baselineDia, baselineSource));
        }

        public bool InvokeSetPatientBaseline(ReducerEventContext ctx, Reducer.SetPatientBaseline args)
        {
            if (OnSetPatientBaseline == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetPatientBaseline(
                ctx,
                args.SessionId,
                args.BaselineHr,
                args.BaselineRr,
                args.BaselineSys,
                args.BaselineDia,
                args.BaselineSource
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetPatientBaseline : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "baseline_hr")]
            public double BaselineHr;
            [DataMember(Name = "baseline_rr")]
            public double BaselineRr;
            [DataMember(Name = "baseline_sys")]
            public double BaselineSys;
            [DataMember(Name = "baseline_dia")]
            public double BaselineDia;
            [DataMember(Name = "baseline_source")]
            public string BaselineSource;

            public SetPatientBaseline(
                string SessionId,
                double BaselineHr,
                double BaselineRr,
                double BaselineSys,
                double BaselineDia,
                string BaselineSource
            )
            {
                this.SessionId = SessionId;
                this.BaselineHr = BaselineHr;
                this.BaselineRr = BaselineRr;
                this.BaselineSys = BaselineSys;
                this.BaselineDia = BaselineDia;
                this.BaselineSource = BaselineSource;
            }

            public SetPatientBaseline()
            {
                this.SessionId = "";
                this.BaselineSource = "";
            }

            string IReducerArgs.ReducerName => "set_patient_baseline";
        }
    }
}
