// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartEncounterHandler(ReducerEventContext ctx, string encounterId, string sessionId, string patientId, string patientName, string speaker, string speakerName);
        public event StartEncounterHandler? OnStartEncounter;

        public void StartEncounter(string encounterId, string sessionId, string patientId, string patientName, string speaker, string speakerName)
        {
            conn.InternalCallReducer(new Reducer.StartEncounter(encounterId, sessionId, patientId, patientName, speaker, speakerName));
        }

        public bool InvokeStartEncounter(ReducerEventContext ctx, Reducer.StartEncounter args)
        {
            if (OnStartEncounter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch(ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartEncounter(
                ctx,
                args.EncounterId,
                args.SessionId,
                args.PatientId,
                args.PatientName,
                args.Speaker,
                args.SpeakerName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartEncounter : Reducer, IReducerArgs
        {
            [DataMember(Name = "encounter_id")]
            public string EncounterId;
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "patient_id")]
            public string PatientId;
            [DataMember(Name = "patient_name")]
            public string PatientName;
            [DataMember(Name = "speaker")]
            public string Speaker;
            [DataMember(Name = "speaker_name")]
            public string SpeakerName;

            public StartEncounter(
                string EncounterId,
                string SessionId,
                string PatientId,
                string PatientName,
                string Speaker,
                string SpeakerName
            )
            {
                this.EncounterId = EncounterId;
                this.SessionId = SessionId;
                this.PatientId = PatientId;
                this.PatientName = PatientName;
                this.Speaker = Speaker;
                this.SpeakerName = SpeakerName;
            }

            public StartEncounter()
            {
                this.EncounterId = "";
                this.SessionId = "";
                this.PatientId = "";
                this.PatientName = "";
                this.Speaker = "";
                this.SpeakerName = "";
            }

            string IReducerArgs.ReducerName => "start_encounter";
        }
    }
}
