// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartAttemptHandler(ReducerEventContext ctx, string sessionId, string exerciseId, string exerciseVersion);
        public event StartAttemptHandler? OnStartAttempt;

        public void StartAttempt(string sessionId, string exerciseId, string exerciseVersion)
        {
            conn.InternalCallReducer(new Reducer.StartAttempt(sessionId, exerciseId, exerciseVersion));
        }

        public bool InvokeStartAttempt(ReducerEventContext ctx, Reducer.StartAttempt args)
        {
            if (OnStartAttempt == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartAttempt(
                ctx,
                args.SessionId,
                args.ExerciseId,
                args.ExerciseVersion
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartAttempt : Reducer, IReducerArgs
        {
            [DataMember(Name = "session_id")]
            public string SessionId;
            [DataMember(Name = "exercise_id")]
            public string ExerciseId;
            [DataMember(Name = "exercise_version")]
            public string ExerciseVersion;

            public StartAttempt(
                string SessionId,
                string ExerciseId,
                string ExerciseVersion
            )
            {
                this.SessionId = SessionId;
                this.ExerciseId = ExerciseId;
                this.ExerciseVersion = ExerciseVersion;
            }

            public StartAttempt()
            {
                this.SessionId = "";
                this.ExerciseId = "";
                this.ExerciseVersion = "";
            }

            string IReducerArgs.ReducerName => "start_attempt";
        }
    }
}
