// Generates, from the TS catalogs:
// - apps/quest/Assets/Scalpal/Exercises/Generated/ScalpalIds.cs: id constants and the route resolver
// - docs/unity-asset-manifest.md: every mesh, prefab, and port the 3D assets must provide
// Run: npm run gen:unity
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { ANATOMY } from "../src/catalog/anatomy.js";
import { CHECKLIST_LABELS } from "../src/catalog/cases.js";
import { INSTRUMENTS } from "../src/catalog/instruments.js";
import { PROCEDURES } from "../src/catalog/procedures.js";
import { ROUTE_PATTERNS } from "../src/route-patterns.js";
import { validateCatalog } from "../src/validate.js";

export const UNITY_EXERCISES_DIR = join(import.meta.dirname, "../../../apps/quest/Assets/Scalpal/Exercises");
const OUT = join(UNITY_EXERCISES_DIR, "Generated/ScalpalIds.cs");
export const MANIFEST_PATH = join(import.meta.dirname, "../../../docs/unity-asset-manifest.md");

const pascal = (id: string) => id.split(/[_-]/).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("").replace(/^(\d)/, "_$1");
const str = (s: string) => JSON.stringify(s);
const consts = (pairs: [string, string][], indent = "        ") => pairs.map(([n, v]) => `${indent}public const string ${n} = ${str(v)};`).join("\n");

export function generateIds(): string {
  const errors = validateCatalog();
  if (errors.length) throw new Error(`catalog invalid, refusing to generate:\n${errors.join("\n")}`);

  const stepClasses = PROCEDURES.map(
    (p) => `        public static class ${pascal(p.id)}
        {
${consts(p.steps.map((s) => [pascal(s.id), s.id]), "            ")}
        }`,
  ).join("\n\n");

  return `// <auto-generated>
// Generated by services/preop/scripts/gen-unity.ts from the preop catalogs. Do not edit by hand;
// change the catalog and run \`npm run gen:unity\` in services/preop.
// </auto-generated>
using System.Text.RegularExpressions;

namespace Scalpal.Exercises.Generated
{
    // Separately addressable anatomy. Imported meshes must be named with AnatomyUnityNames.
    public static class AnatomyIds
    {
${consts(ANATOMY.map((a) => [pascal(a.id), a.id]))}
    }

    public static class AnatomyUnityNames
    {
${consts(ANATOMY.map((a) => [pascal(a.id), a.unityName]))}

        public static readonly string[] All =
        {
${ANATOMY.map((a) => `            ${pascal(a.id)},`).join("\n")}
        };
    }

    public static class InstrumentIds
    {
${consts(INSTRUMENTS.map((i) => [pascal(i.id), i.id]))}
    }

    public static class InstrumentPrefabs
    {
${consts(INSTRUMENTS.map((i) => [pascal(i.id), i.unityPrefab]))}

        public static readonly string[] All =
        {
${INSTRUMENTS.map((i) => `            ${pascal(i.id)},`).join("\n")}
        };
    }

    public static class ProcedureIds
    {
${consts(PROCEDURES.map((p) => [pascal(p.id), p.id]))}
    }

    public static class StepIds
    {
${stepClasses}
    }

    public static class FlagTypes
    {
${consts((Object.keys(CHECKLIST_LABELS) as string[]).map((t) => [pascal(t), t]))}
    }

    public enum RouteKind
    {
        Unknown,
${ROUTE_PATTERNS.map((r) => `        ${r.kind},`).join("\n")}
    }

    // Every route the service can return in an action. Unknown means a contract break, not a feature.
    public static class ScalpalRoutes
    {
        static readonly (RouteKind kind, string method, Regex pattern)[] Patterns =
        {
${ROUTE_PATTERNS.map((r) => `            (RouteKind.${r.kind}, ${str(r.method)}, new Regex(${str(r.pattern)}, RegexOptions.CultureInvariant)),`).join("\n")}
        };

        public static RouteKind Resolve(string method, string route)
        {
            foreach (var p in Patterns)
            {
                if (p.method == method && p.pattern.IsMatch(route ?? "")) return p.kind;
            }
            return RouteKind.Unknown;
        }
    }
}
`;
}

export function generateManifest(): string {
  const usedBy = (pred: (p: (typeof PROCEDURES)[number]) => boolean) =>
    PROCEDURES.filter(pred).map((p) => p.shortTitle).join(", ") || "risk highlight only";
  const fmt = (n: number) => n.toFixed(2);

  const anatomyRows = ANATOMY.map(
    (a) => `| \`${a.unityName}\` | ${a.displayName} | ${a.system} | ${a.region} | ${usedBy((p) => p.structures.includes(a.id))} |`,
  ).join("\n");
  const instrumentRows = INSTRUMENTS.map(
    (i) => `| \`${i.unityPrefab}\` | ${i.displayName} | ${i.kind} | ${usedBy((p) => p.steps.some((s) => s.instrumentId === i.id) || p.ports.some((port) => port.instrumentIds.includes(i.id)))} |`,
  ).join("\n");
  const procedures = PROCEDURES.map((p) => {
    const ports = p.ports
      .map((port) => `| \`${port.id}\` | ${port.label} | ${port.sizeMm} mm | (${fmt(port.position.x)}, ${fmt(port.position.y)}, ${fmt(port.position.z)}) |`)
      .join("\n");
    const focus = p.focusStructures.map((s) => `\`anat_${s}\``).join(", ");
    return `### ${p.title} (\`${p.id}\`)

${p.steps.length} steps, about ${p.typicalMinutes} minutes. Must read clearly up close: ${focus}.

| Port | Label | Size | Torso position (x, y, z) m |
| --- | --- | --- | --- |
${ports}`;
  }).join("\n\n");

  return `<!-- Generated by services/preop/scripts/gen-unity.ts. Do not edit; change the catalogs and run \`npm run gen:unity\`. -->
# Unity Asset Manifest

Every name below is looked up at runtime. A missing or misnamed object means a step cannot highlight or detect its target. See the [Unity and Blender handoff](unity-handoff.md) for export settings and scene conventions.

## Anatomy meshes (${ANATOMY.length})

One separate object per row, named exactly as shown, each with a collider.

| Object name | Structure | System | Region | Used by |
| --- | --- | --- | --- | --- |
${anatomyRows}

## Instrument prefabs (${INSTRUMENTS.length})

Each prefab needs a trigger collider on a child named \`Tip\` at the working end.

| Prefab name | Instrument | Kind | Used by |
| --- | --- | --- | --- |
${instrumentRows}

## Procedures and ports

Positions are in the torso frame: meters from the umbilicus, +x the participant's left, +y out of the abdomen, +z toward the head. Children scale by \`case.bodyScale\`.

${procedures}
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, generateIds());
  writeFileSync(MANIFEST_PATH, generateManifest());
  console.log(`wrote ${OUT}\nwrote ${MANIFEST_PATH}`);
}
