// Generates apps/quest/Assets/Scalpal/Exercises/Generated/ScalpalIds.cs from the TS catalogs so Unity
// code references ids through constants instead of string literals. Run: npm run gen:unity
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { ANATOMY } from "../src/catalog/anatomy.js";
import { CHECKLIST_LABELS } from "../src/catalog/cases.js";
import { INSTRUMENTS } from "../src/catalog/instruments.js";
import { PROCEDURES } from "../src/catalog/procedures.js";
import { ROUTE_PATTERNS } from "../src/route-patterns.js";
import { validateCatalog } from "../src/validate.js";

export const UNITY_EXERCISES_DIR = join(import.meta.dirname, "../../../apps/quest/Assets/Scalpal/Exercises");
const OUT = join(UNITY_EXERCISES_DIR, "Generated/ScalpalIds.cs");

const pascal = (id: string) => id.split(/[_-]/).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("").replace(/^(\d)/, "_$1");
const str = (s: string) => JSON.stringify(s);
const consts = (pairs: [string, string][], indent = "        ") => pairs.map(([n, v]) => `${indent}public const string ${n} = ${str(v)};`).join("\n");

export function generateIds(): string {
  const errors = validateCatalog();
  if (errors.length) throw new Error(`catalog invalid, refusing to generate:\n${errors.join("\n")}`);

  const stepClasses = PROCEDURES.map(
    (p) => `        public static class ${pascal(p.id)}
        {
${consts(p.steps.map((s) => [pascal(s.id), s.id]), "            ")}
        }`,
  ).join("\n\n");

  return `// <auto-generated>
// Generated by services/preop/scripts/gen-unity.ts from the preop catalogs. Do not edit by hand;
// change the catalog and run \`npm run gen:unity\` in services/preop.
// </auto-generated>
using System.Text.RegularExpressions;

namespace Scalpal.Exercises.Generated
{
    // Separately addressable anatomy. Imported meshes must be named with AnatomyUnityNames.
    public static class AnatomyIds
    {
${consts(ANATOMY.map((a) => [pascal(a.id), a.id]))}
    }

    public static class AnatomyUnityNames
    {
${consts(ANATOMY.map((a) => [pascal(a.id), a.unityName]))}
    }

    public static class InstrumentIds
    {
${consts(INSTRUMENTS.map((i) => [pascal(i.id), i.id]))}
    }

    public static class InstrumentPrefabs
    {
${consts(INSTRUMENTS.map((i) => [pascal(i.id), i.unityPrefab]))}
    }

    public static class ProcedureIds
    {
${consts(PROCEDURES.map((p) => [pascal(p.id), p.id]))}
    }

    public static class StepIds
    {
${stepClasses}
    }

    public static class FlagTypes
    {
${consts((Object.keys(CHECKLIST_LABELS) as string[]).map((t) => [pascal(t), t]))}
    }

    public enum RouteKind
    {
        Unknown,
${ROUTE_PATTERNS.map((r) => `        ${r.kind},`).join("\n")}
    }

    // Every route the service can return in an action. Unknown means a contract break, not a feature.
    public static class ScalpalRoutes
    {
        static readonly (RouteKind kind, string method, Regex pattern)[] Patterns =
        {
${ROUTE_PATTERNS.map((r) => `            (RouteKind.${r.kind}, ${str(r.method)}, new Regex(${str(r.pattern)}, RegexOptions.CultureInvariant)),`).join("\n")}
        };

        public static RouteKind Resolve(string method, string route)
        {
            foreach (var p in Patterns)
            {
                if (p.method == method && p.pattern.IsMatch(route ?? "")) return p.kind;
            }
            return RouteKind.Unknown;
        }
    }
}
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, generateIds());
  console.log(`wrote ${OUT}`);
}
