// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  QualitySummary,
  VerifiedOutput,
} from "./types";

export default {
  jobId: __t.string(),
  run: __t.u32(),
  get outputs() {
    return __t.array(VerifiedOutput);
  },
  get quality() {
    return QualitySummary;
  },
};
