// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AckSignalsReducer from "./ack_signals_reducer";
import AddServiceIdentityReducer from "./add_service_identity_reducer";
import AppendExerciseEventReducer from "./append_exercise_event_reducer";
import CancelMotionJobReducer from "./cancel_motion_job_reducer";
import ClaimMotionJobReducer from "./claim_motion_job_reducer";
import CompleteMotionJobReducer from "./complete_motion_job_reducer";
import ConfirmArtifactReducer from "./confirm_artifact_reducer";
import CreateSessionReducer from "./create_session_reducer";
import DeleteArtifactReducer from "./delete_artifact_reducer";
import DenyGrantReducer from "./deny_grant_reducer";
import DenyServiceGrantReducer from "./deny_service_grant_reducer";
import EndSessionReducer from "./end_session_reducer";
import FailMotionJobReducer from "./fail_motion_job_reducer";
import HeartbeatMotionJobReducer from "./heartbeat_motion_job_reducer";
import IssueGrantReducer from "./issue_grant_reducer";
import IssueServiceGrantReducer from "./issue_service_grant_reducer";
import JoinSessionReducer from "./join_session_reducer";
import LeaveSessionReducer from "./leave_session_reducer";
import MarkUploadedReducer from "./mark_uploaded_reducer";
import PostCoachMessageReducer from "./post_coach_message_reducer";
import PublishExerciseStateReducer from "./publish_exercise_state_reducer";
import RegisterJobOutputReducer from "./register_job_output_reducer";
import RemoveMemberReducer from "./remove_member_reducer";
import RemoveServiceIdentityReducer from "./remove_service_identity_reducer";
import RequestCommandReducer from "./request_command_reducer";
import RequestDownloadReducer from "./request_download_reducer";
import RequestMotionJobReducer from "./request_motion_job_reducer";
import RequestServiceGrantReducer from "./request_service_grant_reducer";
import RequestUploadReducer from "./request_upload_reducer";
import ResolveCommandReducer from "./resolve_command_reducer";
import RetryMotionJobReducer from "./retry_motion_job_reducer";
import RotateInviteReducer from "./rotate_invite_reducer";
import SendSignalReducer from "./send_signal_reducer";
import SetAttemptResultReducer from "./set_attempt_result_reducer";
import SetCoachStatusReducer from "./set_coach_status_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";
import SetMediaSourceReducer from "./set_media_source_reducer";
import SetReplayStateReducer from "./set_replay_state_reducer";
import StartAttemptReducer from "./start_attempt_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AmServiceRow from "./am_service_table";
import MyMembershipsRow from "./my_memberships_table";
import MyRtcSignalsRow from "./my_rtc_signals_table";
import MyServiceGrantsRow from "./my_service_grants_table";
import MySessionsRow from "./my_sessions_table";
import MyTransferGrantsRow from "./my_transfer_grants_table";
import SessionArtifactsRow from "./session_artifacts_table";
import SessionAttemptsRow from "./session_attempts_table";
import SessionCoachMessagesRow from "./session_coach_messages_table";
import SessionCoachStatusRow from "./session_coach_status_table";
import SessionCommandsRow from "./session_commands_table";
import SessionEventsRow from "./session_events_table";
import SessionExerciseStateRow from "./session_exercise_state_table";
import SessionInvitesRow from "./session_invites_table";
import SessionMediaSourceRow from "./session_media_source_table";
import SessionMembersRow from "./session_members_table";
import SessionMotionJobsRow from "./session_motion_jobs_table";
import SessionReplayStateRow from "./session_replay_state_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  amService: __table({
    name: 'am_service',
    indexes: [
    ],
    constraints: [
    ],
  }, AmServiceRow),
  myMemberships: __table({
    name: 'my_memberships',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMembershipsRow),
  myRtcSignals: __table({
    name: 'my_rtc_signals',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRtcSignalsRow),
  myServiceGrants: __table({
    name: 'my_service_grants',
    indexes: [
    ],
    constraints: [
    ],
  }, MyServiceGrantsRow),
  mySessions: __table({
    name: 'my_sessions',
    indexes: [
    ],
    constraints: [
    ],
  }, MySessionsRow),
  myTransferGrants: __table({
    name: 'my_transfer_grants',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTransferGrantsRow),
  sessionArtifacts: __table({
    name: 'session_artifacts',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionArtifactsRow),
  sessionAttempts: __table({
    name: 'session_attempts',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionAttemptsRow),
  sessionCoachMessages: __table({
    name: 'session_coach_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionCoachMessagesRow),
  sessionCoachStatus: __table({
    name: 'session_coach_status',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionCoachStatusRow),
  sessionCommands: __table({
    name: 'session_commands',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionCommandsRow),
  sessionEvents: __table({
    name: 'session_events',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionEventsRow),
  sessionExerciseState: __table({
    name: 'session_exercise_state',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionExerciseStateRow),
  sessionInvites: __table({
    name: 'session_invites',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionInvitesRow),
  sessionMediaSource: __table({
    name: 'session_media_source',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionMediaSourceRow),
  sessionMembers: __table({
    name: 'session_members',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionMembersRow),
  sessionMotionJobs: __table({
    name: 'session_motion_jobs',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionMotionJobsRow),
  sessionReplayState: __table({
    name: 'session_replay_state',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionReplayStateRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("ack_signals", AckSignalsReducer),
  __reducerSchema("add_service_identity", AddServiceIdentityReducer),
  __reducerSchema("append_exercise_event", AppendExerciseEventReducer),
  __reducerSchema("cancel_motion_job", CancelMotionJobReducer),
  __reducerSchema("claim_motion_job", ClaimMotionJobReducer),
  __reducerSchema("complete_motion_job", CompleteMotionJobReducer),
  __reducerSchema("confirm_artifact", ConfirmArtifactReducer),
  __reducerSchema("create_session", CreateSessionReducer),
  __reducerSchema("delete_artifact", DeleteArtifactReducer),
  __reducerSchema("deny_grant", DenyGrantReducer),
  __reducerSchema("deny_service_grant", DenyServiceGrantReducer),
  __reducerSchema("end_session", EndSessionReducer),
  __reducerSchema("fail_motion_job", FailMotionJobReducer),
  __reducerSchema("heartbeat_motion_job", HeartbeatMotionJobReducer),
  __reducerSchema("issue_grant", IssueGrantReducer),
  __reducerSchema("issue_service_grant", IssueServiceGrantReducer),
  __reducerSchema("join_session", JoinSessionReducer),
  __reducerSchema("leave_session", LeaveSessionReducer),
  __reducerSchema("mark_uploaded", MarkUploadedReducer),
  __reducerSchema("post_coach_message", PostCoachMessageReducer),
  __reducerSchema("publish_exercise_state", PublishExerciseStateReducer),
  __reducerSchema("register_job_output", RegisterJobOutputReducer),
  __reducerSchema("remove_member", RemoveMemberReducer),
  __reducerSchema("remove_service_identity", RemoveServiceIdentityReducer),
  __reducerSchema("request_command", RequestCommandReducer),
  __reducerSchema("request_download", RequestDownloadReducer),
  __reducerSchema("request_motion_job", RequestMotionJobReducer),
  __reducerSchema("request_service_grant", RequestServiceGrantReducer),
  __reducerSchema("request_upload", RequestUploadReducer),
  __reducerSchema("resolve_command", ResolveCommandReducer),
  __reducerSchema("retry_motion_job", RetryMotionJobReducer),
  __reducerSchema("rotate_invite", RotateInviteReducer),
  __reducerSchema("send_signal", SendSignalReducer),
  __reducerSchema("set_attempt_result", SetAttemptResultReducer),
  __reducerSchema("set_coach_status", SetCoachStatusReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("set_media_source", SetMediaSourceReducer),
  __reducerSchema("set_replay_state", SetReplayStateReducer),
  __reducerSchema("start_attempt", StartAttemptReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

