// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  membershipId: __t.u64().primaryKey().name("membership_id"),
  sessionId: __t.string().name("session_id"),
  identity: __t.identity(),
  role: __t.string(),
  displayName: __t.string().name("display_name"),
  joinedAt: __t.timestamp().name("joined_at"),
  online: __t.bool(),
});
