// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  artifactId: __t.option(__t.string()).name("artifact_id"),
  playing: __t.bool(),
  positionMs: __t.f64().name("position_ms"),
  rate: __t.f64(),
  updatedAt: __t.timestamp().name("updated_at"),
  updatedBy: __t.identity().name("updated_by"),
});
