// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  attemptId: __t.string().name("attempt_id"),
  exerciseId: __t.string().name("exercise_id"),
  exerciseVersion: __t.string().name("exercise_version"),
  mode: __t.string(),
  stepId: __t.option(__t.string()).name("step_id"),
  stepIndex: __t.u32().name("step_index"),
  stepCount: __t.u32().name("step_count"),
  selectedStructureId: __t.option(__t.string()).name("selected_structure_id"),
  highlightedStructureId: __t.option(__t.string()).name("highlighted_structure_id"),
  previewRotating: __t.bool().name("preview_rotating"),
  paused: __t.bool(),
  registration: __t.string(),
  registrationReason: __t.option(__t.string()).name("registration_reason"),
  recording: __t.string(),
  stateVersion: __t.u64().name("state_version"),
  stepVersion: __t.u64().name("step_version"),
  updatedAt: __t.timestamp().name("updated_at"),
  updatedBy: __t.identity().name("updated_by"),
});
