// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  QualitySummary,
} from "./types";


export default __t.row({
  jobId: __t.string().primaryKey().name("job_id"),
  dedupeKey: __t.string().name("dedupe_key"),
  sessionId: __t.string().name("session_id"),
  attemptId: __t.string().name("attempt_id"),
  inputArtifactId: __t.string().name("input_artifact_id"),
  extraArtifactIds: __t.array(__t.string()).name("extra_artifact_ids"),
  configVersion: __t.string().name("config_version"),
  status: __t.string(),
  run: __t.u32(),
  maxRuns: __t.u32().name("max_runs"),
  workerId: __t.option(__t.string()).name("worker_id"),
  leaseExpiresAt: __t.option(__t.timestamp()).name("lease_expires_at"),
  progress: __t.option(__t.f64()),
  stage: __t.option(__t.string()),
  outputArtifactIds: __t.array(__t.string()).name("output_artifact_ids"),
  get quality() {
    return __t.option(QualitySummary);
  },
  error: __t.option(__t.string()),
  requestedBy: __t.identity().name("requested_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
