// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  coachSessionId: __t.string().name("coach_session_id"),
  baselineHr: __t.f64().name("baseline_hr"),
  baselineRr: __t.f64().name("baseline_rr"),
  baselineSys: __t.f64().name("baseline_sys"),
  baselineDia: __t.f64().name("baseline_dia"),
  baselineSpo2: __t.f64().name("baseline_spo_2"),
  baselineSource: __t.string().name("baseline_source"),
  weightKg: __t.f64().name("weight_kg"),
  mlPerKg: __t.f64().name("ml_per_kg"),
  ebvMl: __t.f64().name("ebv_ml"),
  scale: __t.f64(),
  hr: __t.i32(),
  rr: __t.i32(),
  sys: __t.i32(),
  dia: __t.i32(),
  spo2: __t.i32().name("spo_2"),
  bloodLossPct: __t.f64().name("blood_loss_pct"),
  hemorrhageClass: __t.u32().name("hemorrhage_class"),
  label: __t.string(),
  bodyLostMl: __t.f64().name("body_lost_ml"),
  regionLostMl: __t.f64().name("region_lost_ml"),
  bloodLostMl: __t.f64().name("blood_lost_ml"),
  bodyBleedMlPerMin: __t.f64().name("body_bleed_ml_per_min"),
  activeBleedsJson: __t.string().name("active_bleeds_json"),
  regionInjuriesJson: __t.string().name("region_injuries_json"),
  outcomeResult: __t.string().name("outcome_result"),
  outcomeCause: __t.string().name("outcome_cause"),
  outcomeAt: __t.option(__t.timestamp()).name("outcome_at"),
  version: __t.u64(),
  startedAt: __t.timestamp().name("started_at"),
  advancedAt: __t.timestamp().name("advanced_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
