// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AmService = __t.object("AmService", {});
export type AmService = __Infer<typeof AmService>;

export const Artifact = __t.object("Artifact", {
  artifactId: __t.string(),
  sessionId: __t.string(),
  attemptId: __t.string(),
  kind: __t.string(),
  storageKey: __t.string(),
  filename: __t.string(),
  contentType: __t.string(),
  declaredBytes: __t.option(__t.u64()),
  verifiedBytes: __t.option(__t.u64()),
  sha256: __t.option(__t.string()),
  status: __t.string(),
  statusReason: __t.option(__t.string()),
  jobId: __t.option(__t.string()),
  jobRun: __t.option(__t.u32()),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  availableAt: __t.option(__t.timestamp()),
});
export type Artifact = __Infer<typeof Artifact>;

export const Attempt = __t.object("Attempt", {
  attemptId: __t.string(),
  sessionId: __t.string(),
  ordinal: __t.u32(),
  exerciseId: __t.string(),
  exerciseVersion: __t.string(),
  startedAt: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
  practiceStatus: __t.string(),
  resultSummary: __t.option(__t.string()),
  stepsCompleted: __t.u32(),
  stepsTotal: __t.u32(),
  mistakes: __t.u32(),
  hintsUsed: __t.u32(),
});
export type Attempt = __Infer<typeof Attempt>;

export const CoachMessage = __t.object("CoachMessage", {
  messageId: __t.u64(),
  sessionId: __t.string(),
  attemptId: __t.string(),
  speaker: __t.string(),
  text: __t.string(),
  at: __t.timestamp(),
});
export type CoachMessage = __Infer<typeof CoachMessage>;

export const CoachStatus = __t.object("CoachStatus", {
  sessionId: __t.string(),
  status: __t.string(),
  detail: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type CoachStatus = __Infer<typeof CoachStatus>;

export const Command = __t.object("Command", {
  commandId: __t.string(),
  sessionId: __t.string(),
  attemptId: __t.string(),
  action: __t.string(),
  targetId: __t.option(__t.string()),
  argBool: __t.option(__t.bool()),
  argNumber: __t.option(__t.f64()),
  expectedStepVersion: __t.u64(),
  requestedBy: __t.identity(),
  requestedRole: __t.string(),
  requestedAt: __t.timestamp(),
  status: __t.string(),
  reason: __t.option(__t.string()),
  resolvedAt: __t.option(__t.timestamp()),
  resolvedStateVersion: __t.option(__t.u64()),
});
export type Command = __Infer<typeof Command>;

export const Connection = __t.object("Connection", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
  connectedAt: __t.timestamp(),
});
export type Connection = __Infer<typeof Connection>;

export const ExerciseEvent = __t.object("ExerciseEvent", {
  eventId: __t.u64(),
  sessionId: __t.string(),
  attemptId: __t.string(),
  kind: __t.string(),
  stepId: __t.option(__t.string()),
  structureId: __t.option(__t.string()),
  message: __t.string(),
  deviceTimeMs: __t.option(__t.f64()),
  at: __t.timestamp(),
});
export type ExerciseEvent = __Infer<typeof ExerciseEvent>;

export const ExerciseState = __t.object("ExerciseState", {
  sessionId: __t.string(),
  attemptId: __t.string(),
  exerciseId: __t.string(),
  exerciseVersion: __t.string(),
  mode: __t.string(),
  stepId: __t.option(__t.string()),
  stepIndex: __t.u32(),
  stepCount: __t.u32(),
  selectedStructureId: __t.option(__t.string()),
  highlightedStructureId: __t.option(__t.string()),
  previewRotating: __t.bool(),
  paused: __t.bool(),
  registration: __t.string(),
  registrationReason: __t.option(__t.string()),
  recording: __t.string(),
  stateVersion: __t.u64(),
  stepVersion: __t.u64(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.identity(),
});
export type ExerciseState = __Infer<typeof ExerciseState>;

export const MediaSource = __t.object("MediaSource", {
  sessionId: __t.string(),
  publisher: __t.option(__t.identity()),
  status: __t.string(),
  label: __t.option(__t.string()),
  detail: __t.option(__t.string()),
  width: __t.option(__t.u32()),
  height: __t.option(__t.u32()),
  updatedAt: __t.timestamp(),
});
export type MediaSource = __Infer<typeof MediaSource>;

export const Membership = __t.object("Membership", {
  membershipId: __t.u64(),
  sessionId: __t.string(),
  identity: __t.identity(),
  role: __t.string(),
  displayName: __t.string(),
  joinedAt: __t.timestamp(),
});
export type Membership = __Infer<typeof Membership>;

export const MotionJob = __t.object("MotionJob", {
  jobId: __t.string(),
  dedupeKey: __t.string(),
  sessionId: __t.string(),
  attemptId: __t.string(),
  inputArtifactId: __t.string(),
  extraArtifactIds: __t.array(__t.string()),
  configVersion: __t.string(),
  status: __t.string(),
  run: __t.u32(),
  maxRuns: __t.u32(),
  workerId: __t.option(__t.string()),
  leaseExpiresAt: __t.option(__t.timestamp()),
  progress: __t.option(__t.f64()),
  stage: __t.option(__t.string()),
  outputArtifactIds: __t.array(__t.string()),
  get quality() {
    return __t.option(QualitySummary);
  },
  error: __t.option(__t.string()),
  requestedBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type MotionJob = __Infer<typeof MotionJob>;

export const MyMemberships = __t.object("MyMemberships", {});
export type MyMemberships = __Infer<typeof MyMemberships>;

export const MyRtcSignals = __t.object("MyRtcSignals", {});
export type MyRtcSignals = __Infer<typeof MyRtcSignals>;

export const MyServiceGrants = __t.object("MyServiceGrants", {});
export type MyServiceGrants = __Infer<typeof MyServiceGrants>;

export const MySessions = __t.object("MySessions", {});
export type MySessions = __Infer<typeof MySessions>;

export const MyTransferGrants = __t.object("MyTransferGrants", {});
export type MyTransferGrants = __Infer<typeof MyTransferGrants>;

export const QualitySummary = __t.object("QualitySummary", {
  framesTotal: __t.u32(),
  framesValid: __t.u32(),
  invalidIntervals: __t.u32(),
  robotModel: __t.string(),
  replayKind: __t.string(),
  notes: __t.string(),
});
export type QualitySummary = __Infer<typeof QualitySummary>;

export const ReplayState = __t.object("ReplayState", {
  sessionId: __t.string(),
  artifactId: __t.option(__t.string()),
  playing: __t.bool(),
  positionMs: __t.f64(),
  rate: __t.f64(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.identity(),
});
export type ReplayState = __Infer<typeof ReplayState>;

export const RtcSignal = __t.object("RtcSignal", {
  signalId: __t.u64(),
  sessionId: __t.string(),
  from: __t.identity(),
  to: __t.identity(),
  peerId: __t.string(),
  kind: __t.string(),
  payload: __t.string(),
  createdAt: __t.timestamp(),
});
export type RtcSignal = __Infer<typeof RtcSignal>;

export const ServiceFlag = __t.object("ServiceFlag", {
  identity: __t.identity(),
  label: __t.string(),
});
export type ServiceFlag = __Infer<typeof ServiceFlag>;

export const ServiceGrant = __t.object("ServiceGrant", {
  grantId: __t.string(),
  sessionId: __t.string(),
  kind: __t.string(),
  requestedBy: __t.identity(),
  requestedAt: __t.timestamp(),
  status: __t.string(),
  payload: __t.option(__t.string()),
  reason: __t.option(__t.string()),
  expiresAt: __t.option(__t.timestamp()),
});
export type ServiceGrant = __Infer<typeof ServiceGrant>;

export const ServiceIdentity = __t.object("ServiceIdentity", {
  identity: __t.identity(),
  label: __t.string(),
  addedAt: __t.timestamp(),
});
export type ServiceIdentity = __Infer<typeof ServiceIdentity>;

export const Session = __t.object("Session", {
  sessionId: __t.string(),
  label: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  status: __t.string(),
  exerciseId: __t.string(),
  exerciseVersion: __t.string(),
  currentAttemptId: __t.string(),
  attemptCount: __t.u32(),
  endedAt: __t.option(__t.timestamp()),
});
export type Session = __Infer<typeof Session>;

export const SessionArtifacts = __t.object("SessionArtifacts", {});
export type SessionArtifacts = __Infer<typeof SessionArtifacts>;

export const SessionAttempts = __t.object("SessionAttempts", {});
export type SessionAttempts = __Infer<typeof SessionAttempts>;

export const SessionCoachMessages = __t.object("SessionCoachMessages", {});
export type SessionCoachMessages = __Infer<typeof SessionCoachMessages>;

export const SessionCoachStatus = __t.object("SessionCoachStatus", {});
export type SessionCoachStatus = __Infer<typeof SessionCoachStatus>;

export const SessionCommands = __t.object("SessionCommands", {});
export type SessionCommands = __Infer<typeof SessionCommands>;

export const SessionEvents = __t.object("SessionEvents", {});
export type SessionEvents = __Infer<typeof SessionEvents>;

export const SessionExerciseState = __t.object("SessionExerciseState", {});
export type SessionExerciseState = __Infer<typeof SessionExerciseState>;

export const SessionInvite = __t.object("SessionInvite", {
  code: __t.string(),
  sessionId: __t.string(),
  role: __t.string(),
  createdAt: __t.timestamp(),
  revoked: __t.bool(),
});
export type SessionInvite = __Infer<typeof SessionInvite>;

export const SessionInvites = __t.object("SessionInvites", {});
export type SessionInvites = __Infer<typeof SessionInvites>;

export const SessionMediaSource = __t.object("SessionMediaSource", {});
export type SessionMediaSource = __Infer<typeof SessionMediaSource>;

export const SessionMember = __t.object("SessionMember", {
  membershipId: __t.u64(),
  sessionId: __t.string(),
  identity: __t.identity(),
  role: __t.string(),
  displayName: __t.string(),
  joinedAt: __t.timestamp(),
  online: __t.bool(),
});
export type SessionMember = __Infer<typeof SessionMember>;

export const SessionMembers = __t.object("SessionMembers", {});
export type SessionMembers = __Infer<typeof SessionMembers>;

export const SessionMotionJobs = __t.object("SessionMotionJobs", {});
export type SessionMotionJobs = __Infer<typeof SessionMotionJobs>;

export const SessionReplayState = __t.object("SessionReplayState", {});
export type SessionReplayState = __Infer<typeof SessionReplayState>;

export const SweepTimer = __t.object("SweepTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SweepTimer = __Infer<typeof SweepTimer>;

export const TransferGrant = __t.object("TransferGrant", {
  grantId: __t.string(),
  sessionId: __t.string(),
  artifactId: __t.string(),
  direction: __t.string(),
  requestedBy: __t.identity(),
  requestedAt: __t.timestamp(),
  status: __t.string(),
  url: __t.option(__t.string()),
  method: __t.option(__t.string()),
  reason: __t.option(__t.string()),
  expiresAt: __t.option(__t.timestamp()),
});
export type TransferGrant = __Infer<typeof TransferGrant>;

export const VerifiedOutput = __t.object("VerifiedOutput", {
  artifactId: __t.string(),
  verifiedBytes: __t.u64(),
});
export type VerifiedOutput = __Infer<typeof VerifiedOutput>;
