// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  signalId: __t.u64().primaryKey().name("signal_id"),
  sessionId: __t.string().name("session_id"),
  from: __t.identity(),
  to: __t.identity(),
  peerId: __t.string().name("peer_id"),
  kind: __t.string(),
  payload: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
