// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  commandId: __t.string(),
  sessionId: __t.string(),
  action: __t.string(),
  targetId: __t.option(__t.string()),
  argBool: __t.option(__t.bool()),
  argNumber: __t.option(__t.f64()),
  expectedStepVersion: __t.u64(),
};
