// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  grantId: __t.string(),
  artifactId: __t.string(),
  sessionId: __t.string(),
  attemptId: __t.string(),
  kind: __t.string(),
  filename: __t.string(),
  contentType: __t.string(),
  declaredBytes: __t.option(__t.u64()),
  sha256: __t.option(__t.string()),
};
