// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  attemptId: __t.string().primaryKey().name("attempt_id"),
  sessionId: __t.string().name("session_id"),
  ordinal: __t.u32(),
  exerciseId: __t.string().name("exercise_id"),
  exerciseVersion: __t.string().name("exercise_version"),
  startedAt: __t.timestamp().name("started_at"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
  practiceStatus: __t.string().name("practice_status"),
  resultSummary: __t.option(__t.string()).name("result_summary"),
  stepsCompleted: __t.u32().name("steps_completed"),
  stepsTotal: __t.u32().name("steps_total"),
  mistakes: __t.u32(),
  hintsUsed: __t.u32().name("hints_used"),
});
