// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.string(),
  coachSessionId: __t.string(),
  baselineHr: __t.f64(),
  baselineRr: __t.f64(),
  baselineSys: __t.f64(),
  baselineDia: __t.f64(),
  baselineSpo2: __t.f64(),
  baselineSource: __t.string(),
  weightKg: __t.f64(),
  mlPerKg: __t.f64(),
};
