// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  label: __t.string(),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  status: __t.string(),
  exerciseId: __t.string().name("exercise_id"),
  exerciseVersion: __t.string().name("exercise_version"),
  currentAttemptId: __t.string().name("current_attempt_id"),
  attemptCount: __t.u32().name("attempt_count"),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
});
