// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  grantId: __t.string().primaryKey().name("grant_id"),
  sessionId: __t.string().name("session_id"),
  kind: __t.string(),
  requestedBy: __t.identity().name("requested_by"),
  requestedAt: __t.timestamp().name("requested_at"),
  status: __t.string(),
  payload: __t.option(__t.string()),
  reason: __t.option(__t.string()),
  expiresAt: __t.option(__t.timestamp()).name("expires_at"),
});
