// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.string(),
  attemptId: __t.string(),
  mode: __t.string(),
  stepId: __t.option(__t.string()),
  stepIndex: __t.u32(),
  stepCount: __t.u32(),
  selectedStructureId: __t.option(__t.string()),
  clearSelectedStructure: __t.bool(),
  highlightedStructureId: __t.option(__t.string()),
  clearHighlightedStructure: __t.bool(),
  previewRotating: __t.bool(),
  paused: __t.bool(),
  registration: __t.string(),
  registrationReason: __t.option(__t.string()),
  recording: __t.string(),
};
