// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  commandId: __t.string().primaryKey().name("command_id"),
  sessionId: __t.string().name("session_id"),
  attemptId: __t.string().name("attempt_id"),
  action: __t.string(),
  targetId: __t.option(__t.string()).name("target_id"),
  argBool: __t.option(__t.bool()).name("arg_bool"),
  argNumber: __t.option(__t.f64()).name("arg_number"),
  expectedStepVersion: __t.u64().name("expected_step_version"),
  requestedBy: __t.identity().name("requested_by"),
  requestedRole: __t.string().name("requested_role"),
  requestedAt: __t.timestamp().name("requested_at"),
  status: __t.string(),
  reason: __t.option(__t.string()),
  resolvedAt: __t.option(__t.timestamp()).name("resolved_at"),
  resolvedStateVersion: __t.option(__t.u64()).name("resolved_state_version"),
});
