// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  artifactId: __t.string().primaryKey().name("artifact_id"),
  sessionId: __t.string().name("session_id"),
  attemptId: __t.string().name("attempt_id"),
  kind: __t.string(),
  storageKey: __t.string().name("storage_key"),
  filename: __t.string(),
  contentType: __t.string().name("content_type"),
  declaredBytes: __t.option(__t.u64()).name("declared_bytes"),
  verifiedBytes: __t.option(__t.u64()).name("verified_bytes"),
  sha256: __t.option(__t.string()).name("sha_256"),
  status: __t.string(),
  statusReason: __t.option(__t.string()).name("status_reason"),
  jobId: __t.option(__t.string()).name("job_id"),
  jobRun: __t.option(__t.u32()).name("job_run"),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  availableAt: __t.option(__t.timestamp()).name("available_at"),
});
