// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  encounterId: __t.string().primaryKey().name("encounter_id"),
  sessionId: __t.string().name("session_id"),
  attemptId: __t.string().name("attempt_id"),
  patientId: __t.string().name("patient_id"),
  patientName: __t.string().name("patient_name"),
  speaker: __t.string(),
  speakerName: __t.string().name("speaker_name"),
  phase: __t.string(),
  scoreTotal: __t.option(__t.u32()).name("score_total"),
  grade: __t.option(__t.string()),
  scorecardJson: __t.option(__t.string()).name("scorecard_json"),
  startedAt: __t.timestamp().name("started_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
