// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  sessionId: __t.string().name("session_id"),
  attemptId: __t.string().name("attempt_id"),
  kind: __t.string(),
  stepId: __t.option(__t.string()).name("step_id"),
  structureId: __t.option(__t.string()).name("structure_id"),
  message: __t.string(),
  deviceTimeMs: __t.option(__t.f64()).name("device_time_ms"),
  at: __t.timestamp(),
});
