// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AckSignalsReducer from "../ack_signals_reducer";
import AddServiceIdentityReducer from "../add_service_identity_reducer";
import AppendExerciseEventReducer from "../append_exercise_event_reducer";
import CancelMotionJobReducer from "../cancel_motion_job_reducer";
import ClaimMotionJobReducer from "../claim_motion_job_reducer";
import CompleteMotionJobReducer from "../complete_motion_job_reducer";
import ConfirmArtifactReducer from "../confirm_artifact_reducer";
import CreateSessionReducer from "../create_session_reducer";
import DeleteArtifactReducer from "../delete_artifact_reducer";
import DenyGrantReducer from "../deny_grant_reducer";
import DenyServiceGrantReducer from "../deny_service_grant_reducer";
import EndSessionReducer from "../end_session_reducer";
import FailMotionJobReducer from "../fail_motion_job_reducer";
import HeartbeatMotionJobReducer from "../heartbeat_motion_job_reducer";
import IssueGrantReducer from "../issue_grant_reducer";
import IssueServiceGrantReducer from "../issue_service_grant_reducer";
import JoinSessionReducer from "../join_session_reducer";
import LeaveSessionReducer from "../leave_session_reducer";
import MarkUploadedReducer from "../mark_uploaded_reducer";
import PostCoachMessageReducer from "../post_coach_message_reducer";
import PublishExerciseStateReducer from "../publish_exercise_state_reducer";
import RegisterJobOutputReducer from "../register_job_output_reducer";
import RemoveMemberReducer from "../remove_member_reducer";
import RemoveServiceIdentityReducer from "../remove_service_identity_reducer";
import RequestCommandReducer from "../request_command_reducer";
import RequestDownloadReducer from "../request_download_reducer";
import RequestMotionJobReducer from "../request_motion_job_reducer";
import RequestServiceGrantReducer from "../request_service_grant_reducer";
import RequestUploadReducer from "../request_upload_reducer";
import ResolveCommandReducer from "../resolve_command_reducer";
import RetryMotionJobReducer from "../retry_motion_job_reducer";
import RotateInviteReducer from "../rotate_invite_reducer";
import SendSignalReducer from "../send_signal_reducer";
import SetAttemptResultReducer from "../set_attempt_result_reducer";
import SetCoachStatusReducer from "../set_coach_status_reducer";
import SetDisplayNameReducer from "../set_display_name_reducer";
import SetMediaSourceReducer from "../set_media_source_reducer";
import SetReplayStateReducer from "../set_replay_state_reducer";
import StartAttemptReducer from "../start_attempt_reducer";

export type AckSignalsParams = __Infer<typeof AckSignalsReducer>;
export type AddServiceIdentityParams = __Infer<typeof AddServiceIdentityReducer>;
export type AppendExerciseEventParams = __Infer<typeof AppendExerciseEventReducer>;
export type CancelMotionJobParams = __Infer<typeof CancelMotionJobReducer>;
export type ClaimMotionJobParams = __Infer<typeof ClaimMotionJobReducer>;
export type CompleteMotionJobParams = __Infer<typeof CompleteMotionJobReducer>;
export type ConfirmArtifactParams = __Infer<typeof ConfirmArtifactReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type DeleteArtifactParams = __Infer<typeof DeleteArtifactReducer>;
export type DenyGrantParams = __Infer<typeof DenyGrantReducer>;
export type DenyServiceGrantParams = __Infer<typeof DenyServiceGrantReducer>;
export type EndSessionParams = __Infer<typeof EndSessionReducer>;
export type FailMotionJobParams = __Infer<typeof FailMotionJobReducer>;
export type HeartbeatMotionJobParams = __Infer<typeof HeartbeatMotionJobReducer>;
export type IssueGrantParams = __Infer<typeof IssueGrantReducer>;
export type IssueServiceGrantParams = __Infer<typeof IssueServiceGrantReducer>;
export type JoinSessionParams = __Infer<typeof JoinSessionReducer>;
export type LeaveSessionParams = __Infer<typeof LeaveSessionReducer>;
export type MarkUploadedParams = __Infer<typeof MarkUploadedReducer>;
export type PostCoachMessageParams = __Infer<typeof PostCoachMessageReducer>;
export type PublishExerciseStateParams = __Infer<typeof PublishExerciseStateReducer>;
export type RegisterJobOutputParams = __Infer<typeof RegisterJobOutputReducer>;
export type RemoveMemberParams = __Infer<typeof RemoveMemberReducer>;
export type RemoveServiceIdentityParams = __Infer<typeof RemoveServiceIdentityReducer>;
export type RequestCommandParams = __Infer<typeof RequestCommandReducer>;
export type RequestDownloadParams = __Infer<typeof RequestDownloadReducer>;
export type RequestMotionJobParams = __Infer<typeof RequestMotionJobReducer>;
export type RequestServiceGrantParams = __Infer<typeof RequestServiceGrantReducer>;
export type RequestUploadParams = __Infer<typeof RequestUploadReducer>;
export type ResolveCommandParams = __Infer<typeof ResolveCommandReducer>;
export type RetryMotionJobParams = __Infer<typeof RetryMotionJobReducer>;
export type RotateInviteParams = __Infer<typeof RotateInviteReducer>;
export type SendSignalParams = __Infer<typeof SendSignalReducer>;
export type SetAttemptResultParams = __Infer<typeof SetAttemptResultReducer>;
export type SetCoachStatusParams = __Infer<typeof SetCoachStatusReducer>;
export type SetDisplayNameParams = __Infer<typeof SetDisplayNameReducer>;
export type SetMediaSourceParams = __Infer<typeof SetMediaSourceReducer>;
export type SetReplayStateParams = __Infer<typeof SetReplayStateReducer>;
export type StartAttemptParams = __Infer<typeof StartAttemptReducer>;

